### ISSUE TITLE
LibreSprite

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#1019]
To help us make adding AppImages quicker and easier, please try to follow the following two syntaxes.

## If available on Github.com
- name libresprite
- repository https://github.com/LibreSprite/LibreSprite

(Have a good day ivan-hc ur a real one <3 )

**Comment by Twig6943** [comment]
(pls add the latest version too) (1.1)

**Comment by ivan-hc** [comment]
I didn't remember having this app, it was already available in the repository and I had to update the script, not add a new one. I accidentally added two entries to the list.

**Comment by Twig6943** [comment]
Could u add [PINCE](https://github.com/korcankaraokcu/PINCE/releases) to the DB too?

**Comment by ivan-hc** [comment]
done

**Comment by Twig6943** [comment]
@ivan-hc the pkg does install but could u make it so that the desktop file has sudo -E in the "Exec" part (and also triggers the polkit) otherwise the app won't boot since it needs elevated privileges

**Comment by ivan-hc** [comment]
> @ivan-hc the pkg does install. could u add sudo -E to the "Exec" part of the .desktop file (and also needs to trigger the polkit) otherwise the app won't boot since it needs elevated privileges

I noticed that the app have no icon, is Ponce an app to run from command line?

Anyway, this is the original .desktop file
```
[Desktop Entry]
Name=PINCE
Exec=PINCE
Icon=PINCE
Type=Application
Terminal=true
Categories=Development;
```
and this is the one changed in AppMan
```
[Desktop Entry]
Name=PINCE
Exec=/home/ivan/.local/bin/pince
Icon=/home/ivan/.local/share/appman/pince/icons/pince
Type=Application
Terminal=true
Categories=Development;
```
also, in their documentation they say to run it from the terminal https://github.com/korcankaraokcu/PINCE#users

Maybe I should remove the creation of the launcher from the script, as I do with "wine"

**Comment by Twig6943** [comment]
Yep turns out the app is meant to be executed from a terminal. (Also doesnt seem to have an icon)

**Comment by ivan-hc** [comment]
@Twig6943 ti suggerisco di chiedere loro di implementare un prompt per la richiesta della password direttamente nell'applicazione, preferisco non alterare ciò che gli sviluppatori hanno creato (icona e launcher), poichè in futuro la loro app potrebbe cambiare.

**Comment by Twig6943** [comment]
ayo @ivan-hc could u make "PINCE" 's .desktop file to this
(Also here's the [icon](https://raw.githubusercontent.com/korcankaraokcu/PINCE/refs/heads/master/media/logo/ozgurozbek/pince_big_transparent.png) )

[Desktop Entry]
Name=Pince
Exec=sudo -E pince
Icon=/opt/pince/icons/pince.png
Type=Application
GenericName=Reverse engineering tool for linux games.
Terminal=true
Categories=Game;Development;
Keywords=cheat;engine;game;reverse;

**Comment by Twig6943** [comment]
@ivan-hc could u fix this too? (u seem to be online rn)

have a good one 👑

**Comment by ivan-hc** [comment]
Please, see what I wrote in the other issue https://github.com/ivan-hc/AM/issues/1049#issuecomment-2453507197

**Comment by ivan-hc** [comment]
Not for anything, but the person directly interested in using these applications, is you. Only you know how they work and what doesn't work. I can only provide the basic script, but it's up to you to figure out what to change in order to make them work properly.

Personally, my job is just to add the apps, but I don't know them, and I don't want to fill my $HOME with dotfiles of programs I won't use.

I could keep testing the scripts and not make them work as you want, forever... that's why it's up to you to fix them. You know these programs. You know the name of the files from which to make them work.

The installation scripts are divided into "sections", each with its own title (they start with `#` and explain what the listed processes do). It shouldn't be difficult to understand how they work.

If you're good enough not to accidentally add a `rm -Rf /` and erase the entire memory, you're already on the right track.

In your case, the problems are mainly related to the binary files (the lines starting with `chmod` and `ln -s`) and the .desktop file. You should not alter the script text too much, to do your analysis safely.
