### ISSUE TITLE
Universal Media Server

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#1020]
To help us make adding AppImages quicker and easier, please try to follow the following two syntaxes.

## If available on Github.com
- name ums/universal-media-server
- repository https://github.com/UniversalMediaServer/UniversalMediaServer

(An they still don't provide an AppImage https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1701
Binaries can be found [here](https://github.com/UniversalMediaServer/UniversalMediaServer/releases/download/14.5.1/UMS-14.5.1-x86_64.tgz) )

**Comment by ivan-hc** [comment]
man, I have understand that thei don't provide an AppImage, but when they only provide portable apps, there is a dedicated template to compile for this request, named "**Add portable apps (NOT AppImages)**" https://github.com/ivan-hc/AM/issues/new?assignees=&labels=&projects=&template=add-portable-apps--not-appimages-.md&title= I wrote it on purpose so that you can provide us with more details to create a .desktop file and have an icon, precisely "to help us", as I say in the template.

So please, stick to the template I provided. Thanks.

**Comment by Twig6943** [comment]
Sure thing (sorry)

**Comment by ivan-hc** [comment]
I understand that the templates are not intuitive enough, later I will work on making them more "user friendly". I promise.
