### ISSUE TITLE
Kitty

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#1049]
To help us make adding applications quicker and easier, please follow the syntax below (**NOTE that if point 2 is a github repository, you can remove points 3 and 4**, and **if the program is a CLI you can remove point 5 and 6**).

Arch:amd64,arm64
![image](https://github.com/user-attachments/assets/4841a688-ea90-4225-9196-fa665acc2d99)

1. name: kitty
2. main site: https://github.com/kovidgoyal/kitty
3. download page: https://github.com/kovidgoyal/kitty/releases
4. description of the application: Cross-platform, fast, feature-rich, GPU based terminal
5. URL to the application icon: https://raw.githubusercontent.com/kovidgoyal/kitty/refs/heads/master/logo/kitty.png
6. the .desktop* file (choose whether to add a URL, to paste the content of the file, to drag a text file into your comment or to provide only the following 3 desktop entries, `Name=`, `Exec=` and `Categories=`

.Desktop entry (grabbed from the .txz) ;
[Desktop Entry]
Version=1.0
Type=Application
Name=kitty
GenericName=Terminal emulator
Comment=Fast, feature-rich, GPU based terminal
TryExec=kitty
StartupNotify=true
Exec=kitty
Icon=kitty
Categories=System;TerminalEmulator;

**Comment by ivan-hc** [comment]
they have a static binary, I think it is better, isn't?

**Comment by Twig6943** [comment]
@ivan-hc please rename this pkg to "kitten" (it instead downloads binaries for a project called kitten (its from the same developer, really sorry for the mix up ) )
![image](https://github.com/user-attachments/assets/25350e10-8a0d-4bb0-8ef0-48c08ae0dccc)

**Comment by Twig6943** [comment]
nvm (but im not sure) (this pkg seems to be acting funny)

**Comment by Twig6943** [comment]
output of "am -i kitty"
![image](https://github.com/user-attachments/assets/297a7241-45da-4967-88f9-5f3eef8f1322)

**Comment by Twig6943** [comment]
/opt/kitty does have the kitty binary but when I execute it
![image](https://github.com/user-attachments/assets/fee63cd2-8786-4ab5-b6cd-4ba33b01d8ad)

Video:
https://github.com/user-attachments/assets/5c6f56bf-82dc-486d-84fa-119bc512698c

When I run
sudo pacman -S kitty && kitty

kitty (the terminal emulator) run instead
![image](https://github.com/user-attachments/assets/2a90600d-b65d-47c0-bd6a-b713b3e63c76)

**Comment by Twig6943** [comment]
as of writing this the latest nightly version does have a "kitty" binary as well as a "kitten" one

and when I extract & and run that it works
![image](https://github.com/user-attachments/assets/cb80596e-883a-480c-90dc-154f504fc45b)

**Comment by Twig6943** [comment]
(this issue might only be happening on me I havent tested "am -i kitty" on any other machines)

**Comment by ivan-hc** [comment]
I suggest to investigate
```
am -R kitty
am -d kitty
```
then read the script and understand how the symlink works, maybe you should chang `ln -s /opt/$APP/$APP` to `ln -s /opt/$APP/kitten`... or maybe the issue is elsewhere.

To tast your changes, drag/drop the script in the terminal, after `am -i`, like this:
```
am -i /path/to/your/script/kitty
```
PS: I suggest to use `appman` for this kind of testing, or `am -i --user`, it is safer to do this kind of test rootless.

When you have done, feel free to open a pull request, for your first contribution.

**Comment by ivan-hc** [comment]
After this, you should have a clearer understanding of how the installation scripts work.

I also suggest you to check out the related guide https://github.com/ivan-hc/AM/blob/main/docs/guides-and-tutorials/template.md , so you don't need me to create these scripts anymore.

**Comment by Twig6943** [comment]
@ivan-hc I now provide an AppImage builds for x86_64 architecture
https://github.com/Twig6943/kitty-appimage

Here's the script made with "am -t kitty" (Pressed 0)
[am-scripts.tar.gz](https://github.com/user-attachments/files/17715760/am-scripts.tar.gz)

**Comment by ivan-hc** [comment]
good, have you proposed your work to the upstream developer?

**Comment by Twig6943** [comment]
@ivan-hc nope I haven't cuz https://github.com/kovidgoyal/kitty/issues/438

**Comment by ivan-hc** [comment]
A lot has happened since 2018. I suggest you contact the developer again, show him what you worked on and convince him.

The difference between the person who opened that issue and you is that you have worked and successfully built a package. You already have some extra knowledge in creating AppImages. So I suggest you "spread" it. You are the expert now. Trust me.

**Comment by Twig6943** [comment]
@ivan-hc they still think the same way

**Comment by ivan-hc** [comment]
but you didn't tell him that you created it and that you have a script to create it

**Comment by Twig6943** [comment]
I told him to check this issue first

**Comment by tsuri21** [comment]
Regardless of the appimage topic, the name of the package is currently incorrect. The install script does not deliver the kitty terminal, but rather kitten. This is misleading and should either be renamed or the installation script should be changed so that the kitty binary is actually installed and not the kitten binary.

**Comment by ivan-hc** [comment]
Pull requests exist for this.

**Comment by ivan-hc** [comment]
> Pull requests exist for this.

I mean, you're asking me to add applications I don't know and will never use. The request was presented to me as `kitty`, and I was also provided with the contents of the .desktop file with references to `kitty`.

That said, did you have the script available in this database? Do you have a GitHub account? Then it won't cost you anything to fork this repository, make your changes, and submit a pull request. In fact, you'd even appear as a contributor to this project.

Personally, I don't care whether it's called `kitty`, `kitten`, or whatever. I'd be more interested in seeing you active and improving your knowledge as you try to add applications to this database.

Or at the very least, start building your own database https://github.com/ivan-hc/am-extras , so you don't have to ask me anything. We'll all save time: you don't have to wait for me to add the apps you want, and I don't have to waste time with your second thoughts.

That's all.

**Comment by tsuri21** [comment]
My intention probably didn’t come across the way I meant it, and my first reply was a bit brief since I wasn’t familiar with the process for adding new apps. From a maintainer’s perspective, your reply is absolutely understandable.
I’ll read up on it in more detail and give it a try with a pull request. Thanks for the tip, and sorry if it came across the wrong way before.

**Comment by ivan-hc** [comment]
@tsuri21 Don't apologize, you did well to report the problem
