### ISSUE TITLE
Flatpak [& Snap] your project :)

### ISSUE THREAD

**Issue by hotlittlewhitedog** [ivan-hc/AM#1052]
It's a suggestion to be more visible.   

In fact, AppImage users need a front-end, a façade (=vitrine).  
All distributions and communities have a package manager in CLI and a front-end (Gnome, KDE, Debian, Ubuntu of course). Maybe it's also an idea to regroup all AppImage hub/website together, even some are not OK as the war in Reddit, pfff! 

# In Flathub 
there are already these projects and specially the first one. 
The app is installed a lot everyday.   
(maybe contact this guy) ;)

<img width="924" alt="Screenshot 2024-10-29 at 18 01 38" src="https://github.com/user-attachments/assets/09fae92a-e045-4c12-b176-4c118ee57d1c">

  
This can be the first step.  
If after you want to create a simple front-end in Python/Ncurses to run in Terminal and be really quick (and execute your external bash scripts), it should be not so difficult. A Midnight Commander look!

# On Snapcraft.io 
there are more apps: 

<img width="808" alt="Screenshot 2024-10-29 at 18 08 41" src="https://github.com/user-attachments/assets/1205fd6e-c56e-41d8-8aed-ea51c73866aa">

**Comment by Twig6943** [comment]
The pkg manager is CLI only. (for now) Ivan might make a GUI later and then submit that to flathub/snap store tho

**Comment by ivan-hc** [comment]
Sorry, I have no knowledge in GUI programming and Flatpak does not support CLIs, also AppImagePool is a frontend of appimagehub.com, so it uses different APIs (Pling) than those of github.com, it would require a re-work.

I've also been against Flatpak on several occasions, to the point of competing with it (typing "AM"/"AppMan"), and I haven't changed my mind since.

Regarding Snape and Ubuntu, I recently released a build that checks AppArmor permissions, prompting the user to disable it... so I don't think Canonical would appreciate that.

Anyway...

> It's a suggestion to be more visible.

thank you for your thoughts, but I think the easiest way to make "AM" known to the public is to present it, through word of mouth, on social media, blogs, forums and specialist sites. To date I only have one DistroTube review on YouTube (badly done, since the video used a one-year-old version full of bugs) and a small mention in a long video on AppImage in an Italian YouTube channel.

I am also mentioned in some posts on Reddit and my releases are regularly published on linuxcompatible.org, but I have not seen a site or blog that talks about my project.

A review would be useful at least. I personally am not the type to spam sites... and if I did something similar (spam) I stopped immediately, because I felt ridiculous. Those who love what I do should talk about it everywhere, informing people. That's how it works in open source.

Again, thanks for this post.
