### ISSUE TITLE
Playit

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#1053]
![image](https://github.com/user-attachments/assets/93115cd9-3a30-4a50-88dc-ac9fd419fc58)

1. name: playit
(CLI application)
2. main site: https://github.com/playit-cloud/playit-agent
3. download page: https://github.com/playit-cloud/playit-agent/releases
4. description of the application: The playit program.
5. URL to the application icon: https://styles.redditmedia.com/t5_4p2peg/styles/communityIcon_03fcv8nuag4b1.png
6. the .desktop* file (choose whether to add a URL, to paste the content of the file, to drag a text file into your comment or to provide only the following 3 desktop entries, `Name=`, `Exec=` and `Categories=`

[Desktop Entry]
Type=Application
Name=Playit
Comment=Tunneling application
Exec=playit
Icon=playit.png
Terminal=true
Categories=Internet;Games;
Keywords=Tunnel;Port;
StartupNotify=false

5. description of the application: The playit program.
6. URL to the application icon: https://styles.redditmedia.com/t5_4p2peg/styles/communityIcon_03fcv8nuag4b1.png
7. the .desktop* file (choose whether to add a URL, to paste the content of the file, to drag a text file into your comment or to provide only the following 3 desktop entries, `Name=`, `Exec=` and `Categories=`

[Desktop Entry]
Type=Application
Name=Playit
Comment=Tunneling application
Exec=playit
Icon=playit.png
Terminal=true
Categories=Internet;Games;
Keywords=Tunnel;Port;
StartupNotify=false
ss=harmonoid

**Comment by ivan-hc** [comment]
I personally only upload apps for x86_64 architectures, but only because they are the only ones I can test on a physical machine.

However, anyone who has that architecture and wants to upload a script can download what I uploaded and modify it, then add it via PR.

AM is based on SHELL, so it can run anywhere. But I don't have the machines or the time to dedicate to the other architectures.
