### ISSUE TITLE
Is it possible to have more than 2 installation directories?

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#1098]
am -i firefox installs firefox to
/opt/firefox/

am -i --user firefox installs firefox to 
/mnt/8073657c-f7f3-4c5d-bb7e-48e43b904ec0/PortablePKGS/firefox

Is it possible to have more install directories? (AFAIK its not)

Proposed solution:
Allow the user to put more than 1 location to;
/home/twig/.config/appman/appman-config

For example 
![image](https://github.com/user-attachments/assets/04ea1103-78f3-48b0-98b4-a961513818b8)

If the user has more than 1 installation in their config am should do the following 
[twig@twig-tobefilledbyoem ~]$ am -i --user firefox
You have multiple installations in your appman config. Please pick the one to install the pkg/s
1 /mnt/8073657c-f7f3-4c5d-bb7e-48e43b904ec0/PortablePKGS/
2 /run/media/twig/unstable/AMPKGS/
User Input: 1

Result: Firefox gets installed to /mnt/8073657c-f7f3-4c5d-bb7e-48e43b904ec0/PortablePKGS/

**Comment by ivan-hc** [comment]
AppMan, or AM in user mode, requires a single configuration file in ~/.config/appman.

The general point of installing programs this way is to use them via the command line or by adding a launcher to the application menu.

**Having more than one installation is counterproductive**. Therefore, it is advisable to have only one installation path.

-------------------------

Alternatively, you should write yourself a script that allows you to start an instance of $HOME for multiple different AppMan installations. For example:
```
HOME=/another/path
PATH=$PATH:/another/path/.local/bin
```
I don't know exactly how to do this. You should google it. I think using containers for this might be a solution.

**Comment by Twig6943** [comment]
Im looking for a built in solution tho (flatpak has this) (if ur not down to implement this (which you seem to be) please help me w the script method)

**Comment by ivan-hc** [comment]
There are several things to consider, for example the XDG paths for launchers (~/.local/share/applications) and for links/symlinks/binaries in $PATH (~/.local/bin).

There is one for each instance of $HOME. Creating an alternate path in AppMan with the same filenames would overwrite launchers and $PATH items, making them unusable if you switch back to the old path.

And I told you, this is not something I normally know how to do. I only use a separate $HOME instance when I need to experiment with an AppImage I'm working on, to avoid "infecting" my real $HOME.

But setting up a different $HOME with all the variables it needs is something I absolutely don't know how to do. Maybe @Samueru-sama knows more about this... but I think it would be necessary to have a separate tool, that creates sub-instances of $HOME in $HOME, with different usernames maybe... maybe containers can make up for the use of a dual-boot or multiple accounts.

Actually, I don't know anything about that.

If you can find something that can solve your problem and is implementable in AppMan, I'll try to accommodate you. But for now, I have no idea how to do it.

**Comment by Samueru-sama** [comment]
How does flatpak handle the exports of the `.desktop` when you have the same app installed at two different locations?

**Comment by Twig6943** [comment]
i think its like
flatpak run --install=placeholder com.usebottles.bottles

**Comment by Samueru-sama** [comment]
> i think its like flatpak run --install=placeholder com.usebottles.bottles

No what I mean what happens when you install the same app at two different location with flatpak.

How do you choose which one to run after that?

**Comment by Twig6943** [comment]
@Samueru-sama https://docs.flatpak.org/en/latest/tips-and-tricks.html#adding-a-custom-installation

**Comment by Samueru-sama** [comment]
> @Samueru-sama https://docs.flatpak.org/en/latest/tips-and-tricks.html#adding-a-custom-installation

Ok this says that in order to install at a extra location the `--installation` flag has to be passed: `flatpak --installation=extra install flathub org.inkscape.Inkscape`

I guess something similar can be done with appman, where `--installation` flag would change the `APPSPATH` variable. 

The way to run that app is terrible though, the example flatpak gives is `flatpak --installation=extra run org.inkscape.Inkscape` seems like it is not possible to set the extra location as default to avoid passing the flag. 

**And no mention on how the `.desktop` files are handled for repeated apps is made**

Also unlike flatpak, am/appman actually adds the apps to `PATH`, so in other words a symlink to either `/usr/local/bin` or `$XDG_BIN_HOME` is made when installing an application, how do we handle this for multiple apps?

**Comment by Twig6943** [comment]
I'll check out flatpaks .desktop approach soon. Hopefully we can implement something similiar to AM.

**Comment by ivan-hc** [comment]
> In all this, all programs can run without a launcher and without a link in $PATH, they are all portable, which means you just copy the whole folder and manually run the binary inside. To update them, almost all have a script called AM-updater, just run it manually.

Correction, AM-updaters follow well defined paths where to move apps... **so no, you can't copy the directory and run AM-updater anywhere.**

**Comment by Twig6943** [comment]
> @Twig6943 as @Samueru-sama said
> 
> > Also unlike flatpak, am/appman actually adds the apps to `PATH`, so in other words a symlink to either `/usr/local/bin` or `$XDG_BIN_HOME` is made when installing an application, how do we handle this for extra installs?
> 
> to make you understand, if you install the same app twice locally, during the installation...
> 
> 1. the existing .desktop file will be overwritten with the new one, which is not a problem for the new app... but it is for the old one, as the icon paths are different;
> 2. the link in `$HOME/.local/bin` will not be overwritten, you will have an extractor with `ln -s`, so from the terminal you will always call the old app
> 
> In the meantime I have already uploaded a prototype in the "dev" branch, just to give you an idea, I created two new options `--add` to add a new profile, and `--profile-manager` to select one
> 
> I attach here the APP-MANAGER script as "appman.txt" (remove .txt if you want to use it as a normal AppMan).
> 
> [appman.txt](https://github.com/user-attachments/files/17770128/appman.txt)
> 
> Let me show you how it works (but keep your feet on the ground, I haven't decided yet whether to approve this request... I just wanted to show you that it can be done)
> 
>  simplescreenrecorder-2024-11-15_05.54.19.mkv.mp4 
> ...all great, but here's what happens with two identical apps installed
> 
>  simplescreenrecorder-2024-11-15_06.21.39.mkv.mp4 
> ...its a mess!
> 
> That said, I don't know to what extent you should use two apps installed like this.
> 
> I personally have different approaches:
> 
> * if you want to use multiple versions of the same program, play with `-b` and `-o`, I wrote a guide about it, and it works for both AppImages and other formats, like Firefox, which you mentioned https://github.com/ivan-hc/AM/blob/main/docs/guides-and-tutorials/backup-and-overwrite.md#how-to-use-multiple-versions-of-the-same-application
> * if you want to use portable versions from other locations, you can only do it with AppImages, and AM has a `--launcher` option, also documented, and that works like AppImageLauncher and Gear Lever, with the only exception that the apps are not updated https://github.com/ivan-hc/AM/blob/main/docs/guides-and-tutorials/launcher.md
> 
> In all this, all programs can run without a launcher and without a link in $PATH, they are all portable, which means you just copy the whole folder and manually run the binary inside. To update them, almost all have a script called AM-updater, just run it manually. Firefox does not have it, because it updates itself (I love Firefox). But you will have to give up integrating them into the menu and $PATH to use them wherever you want. That's all.

Ayooo --profile-manager lookin 🔥🔥🔥🔥I'll try to give it a shot soon.
Also I think this would a great addition to the pkg manager (just like the introduction of the --user flag in 9.0 )
Most pkg managers on linux dont have a built-in installation feature (symlinks can be used with those but yeah still not a built-in solution) 
Apt:No
Rpm:No
Pacman:No
YaY/Paru:No
Nix:No
Snaps:No (only supports 1 insallation. Its location can be changed but yeah just 1)
Zap: Sorta no (not sure) (the project itself is dead as hell/not as feature complete as AM/Appman)
Flatpak:Yes ✅ 
Am/Appman:Supports 2 installation folders as of rn (1 with am 1 with Appman/--user mode) (Seems like this might change to a ✅  like flatpak depending on your choice)

**Comment by ivan-hc** [comment]
> Ayooo --profile-manager lookin 🔥🔥🔥🔥 [...] Most pkg managers on linux dont have a built-in installation feature
(symlinks can be used with those but yeah still not a built-in solution)
> - Apt:No
> - Rpm:No 
> - Pacman:No 
> - YaY/Paru:No 
> - Nix:No 
> - Snaps:No (only supports 1 insallation. Its location can be changed but yeah just 1) 
> - Zap: Sorta no (not sure) (the project itself is dead as hell/not as feature complete as AM/Appman) 
> - Flatpak:Yes ✅ 
> - Am/Appman:Supports 2 installation folders as of rn (1 with am 1 with Appman/--user mode) (Seems like this might change to a ✅ like flatpak depending on your choice)

My question is "who would use something like this?"

Also, knowing how they handle links, Flatpak doesn't have any real links in $PATH, it uses something that looks like an internet address and `flatpak run org.capocchia.appname` to call it, with a flag to go with it.

I have a half-idea of ​​how to introduce something like that... but it would completely break the $PATH management of programs, which would compromise the functioning of AppMan/AM on the user side itself.

**Comment by Twig6943** [comment]
"My question is "who would use something like this?"
I and some friends of mine use this a lot and besides its kinda about having the ability to rather than using it. This also exists on windows. (installers ask user where to install (I hate installers because they sometimes bundle ads and they require a bit of an effort to find but that's besides the point ) )

**Comment by ivan-hc** [comment]
Imagine to have something like this in your `$HOME/.bashrc`, but repeated several times for many different directories
```
BINDIR="${XDG_BIN_HOME:-$HOME/.local/bin}"

if ! echo $PATH | grep "$BINDIR" >/dev/null 2>&1; then
	export PATH="$PATH:$BINDIR"
fi
```

**Comment by ivan-hc** [comment]
This is a complete remake of $PATH.

**Comment by ivan-hc** [comment]
![Istantanea_2024-11-15_14-20-54 png](https://github.com/user-attachments/assets/74ba6389-16fe-41f3-9989-0adbd04df3e4)

@Twig6943 It's not a good thing

**Comment by ivan-hc** [comment]
I have found this article that is quite interesting https://opensource.com/article/21/5/launch-flatpaks-linux-terminal

In particular

> There's one thing that makes Flatpak a little awkward in some cases, though, and that's its naming scheme. For instance, when I install Emacs as a Flatpak, it's registered on my system as org.gnu.emacs. This is done, apparently, for fear of clobbering the name of an existing system-level application—if I already have Emacs installed, then what's the differentiation between /usr/bin/emacs and the Flatpak installation of Emacs? For this reason, a Flatpak like Emacs gets installed to something like (get ready for it) this path:

>                  /var/lib/flatpak/app/org.gnu.emacs/current/active/export/bin/org.gnu.emacs

> It's not symlinked from /usr/bin or /opt, the location isn't added to the user's path, and launching a Flatpak requires an invocation like this:

                    $ flatpak run org.gnu.emacs

> That's a lot of typing compared to just entering emacs.

I started this research when I realized that programs in Flatpak format do not include CLI tools. And the reason, as I suspected... is exactly this.

**Comment by ivan-hc** [comment]
At this point, to make sure this feature works, here's what you need to do during installation:
1. disable the line starting with `ln -s` for symbolic links, so that you can't use them from the terminal at all;
2. replace the `Exec=$APP` reference in the .desktop file with the full path to the application.

Result? AM becomes Flatpak. And like it, it won't have any command line programs.

@Twig6943 so here you have to decide between excluding many portable apps that will be unusable, turning AM into Flatpak... or leaving everything as it is, so that (as you pointed out in the other comment) AM is more like APT and PacMan/YAY, which don't allow the use of different alternative paths.

Personally, I want to use the terminal, also because the programs provided are much more than the graphical ones, which are the heart of Flathub.

$PATH is an essential element for the programs managed by AM, which is not the case with Flatpak.

**Comment by Samueru-sama** [comment]
>There's one thing that makes Flatpak a little awkward in some cases, though, and that's its naming scheme. For instance, when I install Emacs as a Flatpak, it's registered on my system as org.gnu.emacs. This is done, apparently, for fear of clobbering the name of an existing system-level application—if I already have Emacs installed, then what's the differentiation between /usr/bin/emacs and the Flatpak installation of Emacs? For this reason, a Flatpak like Emacs gets installed to something like (get ready for it) this path:

This isn't the real reason flatpak has that problem, the reason given by the developers is this [one](https://github.com/flatpak/flatpak/issues/994#issuecomment-328154457).

Which makes no sense because flatpak could check if the binary that's about to be added to `exports/bin` matches any existing binary and issue a confirmation when installing, not to mention it could even list you in big letters something like **`org.random.random was installed as XYZ in PATH`** and also make sure `exports/bin` is last in PATH to prevent flatpaks from overwritting system binaries, 

Not even snap has this problem.

This is the same project that refuses to follow the [XDG Base dir specification](https://github.com/flatpak/flatpak/issues/46#issuecomment-243095802) it isn't surprising anyway.

**Comment by ivan-hc** [comment]
And since we want to follow and promote the XDG specifications, as good GNU/Linux users... we will opt for alternative ways to the one proposed by Flatpak.

I think I will keep the changes made in a separate branch. If you want to analyze them, here is the link

https://github.com/ivan-hc/AM/tree/appman-profile-manager

Better not beat around the bush. I'm closing this issue as "unplanned".

With my tests I've only shown that it's possible to replicate what Flatpak does, and I've demonstrated the drawbacks of this approach.

If Flatpak users are okay with having to write "papielli" (as we say in Naples), let them keep their long, complex and impractical commands.

We want to embrace all apps, with or without GUI. And this already puts us several steps ahead of Flatpak.

I'm taking this opportunity to free up the "dev" branch, so I can test and introduce better features. And I already have one in mind. Stay tuned.

**Comment by Twig6943** [comment]
> Result? AM becomes Flatpak. And like it, it won't have any command line programs

would it be possible to keep am as is and make AppMan take this flatpak approach (idk if ur against this. I'm sorry if you've stated that you are before I have adhd).

**Comment by Twig6943** [comment]
am -i inkscape
inkscape can be launched with "inkscape"
binary location: /opt/inkscape/inkscape

appman -i inkscape
inkscape can be launched from the terminal with "inkscape-appman"

binary location: /randomfolder/custominstallation/inkscape/inkscape > appman symlinks as "inkscape-appman" and the user can launch it with "inkscape-appman" (I mean this would be appman only + for launching from CLI all you gotta do would be type app_name-a and then press tab to auto complete to app_name-appman you can even make the first part auto complete with tab if the user has the same app installed as a system pkg or from am (not appman)

**Comment by Twig6943** [comment]
this is better than having to type "flatpak run org.inkscape.Inkscape"

**Comment by Twig6943** [comment]
If the user installs the same application twice to different drives appman should add a number to the symlink

Day:Monday
user runs "appman -i inkscape"
appman installs and creates the symlink "inkscape-appman"

Day:Tuesday
user runs "appman -i inkscape" (but instead of his default appman profile he now has his second profile selected)
appman

**Comment by ivan-hc** [comment]
> would it be possible to keep am as is and make AppMan take this flatpak approach

tell this to all AppMan users that rely on the original approach.

Anyway, I provided a URL to a branch with the changes in my last comment https://github.com/ivan-hc/AM/issues/1098#issuecomment-2480413522 , you can fork it and create your.... "AMPak" CLI, if you need it. But you need to remove all non-gui apps for this... and also the Toolpacks support, since they are almost all programs you run from command line.

**Comment by Twig6943** [comment]
>tell this to all AppMan users that rely on the original approach -_-

I mean I'm pretty sure there's like 1-2 guys using CLI stuff with AppMan but yeah you're the boss after all and I dont have the time nor knowledge to maintain my own fork so yeah there goes that

**Comment by ivan-hc** [comment]
> I mean I'm pretty sure there's like 1-2 guys using CLI stuff with AppMan

believe me, there are many more... and maybe there are more than AM users

> but yeah you're the boss after all

I follow everyone's advice, I evaluate the feasibility, the pros and cons, and based on that, I create releases. In this sense, given all the features I've added in recent months, born precisely from requests from other users... I'm less "the boss" than you might imagine.

I've made some changes to the code, and all to please users who asked for additional features.

More than the boss, I'm an employee. In fact, I'm "the manager". And changing the code in the way you're asking me to do would please you, but it would disappoint many other people, who as I've already told you, are many more than those who decide to install applications at the system level.

AppMan is much more versatile, you can put it wherever you want and it will do the same things as AM, but locally, and without root permissions. Most people want to use things without root privileges. Today, what people are looking for is security. And a badly written `rm -Rf`, used with root privileges, can cause IRREVERSIBLE damage.

AppMan is more secure than AM. My responsibility here is to make sure that third party code does not cause problems.

----------------------

Last but not least, AM and AppMan users have the same user experience in two different approaches. If they decided to use these approaches, relying on what I created, it is because they know that I will not do anything to change their habits.

I am a former Ubuntu and GNOME user, like many users who started using Linux with that distro, 10-15 years ago, before exploring other paths, disappointed by the choices of the Canonical or GNOME team. I do not want to give my users the same disappointment.

That's all.
