### ISSUE TITLE
Cheat breaker [request I dont have the time to learn stuff rn]

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#1119]
.

**Comment by ivan-hc** [comment]
If you don't have time, write an issue, don't try to do a Pull Request by modifying two files.

BTW, I uploaded the app you wanted right after I closed your Pull Request https://github.com/ivan-hc/AM/commit/859487ede6667ea0ca38fb0672150576a48b59ee , and for the record, it's called `cheatbreaker`, not `cheat-breaker`, in fact when I ran the verification with repology.org, it gave me an error. There is only one reference, and it's called `cheatbreaker, see https://repology.org/project/cheatbreaker/versions

**Comment by ivan-hc** [comment]
@Twig6943 if you have time enough, see this video, so you can understand a bit my workflow.

This is how I created the script you asked:

https://github.com/user-attachments/assets/a9f55432-ad5f-4384-aa22-e275cb3d3121

I have followed the instructions on screen, then when it asked me to add a command to detect the download URL, I had two options:
1. the easier one is to add the script directly, because it is linear... it should be always OK, but in the future the developer can change de page, this is what I can add for ease of life
```
https://r2.cheatbreaker.net/Launcher/master/Linux/amd64/CheatBreaker.AppImage
```
instead I prefered to use a command, because also if the URL changes in the future, a refenece can be always detected. See below.

2. My approach was this:
- `curl -Ls https://cheatbreaker.net/download` to read the page, you can try this command on any site
- `tr '">< ' '\n'` means that I'm using the `tr` command to replace all references of `"`, `>`, `<` and ` ` (spaces) with a new line, in SHELL it is `\n`, this is a step that works almost every time, on almost all sites (not all) and this is the best way to divide the URL from the rest of the HTML page
- last command `grep -i "^http.*amd64.*appimage$"`, this uses `grep` to search all lowercased/uppercased references (`-i`) of lines starting with "http" (`^http`) and ending for "appimage" (`appimage$`, the final dollar is the end of the line) and in the middle there must be a "amd64" ( `amd64`). You need to separate them with a `.*`
- in extra, as final command, also if I have not added it, you can add `head -1` or `tail -1` in case the page have more than one URL and you need the one listed on top (`head -1`) or down (`tail -1`)

All command abow must be separated with a `|`

This is the complete command I used
```
curl -Ls https://cheatbreaker.net/download | tr '">< ' '\n' | grep -i "^http.*amd64.*appimage$"
```
if there where many URLS and I needed the one on top, I could change it like this
```
curl -Ls https://cheatbreaker.net/download | tr '">< ' '\n' | grep -i "^http.*amd64.*appimage$" | head -1
```
if down instead it was
```
curl -Ls https://cheatbreaker.net/download | tr '">< ' '\n' | grep -i "^http.*amd64.*appimage$" | tail -1
```

I gave you a bit lesson of SHELL usage. I hope you treasure it.

**Comment by ivan-hc** [comment]
@Twig6943 if you start practicing now on web pages with the commands I suggested, you will have fun.... much more than Minecraft! The Internet will no longer have any secrets for you. You will be able to intercept the most hidden objects from web pages, simply by using 4 SHELL commands, and the web is full of guides.

If one day you decide to get serious about submitting scripts via Pull Request and you have doubts about the commands to use... don't hesitate to ask me how to do it. I will be your [stackoverflow](https://stackoverflow.com/)
