### ISSUE TITLE
[Genymotion] I'm so sorry for messing up

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#1125]
Ok soo the genymotion pkg on the db is an installer just like davinci resolve (I thought you've used genymotion before) and its supposed to install to a directory. 

You can specify this with the -d flag & also bypass the "Are you sure you want to install genymotion to $directory Y/N?" by using the -y flag

so am -i genymotion should 
wget/curl the installer
chmod a+x the installer
./genymotion.bin -d /opt -y

(could use $directory if directory=/opt I don't really know how AM works)

for am -i --user
 ./genymotion.bin -d $directory -y

directory=whatever thats inside /home/$USER/.config/appman/appman-config

and then the desktop file should have the Exec=$directory/genymotion

(Again really sorry for the whole mess)

**Comment by Twig6943** [comment]
https://github.com/ivan-hc/AM/issues/1098
or for --user whatever current profile's directory is

e.g.

User has 2 profiles
Profile1=/home/twig/weirdfolder1
Profile2=/home/twig/weirdfolder2
>User selects profile:1 

AM/Appman sets the $directory to /home/twig/weirdfolder1

User runs am -i --user genymotion 
AM/Appman runs: ./genymotion.bin -d $directory -y

Result: Genymotion gets installed to /home/twig/weirdfolder1/genymotion

**Comment by ivan-hc** [comment]
> I thought you've used genymotion before

I don't know all these programs that you propose to me.

I can't do anything other than create the script.

If you encounter problems with these programs, read the scripts, modify them, test them... I have specific guides.

You know how they work!

I don't care about knowing how they work!

Study the scripts!

Test them on your system!

If they work as you say, submit a pull request!

I have other responsibilities, I can't keep up with every program you propose to me!

I have dictated some guidelines, and the most important is "read the documentation". And I didn't write it to waste time, but because I hoped that interested users would contribute!

You use these apps. I don't know what they do. I don't want to know! You have to know what they do and how they should work! I'm not in your head! And I will never do things exactly as you would like!

So, roll up your sleeves, study and commit to solving these problems too.

Contact me only if you have any questions, i.e. if you don't understand how some command works. I told you I would teach you how to use SHELL, not that I would give you "homework". This is homework! Start learning something too!

I started this project 4 years ago, starting from zero scripting knowledge, and to prove that anyone can do it!

Look at @Samueru-sama , until 6 months ago he didn't know how to build AppImage packages, now he contributes to many projects and has surpassed me in skill!

Look at @Sush-ruta , he installed unlisted applications using the `-e` option, and from there he learned how to make pull requests, and in a month he became my third contributor for code added. And we are 26 contributors, in 3 years that this project exists!

And we all have our workloads. It's time you learned how to do something too.

I've been too helpful until now, I even helped you build AppImage packages. I'll show you the videos on how to do things. I spend time teaching you how to do things on your own! It's time for you to prove to me that I haven't wasted your time.
