### ISSUE TITLE
Error when launching a new terminal

### ISSUE THREAD

**Issue by GeoBoi254** [ivan-hc/AM#1127]
Launching a new terminal session gives me an error:
```
compdef: unknown command or service: disable&default_query_exec_mode=simple_protocol..toolpack$'
'quotes-escaper.toolpack$'
'r2agent.toolpack$'
'r2pm.toolpack$'
'r2r.toolpack$'
...
compdef: invalid argument: appman
```

Seems to be a line from my `~/.local/share/AM/list`:
`5432/certwatch?sslmode=disable&default_query_exec_mode=simple_protocol..toolpack`
Removing this line stops the error from occuring.

I can still use appman normally with this error.

**Comment by Samueru-sama** [comment]
Ivan recently added support for the [toolpacks repo](https://github.com/Azathothas/Toolpacks), which contains an insane amount of static binaries.

Your issue is related to that, but I have no idea what's wrong lol

**Comment by ivan-hc** [comment]
> Edit: Looks like a network error somehow made it into the apps list?

![Senza titolo](https://github.com/user-attachments/assets/60d29fbf-fa73-4736-9a8e-b5caf9ef7123)

**Comment by Samueru-sama** [comment]
Oh shit, I was able to replicate the issue, It prevents my entire `.zshrc` from loading wtf.

**Comment by ivan-hc** [comment]
@GeoBoi254 are you using zsh?

**Comment by GeoBoi254** [comment]
> @GeoBoi254 are you using zsh?

yes

**Comment by ivan-hc** [comment]
The list was compiled with a line that should not be there, including `?`, that may cause issues in ZSH

If you update now, just `am -s` and you should get AM 9.1.1-4

**Comment by Samueru-sama** [comment]
Just to explain the issue, zsh is well known for having this issue due to its extended globing, [like this](https://forum.endeavouros.com/t/tip-better-url-pasting-in-zsh/6962).

am adds all the available apps to the list file, that file is read by the bash completion which is also used by zsh since zsh can also work with bash completion. 

Well turns out an entry with a `?` slip thru and it caused compdef to explode.

I originally thought it was an issue on our end with us not discarding errors properly, but turns out it wasn't that 👀 anyways Ivan fixed it by making sure to remove aything with such character from the list, it is possible in the future some other character also has to be removed.

**Comment by ivan-hc** [comment]
I :heart: BASH BTW
