### ISSUE TITLE
SFP

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#1163]
(Please make AM grab the self-contained version e.g SFP_UI-linux-x64-SelfContained.tar.gz)
1. name : sfp
2. main site : https://github.com/PhantomGamers/SFP
3. download page: https://github.com/PhantomGamers/SFP/releases
4. description of the application:  A utility designed to allow you to apply skins to the modern Steam client 
5. URL to the application icon: https://raw.githubusercontent.com/PhantomGamers/SFP/refs/heads/main/SFP_UI/Assets/SFP-logo.ico 
6. the .desktop file:

[Desktop Entry]
Type=Application
Name=SFP
Comment=A utility designed to allow you to apply skins to the modern Steam client
Icon=SFP-logo.ico 
Exec=SFP_UI
Categories=Utility;

**Comment by Twig6943** [comment]
Aye @ivan-hc sorry to disturb but this [PR](https://github.com/PhantomGamers/SFP/pull/210) has been merged. Could you make the icon .svg instead of the .svg? Thanks in advance

**Comment by Twig6943** [comment]
Here's the link https://raw.githubusercontent.com/PhantomGamers/SFP/25a33fd6b5febd1cdb17538e71cc68d31c8d3865/SFP_UI/RawAssets/SFP-logo.svg

**Comment by ivan-hc** [comment]
I already edited the icon and published n my catalogue.

When the icon is not a valif one, I do so.

This is the content of the script I published
```
# ICON
mkdir -p icons
wget https://portable-linux-apps.github.io/icons/sfp.png -O ./icons/"$APP" 2> /dev/null
```

This happen when creating a script for an archive and you leave the blank when `am -t` asks for the url  to the icon

**Comment by Samueru-sama** [comment]
Note that svg support on the XDG Icon spec is optional and we should try to use png instead. I'm assuming you are asking for svg because the default png is too small.

**Comment by Samueru-sama** [comment]
> Na SVGs are better for logos (infinitely scaleable)

I know that, but once again [support for svg is optional](https://specifications.freedesktop.org/icon-theme-spec/latest/).

The draft of the[ appimage spec](https://github.com/AppImage/AppImageSpec/blob/master/draft.md) also mentions that `.DirIcon` **should** be a 256x256 png.

svg rendering requires separate libraries, gtk apps use gdk-pixbuf while qt apps use the iconengines plugins, and these sometime break, a lot for some reason lol

I actually have an open issue at go-appimage because it crashes when `.DirIcon` is an svg.

**Comment by Twig6943** [comment]
Noted, might change if they end up packaging as an appimage
