### ISSUE TITLE
Extending --launcher functionalities

### ISSUE THREAD

**Issue by bju9119** [ivan-hc/AM#1171]
# Is your feature request related to a problem? Please describe.
If we use --launcher we can technically 'install' the app but it needs to be updated manually. The problem is **there is no native command to remove these --launcher installed apps including its .desktop entry and others within appman** and also **these apps cannot be listed in appman**

# Describe the solution you'd like
A logging system of apps getting installed using --launcher from which '**appman -f --launcher**' will show apps which are installed in the system. In the log apps will get recognized using their symbolic name while removing them, as example: '**appman --launcher-remove SYMBOLIC-NAME**' which removes everything created using --launcher for that associated app.

# Describe alternatives you've considered
None

This is my first time opening an issue, correct me anyway possible. Thank you.

**Comment by Samueru-sama** [comment]
I think we can add something that updates appimages with launcher that all it does is check the appimage with `appimageupdatetool` to update it.

But be aware not all appimages have update information embedded, so this won't work with all still. 

Also I think you can remove the desktop entry by first manually deleting the AppImage and then running `am -c` iirc, maybe this should be improved.

**Comment by ivan-hc** [comment]
As @Samueru-sama said, exists `am -c` that takes care of dead .desktop files, leaving them if the AppImage is on an unmounted media, because someone may not be sure if it is worth to remove it...

![Istantanea_2024-11-30_17-33-36](https://github.com/user-attachments/assets/1bcc39d5-9d97-4967-9537-2cb99b0fca68)

...and stops warning you when the partition is mounted

![Istantanea_2024-11-30_17-34-07](https://github.com/user-attachments/assets/37117191-8728-4f6b-83aa-992d9124585c)

------------------------------

Also, if you have another AppImage and you want to overwrite the other one, you can just overwrite it using the same command.

Of course, there should be something to fix the symlink/script in $PATH. This is true.

------------------------------

Updates... well, I created this database to allow updates for all AppImages listed.

To do so, all AppImages and (almost) all portable programs have an AM-updater script with the right instructions to update every package, regardless if it contains delta updates info or not.

But to adding `appimageupdatetool` support to every "free-to-move" AppImage scattered on the system is a risk.

Tools like `appimageupdatetool` and `appimbaced`/`appimagelauncherd` (the latter two are system daemons not included in AM, because they prevent any other AppImage manager or any terminal emulator to run and handle AppImages... so they are pure garbage) can take care of scattered AppImages around the system... according to their update info inside them... of for what I know, only the 10% of AppImages have this feature... https://appimage.github.io (for how much is worst as a catalogue) is a site that validate all added appimages, by showing also if they are/were vuilt with an inbuilt update system. See the last column in their [Apps page](https://appimage.github.io/apps/) (many are flagged with `no valid OpenPGP data found`).

There is another tool that does the same, a Flatpak, named GearLever... you can add a URL in the settings (manually, of course) if no update info are into the AppImage. However, it is limited only to the programs hosted on github and others that have just the update info inside.

That said, AM is born to list all AppImages, by giving them an update system, using the AM-updater script.

We have another option, not just `--launcher` that its better and more similar to `-i` (the one to install the programs), **the option `-e` or `extra`**.

It works like Zap or Bread (other two great package managers for AppImages, in my opinion), and like them, it is limited to github. I wrote a guide on its usage https://github.com/ivan-hc/AM/blob/main/docs/guides-and-tutorials/extra.md , option `-e` is one that I'm proud of, to be onest.

And just yesterday I sent a private message to @Samueru-sama talking about improving that option, by estending it to other AppImages, out of github.com. It is funny that right now you opened an issue about this.

However, this kind of support is still a dream. To handle portable programs like this would be a nightmare. And to use `-e` for AppImages out of github.com would be even difficult for a newbie, since in most cases it is needed a SHELL command to find the correct URL or the version somewhere, in the World Wild Web (yes, **Wild**, not Wide, I wrote correctly). It is a nightmare for us, that are uploading these scripts... and it would be a nightmare for anyone.

This is why the best practice, here in AM, is to submit a request, and we will try to take care of it somehow.

About `--launcher`, yes, it can be still improved... I consider it a niche option though. I'll do my best to make it grow... but I don't promise miracles, let's be clear.

**Comment by Samueru-sama** [comment]
>But to adding appimageupdatetool support to every "free-to-move" AppImage scattered on the system is a risk.

I don't see a problem with running `appimageupdatetool` on `scattered` AppImages, if you pass the `-Or` flag it will replace the AppImage in place with the original name.

`appimaged/appimagelauncherd` are totally different things and do give problems.

The only problem I see is how AM would need to do it lol, I guess read all the `Exec=` key of all the `.desktop` of the scattered appimages and run appimageupdatetool on that path.

**Comment by ivan-hc** [comment]
I'll start to create a `-f --launcher` command for now, that will include the `_clean_launchers` function to automatically remove the unneeded launchers.

Just opened the scripts.

**Comment by ivan-hc** [comment]
WIP

```
_files_launcher() {
	_clean_launchers 2>/dev/null 1>/dev/null
	[ ! -d "$DATADIR"/applications/AppImages ] && echo "No launcher found" && exit 0
	[ -d "$DATADIR"/applications/AppImages ] && [ -z "$( ls -A "$DATADIR"/applications/AppImages )" ] && echo "No launcher found" && exit 0
	echo "- APPIMAGE | PATH "
	echo "- -------- | ----"
	for var in "$DATADIR"/applications/AppImages/*.desktop; do
		# full path to appimage
		appimage_full_path=$(grep "Exec=" 0<"$var" 2>/dev/null | head -1 | cut -c 6- | sed 's/"//g; s/\s.*$//')
		# name of the appimage
		appimagename=$(basename -- "$(echo "$appimage_full_path" | tr '[:upper:]' '[:lower:]')")
		appimage_path=$(echo "$appimage_full_path" | sed -E 's|/[^/]+$|/|')
		# removable mount point where the appimage may be stored
		echo "- $appimagename | $appimage_path"
	done
}
```

![Istantanea_2024-11-30_18-52-50](https://github.com/user-attachments/assets/6cad9d2a-5e08-4449-aa5c-346e5f1d50d4)

**Comment by ivan-hc** [comment]
```
_files_launcher_message() {
	echo "-	APPIMAGE | PATH "
	echo "- -------- | ----"
	for var in "$DATADIR"/applications/AppImages/*.desktop; do
		appimage_full_path=$(grep "Exec=" 0<"$var" 2>/dev/null | head -1 | cut -c 6- | sed 's/"//g; s/\s.*$//')
		appimagename=$(basename -- "$(echo "$appimage_full_path" | tr '[:upper:]' '[:lower:]')")
		appimage_path=$(echo "$appimage_full_path" | sed -E 's|/[^/]+$|/|')
		echo "- $appimagename | $appimage_path"
	done
}

_files_missing_launcher_message() {
	MISSING_LAUNCHERS_MSG=" No launcher found, use option \"${Green}--launcher\033[0m\" to create them."
	printf "%b\n%b\n%b\n" "$DIVIDING_LINE" "$MISSING_LAUNCHERS_MSG" "$DIVIDING_LINE"
}

_files_launcher() {
	_clean_launchers 2>/dev/null 1>/dev/null
	MISSING_LAUNCHERS_MSG="No launcher found, use option \"--launcher\" to create them."
	[ ! -d "$DATADIR"/applications/AppImages ] && _files_missing_launcher_message && exit 0
	[ -d "$DATADIR"/applications/AppImages ] && [ -z "$( ls -A "$DATADIR"/applications/AppImages )" ] && _files_missing_launcher_message && exit 0
	FILES_LAUNCHERS_NUMBER=$(find "$DATADIR"/applications/AppImages -type f -name '.desktop' 2>/dev/null | uniq | wc -l)
	LAUNCHERS_MESSAGE="YOU HAVE INTEGRATED $FILES_LAUNCHERS_NUMBER APPIMAGES USING THE \"--launcher\" OPTION"
	echo ""
	echo "YOU HAVE INTEGRATED $FILES_LAUNCHERS_NUMBER APPIMAGES USING THE \"--launcher\" OPTION"
	echo ""
	_files_launcher_message | column -t
	echo ""
}
```

this is how it looks like

![Istantanea_2024-11-30_19-32-38](https://github.com/user-attachments/assets/9d508278-4904-40d4-9b5c-de6d1dcb1b41)

@bju9119 anything else?

**Comment by ivan-hc** [comment]
Obviously I have AppImages without extension... this is how it looks like if I rename and add another one

![Istantanea_2024-11-30_19-35-27](https://github.com/user-attachments/assets/6c49ab3f-0066-42c7-9bdd-727324f5f73c)

...and this is what happens if I move or raname the AppImage and I run the command again

https://github.com/user-attachments/assets/e65f4650-023a-4501-9aa6-74dfa349f372

**Comment by ivan-hc** [comment]
OK, just fixed number and "APPIMAGE"/"APPIMAGES" (depending if there are more than one)

btw, this is how it appear

![Istantanea_2024-11-30_19-51-11](https://github.com/user-attachments/assets/2ccd3b37-1bd7-4e13-9b6d-ecbb44791ea6)

**Comment by ivan-hc** [comment]
Suggestions?

**Comment by ivan-hc** [comment]
Why not to list them normally?

![Istantanea_2024-11-30_19-59-50](https://github.com/user-attachments/assets/46b82406-c6fc-4ad7-8520-a2417dde626f)

**Comment by ivan-hc** [comment]
Running `am -c` or `am -f` will not be different: obsolete launchers will be checked and removed anyway at start

@bju9119 is this enough or want to add something?

**Comment by Twig6943** [comment]
Pls appimageupdatetool support

**Comment by ivan-hc** [comment]
for now I did this
```
function _launcher_update() {
	_clean_launchers 2>/dev/null 1>/dev/null
	if ! command -v appimageupdatetool 1>/dev/null; then
		update_launchers_error_message=" 💀 ERROR! Missing command \"${RED}appimageupdatetool\033[0m\", install it and retry!"
		printf "%b\n%b\n%b\n" "$DIVIDING_LINE" "$update_launchers_error_message" "$DIVIDING_LINE"
		exit 0
	fi
}
```
I need to complete it

![Istantanea_2024-11-30_21-23-02](https://github.com/user-attachments/assets/240e2af2-8ac0-473f-a63a-f07d3a138156)

**Comment by ivan-hc** [comment]
@Samueru-sama 

```
function _launchers_not_found() {
	MISSING_LAUNCHERS_MSG=" No launcher found."
	printf "%b\n%b\n%b\n" "$DIVIDING_LINE" "$MISSING_LAUNCHERS_MSG" "$DIVIDING_LINE"
}

function _launcher_update() {
	_clean_launchers 2>/dev/null 1>/dev/null
	MISSING_LAUNCHERS_MSG="No launcher found, use option \"--launcher\" to create them."
	[ ! -d "$DATADIR"/applications/AppImages ] && _launchers_not_found && exit 0
	[ -d "$DATADIR"/applications/AppImages ] && [ -z "$( ls -A "$DATADIR"/applications/AppImages )" ] && _launchers_not_found && exit 0
	if ! command -v appimageupdatetool 1>/dev/null; then
		update_launchers_error_message=" 💀 ERROR! Missing command \"${RED}appimageupdatetool\033[0m\", install it and retry!"
		printf "%b\n%b\n%b\n" "$DIVIDING_LINE" "$update_launchers_error_message" "$DIVIDING_LINE"
		exit 0
	else
		echo "$DIVIDING_LINE"
		for var in "$DATADIR"/applications/AppImages/*.desktop; do
			appimage_full_path=$(grep "^Exec=" 0<"$var" 2>/dev/null | head -1 | cut -c 6- | sed 's/"//g; s/\s.*$//')
			appimagename=$(basename -- "$appimage_full_path")
			appimage_path=$(echo "$appimage_full_path" | sed -E 's|/[^/]+$|/|')
			appimage_updating_msg="◆ Trying to update $appimagename..."
			printf "%b\n\n" "$appimage_updating_msg"
			appimageupdatetool -Or "$appimage_full_path"
			echo "$DIVIDING_LINE"
		done
		exit 0
	fi
}
```

works!

https://github.com/user-attachments/assets/a7da5e77-6c6b-4d62-9ccf-b9b54d27217f

**Comment by ivan-hc** [comment]
I have finished here, updates can be managed using `am -u --launchers` or `am --launcher -u`

![Istantanea_2024-12-01_03-01-25](https://github.com/user-attachments/assets/49d08ecc-4ea8-4b59-9e10-102124771219)

Since usually those who choose this method to **integrate** (not "**install**", what `--launcher` does, but also AppImageLauncher and GearLever... is called "integration", because the files are free and scattered in the system, not fixed in one place as AM does with `-i`/`-ia`/`-e`) are those who want a specific version of a program. I know people who maintain multiple versions of the same program, and I don't think they would be willing to lose an old version that (for them) works better than the new one. So the update will happen via "flag", and separately from the full update.

**Comment by ivan-hc** [comment]
@bju9119 To recap, we made "bulk" AppImages updatable (via delta updates) and made them listable with the `-f` option.

If there's anything else you'd like to add, let me know.

**Comment by ivan-hc** [comment]
Hey folks... what of these two views is the best one?

![Istantanea_2024-12-01_06-31-49](https://github.com/user-attachments/assets/64cef9e4-f5dd-4377-9ab9-a2df0f198aaf)

**Comment by ivan-hc** [comment]
@bju9119 you can preview these changes by going to the "dev" or "Developer Mode" branch
```
am -i --devmode-enable
am -s
```
I haven't added any commands, but I've improved the existing ones. `--launcher` can also be used as a flag for `-u` and vice versa. You can't go wrong.

To exit developer mode, run
```
am -i --devmode-disable
```
but don't upgrade.

I'm waiting for the OK to merge these changes into the main branch.

**Comment by ivan-hc** [comment]
PS: as you can see from the messages, I started 13 hours ago... the bulk of the last few hours has been improving the interface, nothing major.

Among the most important changes, I improved the way to intercept and clean dead links in $HOME/.local/bin, now the cleaning is automatic every time you run `-f` and `-c`.

Also, creating launchers warns you if a command already exists, checks if it is in $HOME/.local/bin (it didn't do this before, I fixed it) and asks if you want to overwrite it.

Listing of AppImage files happens on the fly.

Updates? Only if you have `appimageupdatetool` installed and if you run `-u --launcher` or `--launcher -u` (remember, `-u` has the declinations `-U` and `update`, choose the one that is most convenient for you).

More than that, I don't know what to do.

**Comment by bju9119** [comment]
Looks good!!!!!! @ivan-hc. Merge it pls. Thank you so much

**Comment by ivan-hc** [comment]
Merged https://github.com/ivan-hc/AM/commit/f5a1cede4dbebea9b9a1b03d1699f53667db5f14
