### ISSUE TITLE
how to Install only AppImages and enable a sandbox with one click

### ISSUE THREAD

**Issue by candrapersada** [ivan-hc/AM#1173]
`am -ia {PROGRAM}`

**Comment by ivan-hc** [comment]
Sandboxes are not pre-set in AM. Each app has its own way of working, and the choice of accessible directories must be made by the user.

That's why we provide an interactive interface in `--sandbox`, so you can choose what directories can be accessible or not.

**Comment by candrapersada** [comment]
what i mean is `am -ias {PROGRAM}`

**Comment by ivan-hc** [comment]
The problem is that not all AppImages require the same scheme to be sandboxed.

In `--sandbox` all accesses are prevented by default, and this would be a problem for certain apps.

If the user knows what that application does, its the right of the user to choose what directories can be accessible. For example, `baobab-gtk3`, a disk analyzer, if you have a collection of songs and videos and you would like to track their growth on your disk, you can't with the default settings. That said, you need to allow accesso to Music and Videos using `--sandbox` manually.

**Comment by Samueru-sama** [comment]
`am -i {PROGRAM} && am --sandbox {PROGRAM}`

You could technically do this with multiple apps, the issue is that you still need to set what locations are going to be given access by the sandbox.

**Comment by candrapersada** [comment]
> You could technically do this with multiple apps, the issue is that you still need to set what locations are going to be given access by the sandbox.

`am -ias {PROGRAM}`

**Comment by ivan-hc** [comment]
@candrapersada done https://github.com/ivan-hc/AM/releases/tag/9.3
