### ISSUE TITLE
Shorter help message

### ISSUE THREAD

**Issue by zen0bit** [ivan-hc/AM#120]
My previous complain about less everywhere
was mainly about that extra long help message. That maybe belongs to manpage instead? I think help messages should be shortest as posible and every line without information is wasted space in my eyes. Just logo, author, license, version, homepage and usage + needed additional info.

I like your styling but first time i see linux cli app with help message like that.

Since most of my complains are just essential changes you already done pretty good work 🤯

Keep it up 👍

**Comment by zen0bit** [comment]
I am usually using termux in phone sshing to my homelab.

So imagine what i see on small screen with all that lines everywhere and if i exit less i can't scroll back because that help message was cleared from terminal. Thats why i don't like less by default.

**Comment by ivan-hc** [comment]
@zen0bit oh, ok... thank you for pointing out the length of the "help" option message.

In this case there is a reason for everything I listed. In order of placement:
1. LOGO, it's actually useless... I'll see what I can do;
2. SERVICE MESSAGE, "HELP ME MAKE AM/APPMAN KNOWN", this is because evidently no one gives a shit, no one advertises me, and I'm not a marketing expert.... if someone would also suggest me under the comments of a video or in a post or to whoever is responsible... they would help me continue with my project, and quite a bit;
3. OPTIONS, I tried to be as compact and detailed as possible, putting the options in alphabetical order... I can't do more than that;
4. FINAL INFO, they are certainly useless, I will see what to do here too.

In short:
- point 3 is the important one;
- while 1 and 4 can be improved/reduced/merged;
- I can even eliminate the 2 completely... but as long as no one helps me make my work known... I certainly can't afford to pay for an advertisement, and I have to do something to make others understand that I'm in serious difficulty.

PS: I have already published an idea on Github in the past and someone else took advantage of it by creating their own which became more popular and reviewed. I don't want to name names. I'm just telling you, it's hard to have worked and see others take the credit. And seeing where AM has reached today makes me tremble. I know it's a valid product and I know how many selfish thieves there are around, ready to publish an idea as their own and without even mentioning you in the notes. I'm afraid I'll have to throw 3 years of work down the toilet. I'm really scared this time.

**Comment by ivan-hc** [comment]
@zen0bit about your issue, it would be enough to convert the message into a function, for example `_help`, then
```
if command to test you are in Termux; then
 		_help
else
 		_help | less
fi
```
in this way we have solved the issue of `less` on smaller screens. Desktop view will remain with `less`

If you can tell me a command to test that you are on Termux, I'll be happy to improve this for you.

**Comment by zen0bit** [comment]
Maybe test for number of letters in row? (tput cols) Not test for termux, but for small screens in general. In my case it is 50.

terminal_width=$(tput cols)

if [ "$terminal_width" -lt 80 ]; then
    _help
else
    _help | less
fi

**Comment by ivan-hc** [comment]
> terminal_width

thank you, this is the info I needed.

Normally I set all messages (including the `-a` option) to 80. I was not aware about someone that was using my software on smartphones.

**Comment by CarterSnich** [comment]
Hi. Can I suggest to follow how other CLI commands show help messages? It's more cleaner and much familiar to most users as most commands follows the same way. Shorter version of the help message can be called with the `-h` flag and more detailed explanations goes to man page.

Left is `appman`. Right is `xbps-install`
<img width="1366" height="748" alt="Image" src="https://github.com/user-attachments/assets/15edf08a-2e5c-49d9-8dc7-98faded88a35" />

Left is `appman`. Right is `xbps-install` man page
<img width="1366" height="749" alt="Image" src="https://github.com/user-attachments/assets/13a39b58-ab12-4c51-9f42-6161e555a856" />

**Comment by ivan-hc** [comment]
Being minimalist is one thing, but being too minimalist is a disaster: some options support flags, others don't, some require arguments, others don't. Even today, despite the help message containing detailed syntax examples, some people open issues to ask for existing functionality. People just need to read the examples, and they'll be able to figure it out... but some don't. Having a help message that's too minimalist, and without examples (and without colorization, which in your case is grayscale), would lead to even more confusion and the opening of even more unnecessary issues (the most recent ones are these https://github.com/ivan-hc/AM/pull/1866 ).

I don't think it's worth reducing, then. AM has become a large program, and as such, it needs a help message that explains in detail what each option does.
