### ISSUE TITLE
Number of available apps and advertisement

### ISSUE THREAD

**Issue by 00sapo** [ivan-hc/AM#1215]
Today I realised that the number of apps available since when toolpack was introduced is decreased (see https://github.com/ivan-hc/AM/issues/1079#issuecomment-2466950465).

Here is what I get today with devmode enabled:

![image](https://github.com/user-attachments/assets/537cc4f6-05f4-4fef-9be5-eb0da5e5e8a5)

Aside from this, I think that the readme should make it more clear the number of apps and use it to advertise that this is an advantage in respect to alternatives (e.g. flatpaks). This should be said in both the repo description and in the first sentence that appears on  the top of the page. Also, some fancy logo and graphics would help make the project more appealing to new users...

**Comment by ivan-hc** [comment]
Hi. Regarding the reduction of programs, it happened that the way the programs were listed showed more duplicates per "family" of programs (3 `awk`, 4 `sed`, 4 `grep`...) but due to the way "AM" works, managing these subfamilies is not possible if not by using `soar` or `dbin` (available in the AM database). The result will always return the first package in the list, even if it shows different source information. So I preferred a list with only the unique programs available. **The risk was to install a different program than the one actually required**. The duplicates of the subfamilies would deserve a separate list (maybe `grep` for GLIBC, `bgrep` for BusyBox, `pgrep` for the Posix version... I don't know much about subfamilies).

For the rest, I don't understand what you mean. On the README and under the description there is the URL to the catalog of programs actually available in the "AM" database only https://portable-linux-apps.github.io

About the logo, I'm not an artist, I added a test one in AlternativeTo and that remained during the upload (even though I had removed it) https://alternativeto.net/software/am/about/

Other questions/suggestions/requests?

**Comment by 00sapo** [comment]
![image](https://github.com/user-attachments/assets/badf5ae5-7fb0-492f-8060-0193d0d34ffb)

The top-right description is what is shown in social networks, github previews, search engine, etc. and still has a lower number for the available apps. I would actually sell it like:

> The world's largest cross-distro Linux app manager. 3600+ apps and commands easily installable and sandboxable (at your will). Tired of Flatpaks? AM offers more apps, a terminal-friendly ecosystem, and a convenient package manager.

**Comment by ivan-hc** [comment]
> The top-right description is what is shown in social networks, github previews, search engine, etc. and still has a lower number for the available apps. I would actually sell it like:
> 
> > The world's largest cross-distro Linux app manager. 3600+ apps and commands easily installable and sandboxable (at your will). Tired of Flatpaks? AM offers more apps, a terminal-friendly ecosystem, and a convenient package manager.

Thanks for the advice and support, but... I can't post false information.

I care about being transparent in the things I do, and the truth is this:
- AM is both a CLI and a database
- AM database contains 2500+ scripts dedicated to each single app
- each app in the AM database has its own README page on the catalog
- all apps listed in the AM database come from their respective owners or third-party packagers, and every link refers to them, so in case of problems, the user who uses these apps, must contact them
- **Toolpacks is a database whose programs work even better than the originals**, but THEY ARE NOT THE ORIGINALS, so in case of bugs users should not contact upstream, and this creates confusion
- you and I know very well that AM is the best there is, but it is the best there is FOR US, not for everyone. So there is no point in showing off vanity uselessly. I am a humble person, and the description you provided fills my heart... but it does not correspond to the truth
- as far as I know, the largest cross-platform database is Toolpacks, since I have also tested it on FreeBSD recently. AM programs generally only work on Linux out of the box

I understand that you would like AM to be much more known by people, and I would like that too, honestly. But there is only one way to do that: spread the word about it. Recommend it to reviewers. Get it out to people who know about it (and who are willing to spend 15 minutes reading the documentation or at least the README).

Other programs are more successful because they were born when AppImages were more important (see ZAP and AppImageLauncher), and they deserve the success they had. Also because their developers have contributed a lot to building and supporting AppImages, really. Even better than me.

But now that AppImages have lost their appeal due to historical defects (lack of updates and integration, to name a couple), other fairly new programs are exposed on mainstream sites (like Flathub) and therefore are constantly exposed on the homepage, through "dummy" updates (appearing "updated", but by a couple of bits) and listing only 3-4 stupid features to improve the use of AppImages, but the upstream developer does not supports AppImages at all! And without even making the slightest effort to build an AppImage package! Not even if you give him examples! He denies the evidence! And if elsewhere they ask the developer why he doesn't provide an AppImage, he makes up excuses like "AppImages are mostly based on Electron anyway", making them pass for second-rate packages!

"AM" was born as an alternative to Flatpak, but if there are those who support Flatpak by throwing shit on AppImage, "AM" will never see the light, AppImage will have fewer and fewer developers willing to support it as a packaging format. And always by the will of **the mainstream**, which **does not see the developer most committed to growing an ecosystem, but to the most "flashy" one**. There are still people who think that all AppImages require `libfuse2` to work. None of my 70 AppImages have this dependency. But people continue to think that AppImages suck because of this. AppImages have lost this charm. "AM" wants to fight against all this. But if nobody talks about it, these are useless battles.

**Comment by ivan-hc** [comment]
Note, I am not looking for fame. "AM" is a CLI, without a graphical interface, in the era in which Linux grows on the desktop. There will always be someone who can do better than me. And I hope so. I created "AM" because Flatpak did not meet my needs, and because AppImages lacked a reliable package manager that could update and manage them all. ALL! I hope that someone who is better than me will be able to create a GUI, perhaps using AM as an engine, or some other devilry that will be invented. I hope so. For me it is enough that AppImage survives and grows! I do not want everything to be monopolized in favor of Flatpak. I want all packagers to have the opportunity to test themselves, having at their disposal the resources provided by upstream. I do not care if they will be AppImages, RPMs, DEBs, Snaps or Flatpaks: everyone must be able to build alternative packages!

Linux is beautiful because it is varied, but there is someone who would like all these distributions to be the same. For me it's like restricting freedom. It's a way to hide creativity in favor of a common line. If I had wanted this, I would have stayed on Windows.

**Comment by coyoteclan** [comment]
> ALL! I hope that someone who is better than me will be able to create a GUI, perhaps using AM as an engine

On my to-do list 💚

**Comment by ivan-hc** [comment]
@00sapo I have good news here https://github.com/ivan-hc/AM/pull/1358

| ![Image](https://github.com/user-attachments/assets/49de5778-714d-4561-be77-54b6f68f42be) | ![Image](https://github.com/user-attachments/assets/80bc6aa9-8e5d-467b-928b-0c1f2b232d53) |
| - | - |

Stay tuned!
