### ISSUE TITLE
how to get `SITE` from `appman -q {KEYWORD}`

### ISSUE THREAD

**Issue by candrapersada** [ivan-hc/AM#1228]
how to get `SITE PROGRAM` from `appman -q {KEYWORD}` without use `appman -a {PROGRAM}`?

**Comment by ivan-hc** [comment]
I had an option a while back that did what you ask... and I removed it.

The reason? Pages often have multiple references, and often indicate which is the real source and which URL the unofficial package comes from.

Take `bottles` for example, if you didn't know me, and if you had my unofficial AppImage and had both the official project and the unofficial package URLs available... who would you contact?

![Istantanea_2024-12-15_05-39-36](https://github.com/user-attachments/assets/89ee3eef-e0f1-448a-850c-27d71744051f)

Or for example, `mpv`, there are two URLs because the script is shared between two repositories that both provide an unofficial AppImage.

![Istantanea_2024-12-15_05-39-58](https://github.com/user-attachments/assets/9410b3be-d988-451e-a9f7-91791eb823dd)

With only the URL available, how do you know which one you have installed?

Therefore, I don't think it's worth it to add another option to only see the URL. The user needs to read and learn about things, before running into trouble.

The most I can suggest is to prepend a `grep "http"` after the `-a` command.

![Istantanea_2024-12-15_05-40-38](https://github.com/user-attachments/assets/97b4a274-11d9-402b-bac5-a6feafdc61ab)

I also don't want to overwhelm AM and the guides with too many options. There are too many of them, and people get confused, and end up asking the same questions about things that are already well documented.

I could add a flag to `-a` if you want... but that would just use `grep "http"` as I suggested above. And something like that isn't reliable either... for the reasons I explained above.
