### ISSUE TITLE
mercury, missing file

### ISSUE THREAD

**Issue by tuchanemo** [ivan-hc/AM#125]
Hi, the file /opt/mercury/mercury is missing after installation

**Comment by ivan-hc** [comment]
the script was checking too deep in the archive... three "*" are enough.

Its strange, because the first time I have uploaded the script, all worked well. Maybe is the developer that has changed the structure of the archive.

However, if I have to say my opinion, after the stormsh*t on YouTube about Thorium browser's review by Chris Titus Tech, I don't trust much the developers products.

**Comment by tuchanemo** [comment]
Thank you.

**Comment by Edgarruiz856** [comment]
- [x] edgarplasticos3@hotmail.com> Hi, the file /opt/mercury/mercury is missing after installation
