### ISSUE TITLE
NixOS module

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#1263]
# Is your feature request related to a problem? Please describe.
Write here
NixOS' appimage implementation sucks

# Describe the solution you'd like
Write a module for AM

# Describe alternatives you've considered
Write here
Just using through the terminal (no configuration file)

**Comment by Samueru-sama** [comment]
Are you talking about the [appimage wrapper](https://wiki.nixos.org/wiki/Appimage) of NixOS?

**Comment by Samueru-sama** [comment]
> The author is talking about writing a NixOS or home-manager module where you can install appimages declaratively like you can do with flatpaks on NixOS with the [nix-flatpak project](https://github.com/gmodena/nix-flatpak/),
> 
> for example, for flatpaks I manage them like:
> 
> ```
>   services.flatpak = {
>     enable = true;
>     remotes = [
>       {
>         name = "flathub";
>         location = "https://dl.flathub.org/repo/flathub.flatpakrepo";
>       }
>     ];
>     packages = [
>       "com.github.tchx84.Flatseal"
>       "com.steamgriddb.SGDBoop"
>       "io.mrarm.mcpelauncher"
>       "camp.nook.nookdesktop"
>       "org.freedesktop.Sdk/x86_64/23.08"
>       "com.fightcade.Fightcade"
>       "io.itch.itch"
>       "io.github.lime3ds.Lime3DS"
>       "io.github.Soundux"
>       "gg.guilded.Guilded"
>       "net.audiorelay.AudioRelay"
>     ];
>     update.auto = {
>       enable = true;
>       onCalendar = "daily";
>     };
>   };
> ```
> 
> and the equivalent doesn't exist because there wasn't any other centralised way to get appimages thru a CLI tool before `AM`.

Do we have to write something for this? I think for this to happen `AM` first would need to be available on NixOS and then the user could configure Nix to tell AM to install several packages at once. 

Also AM expects an FHS file structure with the user having `/opt` and `/usr/local/bin`, `/usr/share/{icons,applications}`, I guess you could use `appman` instead to install in `$HOME` but maybe this doesn't cut it either because it touches `$HOME`?

**Comment by Twig6943** [comment]
Well yea turns out appimages doesnt run without appimage-run on nixos too and .desktop files need to ne edited sooo tldr; the upstream project needs a nixos mode for this to be possible

**Comment by ivan-hc** [comment]
I still don't understand what all this has to do with AM

**Comment by Samueru-sama** [comment]
> Well yea turns out appimages doesnt run without appimage-run on nixos too and .desktop files need to be edited sooo tldr; the upstream project needs a nixos mode for this to be possible

The AppImages I maintain at [pkgforge-dev](https://github.com/pkgforge-dev/Anylinux-AppImages) should all run without the nixos wrapper since they bundle all the dependencies.  If they do not please open an issue at the respective repo because they should.

[This other one should also run](https://github.com/probonopd/PrusaSlicer/releases/tag/continuous) without the wrapper.

>I still don't understand what all this has to do with AM

Same

**Comment by Twig6943** [comment]
> > Well yea turns out appimages doesnt run without appimage-run on nixos too and .desktop files need to be edited sooo tldr; the upstream project needs a nixos mode for this to be possible
> 
> The AppImages I maintain at [pkgforge-dev](https://github.com/pkgforge-dev/Anylinux-AppImages) should all run without the nixos wrapper since they bundle all the dependencies. If they do not please open an issue at the respective repo because they should.
> 
> [This other one should also run](https://github.com/probonopd/PrusaSlicer/releases/tag/continuous) without the wrapper.
> 
> > I still don't understand what all this has to do with AM
> 
> Same

ok there goes that issue

**Comment by Twig6943** [comment]
Milestones fot this:
AM on nixpkgs :x:
AM nixos module ✅

**Comment by ivan-hc** [comment]
> Milestones fot this: AM on nixpkgs ❌ AM nixos module ❌

It feels like talking to a robot

**Comment by Samueru-sama** [comment]
> Well yea turns out appimages doesnt run without appimage-run on nixos too and .desktop files need to be edited sooo tldr; the upstream project needs a nixos mode for this to be possible

I also don't think we have to edit the .desktop since [this](https://wiki.nixos.org/wiki/Appimage#Configuration) mentions that you can use `binfmt_misc` to open all appimages with the appimage wrapper. 

That thing with `binfmt_misc` is also how AppImageLauncher works internally iirc.

**Comment by ivan-hc** [comment]
AM rejects `appimagelauncherd`, `appimaged` or any implementation that may involve changes to `systemd-binfmt` since they are ment to allow AppImages working completelly standalone, so they can't be handled by any other AppImage manager or even by a command line interface... and AM is both a package manager and a CLI for AppImages.

**Comment by Samueru-sama** [comment]
> AM rejects `appimagelauncherd`, `appimaged` or any implementation that may involve changes to `systemd-binfmt` since they are ment to allow AppImages working completelly standalone, so they can't be handled by any other AppImage manager or even by a command line interface... and AM is both a package manager and a CLI for AppImages.

In this case this isn't a problem for AM, the problem is appimagelauncher being broken, not `binfmt_misc` itself. 

We also don't have to write anything for that, **that's the point of of `binfmt_misc`** that intercepts calls to certain binaries to do additional stuff like launching it with `appimage-run` because otherwise most appimages won't run.
