### ISSUE TITLE
shellcheck

### ISSUE THREAD

**Issue by zen0bit** [ivan-hc/AM#128]
I tried runned shellcheck on APP-MANAGER
😤
a LOT of comply

Maybe some more code cleanup?
[shellcheck](https://github.com/koalaman/shellcheck)
 or shfmt

**Comment by ivan-hc** [comment]
its a product I have tested to for my scripts... and when I had to correct something, there is always something other that does not work.

However, after the latest PRs on code-cleaning I had too many incompatibility of functions between AM and AppMan, because anyone tests or AM, or AppMan... not both.

I know my code, and this is what works for me.

With all respect as possible, but I wont accept code cleanings anymore. 

"Disrespectful" and "abusive" use of one command over another, clearing spaces, using `printf` instead of `echo`... I don't want to hear any more of this. I spend hours and hours trying to make things work as best as possible, then someone always comes along who "for the sake of grammar" has to correct an expression which in the end turns out to be destructive. I don't want to waste time with this "cleaning". The only "cleaning" they know how to do is that of dissatisfied users because something no longer works as before.

That's all.

Thanks for interesting.
