### ISSUE TITLE
Include packages versions

### ISSUE THREAD

**Issue by zen0bit** [ivan-hc/AM#383]
Nice to see which packages versions are available, updated, updating with..

What you think?🤔

**Comment by ivan-hc** [comment]
Are you talking about `-f`?

**Comment by Samueru-sama** [comment]
This is going to be a lot of work because the version file in each package is usually the full url download link.

I think it has to be done eventually though.

**Comment by ivan-hc** [comment]
> This is going to be a lot of work because the version file in each package is usually the full url download link.
> 
> I think it has to be done eventually though.

its not just this, not all installed apps have this "version" file, for example, Firefox (the original one).

Another option would be tho check the version from the binary itself... but not fo all it works.

If you try this on Avidemux, for example, the app has no options at all, just the ones to extract the AppImage, elsewere the AppImage simply starts with its default GUI

**Comment by Samueru-sama** [comment]
@ivan-hc In that case the best approach would be to add a new file for this, for example `actualversion` that will contain the version of the application, and little by little we start adding it. 

And once we have enough packages with `actualversion` file AM can start displaying it along side the package name. 

What do you think? I can start doing that to the apps I've added once you give the go ahead.

**Comment by Samueru-sama** [comment]
For example for the packages that use github for download, the version is usually the second field in the `$version` url. 

So `pkgversion=$(echo $version | awk -F / '{print $(NF-1)}'` would do it for most packages.

**Comment by ivan-hc** [comment]
> @ivan-hc In that case the best approach would be to add a new file for this, say for example `actualversion` that will contain the version of the application, and little by little we start adding it.
> 
> And once we have enough packages with `actualversion` file AM can start displaying it along side the package name.
> 
> What do you think? I can start doing that to the apps I've added once you give the go ahead.

I like the idea... but I think AM is doing too much.

Furthermore, AM was built to always install the latest version of the app available from the source. If the package turns out to be old, there are 2 reasons:
1. AM hasn't updated in a long time;
2. the source developer has not added an official AppImage, or any portable format that AM can handle.

For point 2, the choice would make more sense. It would mean reminding the user to go and "wand" the developer upstream to have him update the AppImage (and he will surely tell you "NO! Use Flatpak!"). Other than that, I don't see much reason to put that information in "`-f`".

**Comment by ivan-hc** [comment]
> For example for the packages that use github for download, the version is usually the second field in the `$version` url.
> 
> So `pkgversion=$(echo $version | awk -F / '{print $(NF-1)}'` would do it for those packages.

what if it is a Continuous build (like all mine)?

**Comment by ivan-hc** [comment]
@Samueru-sama also, many Appimages can be updated using "`zsync`", so the upstream developer has nothing to do but update that file without having to change the name to the file.

**Comment by Samueru-sama** [comment]
> > For example for the packages that use github for download, the version is usually the second field in the `$version` url.
> > So `pkgversion=$(echo $version | awk -F / '{print $(NF-1)}'` would do it for those packages.
> 
> what if it is a Continuous build (like all mine)?

`if [ "pkgversion" = "continuous" ]; then hack_to_get_the_package_version_from_continuous_builds`

We don't actually have to change the current way package update, `pkgversion` would only be used to display the actual version of the file if it exists.

**Comment by ivan-hc** [comment]
@Samueru-sama please, read the two comments related to .zsync

**Comment by ivan-hc** [comment]
> @Samueru-sama please, read the two comments related to .zsync

@Samueru-sama for example, "FUNCTION" can be something like this:
```
echo "https://github.com/ivan-hc/AM/issues/AppName-continuous-x86_64.AppImage"
```
there is no way to have a version number from here.

The release's versions are at the pure discretion of the developers, in most cases.

**Comment by ivan-hc** [comment]
> > @Samueru-sama please, read the two comments related to .zsync
> 
> @Samueru-sama for example, "FUNCTION" can be something like this:
> 
> ```
> echo "https://github.com/ivan-hc/AM/issues/AppName-continuous-x86_64.AppImage"
> ```
> 
> there is no way to have a version number from here.
> 
> The release's versions are at the pure discretion of the developers, in most cases.

I had the same result in many AppImages hosted in the OpenSUSE's servers, all without a version number but all with a .zsync file... for example, the earlier scripts for Celestia /Celestia-dev

**Comment by ivan-hc** [comment]
@zen0bit @Samueru-sama Having said all this, this is why showing only SIZE and TYPE in "-f" is the most sensible choice

**Comment by Samueru-sama** [comment]
> > @Samueru-sama please, read the two comments related to .zsync
> 
> @Samueru-sama for example, "FUNCTION" can be something like this:
> 
> ```
> echo "https://github.com/ivan-hc/AM/issues/AppName-continuous-x86_64.AppImage"
> ```
> 
> there is no way to have a version number from here.
> 
> The release's versions are at the pure discretion of the developers, in most cases.

Well in that case, if the package is continuous then it stays as continuous xd. that is they are like aur git packages which don't have a version and only display the last commit number.

**Comment by ivan-hc** [comment]
> > > @Samueru-sama please, read the two comments related to .zsync
> > 
> > 
> > @Samueru-sama for example, "FUNCTION" can be something like this:
> > ```
> > echo "https://github.com/ivan-hc/AM/issues/AppName-continuous-x86_64.AppImage"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > there is no way to have a version number from here.
> > The release's versions are at the pure discretion of the developers, in most cases.
> 
> Well in that case, if the package is continuous then it stays as continuous xd. that is they are like aur git packages which don't have a version and only display the last commit number.

I was wrong to use Github as an example, if the app is hosted on a private domain... where do you get the commit number from?

**Comment by Samueru-sama** [comment]
> > > > @Samueru-sama please, read the two comments related to .zsync
> > > 
> > > 
> > > @Samueru-sama for example, "FUNCTION" can be something like this:
> > > ```
> > > echo "https://github.com/ivan-hc/AM/issues/AppName-continuous-x86_64.AppImage"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > there is no way to have a version number from here.
> > > The release's versions are at the pure discretion of the developers, in most cases.
> > 
> > 
> > Well in that case, if the package is continuous then it stays as continuous xd. that is they are like aur git packages which don't have a version and only display the last commit number.
> 
> I was wrong to use Github as an example, if the app is hosted on a private domain... where do you get the commit number from?

We don't have to do that, I think displaying `continuous` for `pkgversion` or chaging `continuous` to `git` `devel` or similar and display the installation date alongside is better than nothing in that case.

**Comment by ivan-hc** [comment]
> We don't have to do that, I think displaying `continuous` for `pkgversion` or chaging `continuous` to `git` `devel` or similar and display the installation date alongside is better than nothing in that case.

Are just APPNAME, TYPE and SIZE... "nothing"?

> EDIT: And once again this is something that can be done little by little and only after enought packages have the `pkgversion` file in them AM would be changed to display it as well.

`pkgversion` is something that only AUR maintainers can do, beingh those packages continuously being updated.

Changes in the installation scripts, instead, are already notified when you use `-s`

**Comment by ivan-hc** [comment]
@Samueru-sama go in /opt/any-appimmage-you-want/.am-installer/, open the with a text editor and remove just one space or one character, and then save. Finally, execute the option `-s` and... in the end just tell me if adding the installation's date have sense.

**Comment by Samueru-sama** [comment]
> @Samueru-sama go in /opt/any-appimmage-you-want/.am-installer/, open the file with a text editor and remove just one space or one character, and then save. Finally, execute the option `-s` and... in the end just tell me if adding the installation's date have sense.

It wouldn't be the date of the file, it would be the date when the package was installed and that would be printed in the `pkgversion` file.

**Comment by ivan-hc** [comment]
> > @Samueru-sama go in /opt/any-appimmage-you-want/.am-installer/, open the file with a text editor and remove just one space or one character, and then save. Finally, execute the option `-s` and... in the end just tell me if adding the installation's date have sense.
> 
> It wouldn't be the date of the file, it would be the date when the package was installed and that would be printed in the `pkgversion` file.

Why?

**Comment by ivan-hc** [comment]
> > > @Samueru-sama go in /opt/any-appimmage-you-want/.am-installer/, open the file with a text editor and remove just one space or one character, and then save. Finally, execute the option `-s` and... in the end just tell me if adding the installation's date have sense.
> > 
> > 
> > It wouldn't be the date of the file, it would be the date when the package was installed and that would be printed in the `pkgversion` file.
> 
> Why?

@Samueru-sama That is, I want to understand what the meaning of this work to be done is. @zen0bit  asked for the package version, in this Issue, not when it was last installed/updated.

**Comment by Samueru-sama** [comment]
> > > @Samueru-sama go in /opt/any-appimmage-you-want/.am-installer/, open the file with a text editor and remove just one space or one character, and then save. Finally, execute the option `-s` and... in the end just tell me if adding the installation's date have sense.
> > 
> > 
> > It wouldn't be the date of the file, it would be the date when the package was installed and that would be printed in the `pkgversion` file.
> 
> Why?

Are you suggesting that the pkgversion file would be used for updating instead of the existing version file? That is what I understood when you said to use the -s flag after adding an space. That is not what I'm suggesting, what I'm saying to add a new file forr the purpose of either display the actual version or at least display that it is continuous + date or last commit for example.

**Comment by ivan-hc** [comment]
> > > > @Samueru-sama go in /opt/any-appimmage-you-want/.am-installer/, open the file with a text editor and remove just one space or one character, and then save. Finally, execute the option `-s` and... in the end just tell me if adding the installation's date have sense.
> > > 
> > > 
> > > It wouldn't be the date of the file, it would be the date when the package was installed and that would be printed in the `pkgversion` file.
> > 
> > 
> > Why?
> 
> Are you suggesting that the pkgversion file would be used for updating instead of the existing version file? That is what I understood when you said to use the -s flag after adding an space. That is not what I'm suggesting, what I'm saying is to add a new file for the purpose of either display the actual version or at least display that it is continuous + date or last commit for example.

@Samueru-sama What you are proposing is information that would not interest anyone. It is not the installation date of the script that interests the user, but whether the package is updated to the latest version, and if it is not, there are 2 possibilities:
1. the installation script points to a URL that is no longer maintained, and therefore needs to be updated... the "`-s`" option will notify you of the change;
2. It is the creator of the package who should update it, not the author of this CLI. It's not my responsibility if someone else's app doesn't work. I just distribute them, it's up to the user to trust/care about that package, if he decided to install it.

**Comment by ivan-hc** [comment]
> > > > @Samueru-sama go in /opt/any-appimmage-you-want/.am-installer/, open the file with a text editor and remove just one space or one character, and then save. Finally, execute the option `-s` and... in the end just tell me if adding the installation's date have sense.
> > > 
> > > 
> > > It wouldn't be the date of the file, it would be the date when the package was installed and that would be printed in the `pkgversion` file.
> > 
> > 
> > Why?
> 
> @Samueru-sama That is, I want to understand what the meaning of this work to be done is. @zen0bit asked for the package version, in this Issue, not when it was last installed/updated.

@Samueru-sama again, I re-quote this previous answer.

**Comment by Samueru-sama** [comment]
> > > > > @Samueru-sama go in /opt/any-appimmage-you-want/.am-installer/, open the file with a text editor and remove just one space or one character, and then save. Finally, execute the option `-s` and... in the end just tell me if adding the installation's date have sense.
> > > > 
> > > > 
> > > > It wouldn't be the date of the file, it would be the date when the package was installed and that would be printed in the `pkgversion` file.
> > > 
> > > 
> > > Why?
> > 
> > 
> > Are you suggesting that the pkgversion file would be used for updating instead of the existing version file? That is what I understood when you said to use the -s flag after adding an space. That is not what I'm suggesting, what I'm saying is to add a new file for the purpose of either display the actual version or at least display that it is continuous + date or last commit for example.
> 
> @Samueru-sama What you are proposing is information that would not interest anyone. It is not the installation date of the script that interests the user, but whether the package is updated to the latest version, and if it is not, there are 2 possibilities:
> 
> 1. the installation script points to a URL that is no longer maintained, and therefore needs to be updated... the "`-s`" option will notify you of the change;
> 2. It is the creator of the package who should update it, not the author of this CLI. It's not my responsibility if someone else's app doesn't work. I just distribute them, it's up to the user to trust/care about that package, if he decided to install it.

Well it would interesting to me to know if I package I have installed hasn't had an update for a long time which would be reflected in that file. which sorry if this is already possible with am btw. 

EIther way lets see what [zen0bit](https://github.com/zen0bit) has to say.

**Comment by Samueru-sama** [comment]
> > Well it would interesting to me to know if I package I have installed hasn't had an update for a long time which would be reflected in that file. which sorry if this is already possible with am btw.
> > EIther way lets see what [zen0bit](https://github.com/zen0bit) has to say.
> 
> They are called "portable applications" for a reason. They were designed to be downloaded from the author's site and to encourage users to go to the author's site every time to find out about any changes, otherwise they would have been hosted in a centralized repository, such as .deb, .rpm, and .flatpak.. "AM" is just a way to get the latest version without having to open the browser every time... but if you want to get more detailed information about the individual app and what has changed, use the `-a` option and open the link indicated.
> 
> Let's not overload the work on this CLI with things that are not our responsibility. I published the https://portable-linux-apps.github.io site to provide a graphical interface, and that's one more thing I did. It shouldn't be my job to open such a site, but that of a community truly interested in growing the work around this CLI, and therefore the publication and management of individual pages. There would need to be a great organization behind all this, but that isn't the case. It's just me, and I also "take care" of the individual app pages (and that's something I really don't want to do).
> 
> In this issue, we are talking about adding small details to a CLI that has already gone too far compared to what it should do, from a simple CLI to be used in a Linux terminal, and around which the author (again me) has done too much work to try to make it known to the masses and to encourage them to start a community aimed at keeping Appimages alive as a packaging format, including creating a site and opening 50+ repositories containing 60 different Appimages.
> 
> But concretely, what do we have today?
> 
> We have to discuss about inserting versions of software packages managed by third parties who don't even know that "AM" exists. And that is. We are nobody. We are just a phantom project, who cares for the few who haven't yet convinced themselves that "Flatpak is the future"!
> 
> That said, the option `-a` is sufficient for what you're asking. Really, I don't think there's any point in adding work on things that aren't essential to what "AM" currently is in the Linux world: nothing.
> 
> If you've seen such functionality in Synaptics/APT, Pamac/Pacman/YAY and Flatpak/Flathub... good for them, they have such a large and strong community behind them. It's nice to be popular, don't you think?

It's ok, this was something I wanted to try myself in implementing, but no problem. 

>I don't think there's any point in adding work on things that aren't essential to what "AM" currently is in the Linux world: nothing.

Well it is something to me. And thank you once again for making this tool. it is what made me to start making appimages as well.

**Comment by zen0bit** [comment]
I think you should rename AM to something other then manager then.

Do you saw any manager who don't know what is managing???
🤣 
maybe updater?

**Comment by ivan-hc** [comment]
> I think you should rename AM to something other then manager then.
> 
> Do you saw any manager who don't know what is managing??? 🤣 maybe updater?

Ehm... in the description I wrote "installs, updates and manage"... so I should remove "manage" at this point. :stuck_out_tongue_closed_eyes:

**Comment by ivan-hc** [comment]
> Do you saw any manager who don't know what is managing???

Now @zen0bit , seriously... I've listed a series of reasons because what we want try to implement in -f is useless, I'll try to resume:

1. AM always points to the latest version available
2. Portable Apps are ment to be downloaded from the site of the developer, AM only helps to reach the source faster
3. to fit a wider table, the -f option loses its aestetics, being many terminal emulators set to be 80 charachers wide, on desktop/laptop, not just for those that use it on Steamdeck or Termux :roll_eyes: 
4. not all apps have a file version
5. not all apps can show the version with an option
6. often some Appimages can be updated with zsync, so we can't take track of the version if not with an option that may be missing (see above)
7. not all apps ave the version in the URL
8. not all apps come from github, so we can't take track of versions or commits in the same way

...maybe I miss something, but the point to solve this is unreachable, at least for now.

If we want to take track of all the versions we also need a database of packages, while we have just scripts.

What? AUR has package versions in the PKGBUILDs? I know this, and each script has one or more maintainers that in their spare time can check the last version of each application and puts it in the PKGBUILD.

However, this is not the AUR, this is AM. A public repo maintained by one user, and with the help of some contributors sometime. I can't say all because its a lie, but more than 1900 installation scripts are wrote from just one asshole, me, that despite having done everything to bring about a lasting solution, in view of a lasting abandonment of this repository (whatever the reason may be)... the same asshole that now must read that AM is not worthy of being a "Manager", as the name implies. Oh, come on man! I know you're joking, but let's try to make those who read these issues in the future understand why I closed everything as "unplanned".

However, it is also for this that I am pushing you opening your own community driven database, and I hope that day will come. I really hope this. Maybe with better written installation scripts, something not thought of by me but by the community. This is why I care so much about the creation of a community around this project. I can only lay the foundations, and throw options like "-t", designed precisely so that people stop asking me to load apps and start making Pull Requests instead... and the more time passes, the more I realize that that option is also useless. Most of the time they give me "Requests" but without "Pull".

You know, I'm trying hard to make people understand my project, how it works and get them used to the idea that they can do something themselves, instead of relying on me. You see, I built this project without an expert IT background, with knowledge that I still lack... but I did it because no one had thought of doing it. And I didn't have to hide behind the excuse of "we don't have the resources", as many other developers say, in more famous projects.

PS, before you say that I do everything to close Issues quickly, today I was experimenting all the time with a way to implement this function, and the result was "gross". Going back to point 3, above, when an app has a long name and an even longer version number (like Chromium or Gimp GIT) the table falls apart, completely, and the lines are suddenly truncated, because they don't fit within the 80 total characters of the terminal emulators, surpass it.

If we really want to implement something like this, we will need a graphical interface, there it will be possible to include the whole URL too, and we could scroll a bar to read everything... and this is not good in a terminal window... especially for those "tired of seeing the `less` command everywhere" (any reference to Termux users is to be considered purely coincidental).

**Comment by zen0bit** [comment]
> 1. AM always points to the latest version available

wrong

> 2. Portable Apps are ment to be downloaded from the site of the developer, AM only helps to reach the source faster

sure

> 3. to fit a wider table, the -f option loses its aestetics, being many terminal emulators set to be 80 charachers wide, on desktop/laptop, not just for those that use it on Steamdeck or Termux 🙄

ok - D you know that in termux you can easily change size of screen just with two fingers? :rofl: 

> 4. not all apps have a file version

got it 

> 5. not all apps can show the version with an option

got it 

> 6. often some Appimages can be updated with zsync, so we can't take track of the version if not with an option that may be missing (see above)

Not familiar with zsync (know what it is but how it really works...) 

> 7. not all apps ave the version in the URL

obviously
 
> 8. not all apps come from github, so we can't take track of versions or commits in the same way

obviously

> maybe I miss something, but the point to solve this is unreachable, at least for now.

We just don't know how to do that yet..
 
> If we want to take track of all the versions we also need a database of packages, while we have just scripts.

will be better
 
> What? AUR has package versions in the PKGBUILDs? I know this, and each script has one or more maintainers that in their spare time can check the last version of each application and puts it in the PKGBUILD.

Yes, same as void (I am packaging for)

> However, this is not the AUR, this is AM. A public repo maintained by one user, and with the help of some contributors sometime. I can't say all because its a lie, but more than 1900 installation scripts are wrote from just one asshole, me, that despite having done everything to bring about a lasting solution, in view of a lasting abandonment of this repository (whatever the reason may be)... the same asshole that now must read that AM is not worthy of being a "Manager", as the name implies. Oh, come on man! I know you're joking, but let's try to make those who read these issues in the future understand why I closed everything as "unplanned".

So is actually "unplanned" or just "help needed"? (It's nonsense or you wanna implement that, just don't know how?)

> However, it is also for this that I am pushing you opening your own community driven database, and I hope that day will come. I really hope this. Maybe with better written installation scripts, something not thought of by me but by the community. This is why I care so much about the creation of a community around this project. I can only lay the foundations, and throw options like "-t", designed precisely so that people stop asking me to load apps and start making Pull Requests instead... and the more time passes, the more I realize that that option is also useless. Most of the time they give me "Requests" but without "Pull".

I will get to that (but it will take some time)

> You know, I'm trying hard to make people understand my project, how it works and get them used to the idea that they can do something themselves, instead of relying on me. You see, I built this project without an expert IT background, with knowledge that I still lack... but I did it because no one had thought of doing it. And I didn't have to hide behind the excuse of "we don't have the resources", as many other developers say, in more famous projects.

:+1:

> PS, before you say that I do everything to close Issues quickly, today I was experimenting all the time with a way to implement this function, and the result was "gross". Going back to point 3, above, when an app has a long name and an even longer version number (like Chromium or Gimp GIT) the table falls apart, completely, and the lines are suddenly truncated, because they don't fit within the 80 total characters of the terminal emulators, surpass it.

Again you just don't know yet so..
QUESTION: I want this? YES or NO
if YES - don't closing as not planned
if NO ok close it.
(Imagine some better coder then both of us together will came and see it as not planned, so why do any effort with implementing that (nice change) if is marked as not planned?)
you see? - consequences

> If we really want to implement something like this, we will need a graphical interface, there it will be possible to include the whole URL too, and we could scroll a bar to read everything... and this is not good in a terminal window... especially for those "tired of seeing the `less` command everywhere" (any reference to Termux users is to be considered purely coincidental).

We will get to that...
:rofl:

**Comment by ivan-hc** [comment]
> So is actually "unplanned" or just "help needed"? (It's nonsense or you wanna implement that, just don't know how?)

> Again you just don't know yet so..
QUESTION: I want this? YES or NO
if YES - don't closing as not planned
if NO ok close it.
(Imagine some better coder then both of us together will came and see it as not planned, so why do any effort with implementing that (nice change) if is marked as not planned?)
you see? - consequences

@zen0bit  You convinced me, in case anyone else has an idea how to do it, they are welcome.

However, I assume that in order for this to be feasible, we need a complete redraw of all installation scripts, in order to catalog all the information available for that program, including the type (appimage? script? standalone archive? binary ? other?).

> wrong (should point to latest reelease available) how that rollback works? never used. It just for apps you already installed older version?

the option `--rollback` only works with github apps (so they have a standard scheme), or for those scripts including a dedicated template (see `kdenlive`)

This is how a common AM-rollback script works for github apps:
```
#!/usr/bin/env bash

APP=SAMPLE
rm -f ./rollback-args ./AM-rollback
URL=WEBPAGE-CONTAINING-URLS
SITE=MAIN-DOMAIN-OR-SITE
printf "%s\n" $(wget -q $URL -O - | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep -i appimage) >> "./rollback-args" &&
echo -e "-----------------------------------------------------------------------\nYou have chosen to roll back $APP.\nRollback will be done from $SITE\n-----------------------------------------------------------------------"
printf "Select a URL from this menu (read carefully) or press CTRL+C to abort:\n-----------------------------------------------------------------------\n"; sleep 1;
select d in $(cat "./rollback-args"); do test -n "$d" && break; echo ">>> Invalid Selection"; done
cp ./AM-updater ./AM-rollback
sed -i 's/version0/#version0/g' ./AM-rollback
sed -i '/show-progress/c\wget -q --show-progress '$d'' ./AM-rollback
./AM-rollback
rm -f ./version
echo $d >> ./version
rm -f ./rollback-args ./AM-rollback
echo -e "\nROLLBACK SUCCESSFUL!"
exit
```
and this is the ome of Kdenlive (not hosted on github)
```
#!/usr/bin/env bash

APP=kdenlive
rm -f ./rollback-args* ./AM-rollback

# STABLE AND MORE RECENT VERSIONS
STABLE=$(wget -q https://download.kde.org/stable/kdenlive/ -O - | grep -Eo "[0-9.?]*" | grep -i ".12\|.08\|.04" | uniq | sort -nr)
for arg in $STABLE; do
	for var in $arg; do
		printf "%s\n" $(wget -q https://download.kde.org/stable/kdenlive/$var/linux/ -O - | grep -Eo "[a-zA-Z0-9./?=_%:-]*" | grep -i kdenlive | uniq | sort -nr | grep -v '/' | grep -i appimage) >> "./rollback-args-1"
	done
done

# ARCHIVED OLD RELEASES (THAT MAY NOT WORK)
ARCHIVED=$(wget -q https://download.kde.org/Attic/kdenlive/ -O - | grep -Eo "[0-9.?]*" | grep -i ".12\|.08\|.04" | uniq | sort -nr)
for arg in $ARCHIVED; do
	for var in $arg; do
		printf "%s\n" $(wget -q https://download.kde.org/Attic/kdenlive/$var/linux/ -O - | grep -Eo "[a-zA-Z0-9./?=_%:-]*" | grep -i kdenlive | uniq | sort -nr | grep -v '/' | grep -i appimage) >> "./rollback-args-2"
	done
done

# PREPARE THE LIST OF VERSIONS BY MERGING THE TWO ABOVE
for arg in $(cat ./rollback-args-1); do
	for var in $arg; do
		rel=$(echo $arg | cut -c 10- | cut -c -5)
		printf "%s\n" https://download.kde.org/stable/kdenlive/$rel/linux/$arg >> "./rollback-args"
	done
done
for arg in $(cat ./rollback-args-2); do
	for var in $arg; do
		rel=$(echo $arg | cut -c 10- | cut -c -5)
		printf "%s\n" https://download.kde.org/Attic/kdenlive/$rel/linux/$arg >> "./rollback-args"
	done
done

# LET ROLLBACK KDENLIVE
echo -e "-----------------------------------------------------------------------\nYou have chosen to roll back $APP.\nRollback will be done from https://kdenlive.org\n-----------------------------------------------------------------------"
printf "Select a URL from this menu (read carefully) or press CTRL+C to abort:\n-----------------------------------------------------------------------\n"; sleep 1;
select d in $(cat "./rollback-args"); do test -n "$d" && break; echo ">>> Invalid Selection"; done
cp ./AM-updater ./AM-rollback
sed -i 's/version0/#version0/g' ./AM-rollback
sed -i '/show-progress/c\wget -q --no-verbose --show-progress --progress=dot:mega -q --show-progress '$d'' ./AM-rollback
./AM-rollback
rm -f ./version
echo $d >> ./version
rm -f ./rollback-args* ./AM-rollback
echo -e "\nROLLBACK SUCCESSFUL!"
exit
```

> Not familiar with zsync (know what it is but how it really works...)

`zsync` only downloads the differences between upstream and installed apps, for example `libreoffice`, instead of downloading all 320 MB of AppImage archive again, just downloads few megabites to be included/replaced in the existing archive, so the update is faster and more convenient. But not all developers include this in their AppImages (me included, I don't know how to implement this).

**Comment by zen0bit** [comment]
You can also use labels for issues and PRs. to better sort them if laying here for longer time...

**Comment by ivan-hc** [comment]
> You can also use labels for issues and PRs. to better sort them if laying here for longer time...

I try to close them as soon as possible, however, most of the time a solution is found, and if it isn't found, I keep it in mind and go back to contact the user who was suffering from a problem, as happened today, with the form "install.am" which prevented some apps installed on immutable distributions or with BTRFS from creating .desktop launchers in /usr/local/share/applications

But these are still bugs, i.e. malfunctions of already existing codes, and not requests for features to be added. We know that a lot of work needs to be done for the latter, because there is new code to study and implement.

Speaking of the "files.am" module we have 15 lines/functions to expand to bring the columns from 3 to 4, and a variable with multiple values in `if`/`elif` functions (maybe as many times) due to the provenance of the version data of installed files. This is what I discovered in my today tests.

By rewriting all the installation scripts in the database, we could easily reduce the lines from 15 to just one, since they would include all the data needed for the module to read the necessary information.

**Comment by zen0bit** [comment]
And `help wanted` label?

**Comment by Samueru-sama** [comment]
> By rewriting all the installation scripts in the database, we could easily reduce the lines from 15 to just one, since they would include all the data needed for the module to read the necessary information.

Add the `sed -i "s/Exec=[^ ]*/Exec=$APP/g" ./$APP.desktop` trick I showed up before to the new install scripts as well, and I think something similar can be done with the `Icons=` part.

**Comment by ivan-hc** [comment]
@Samueru-sama let me see these changes throug a PR after you've tested that on your fork

**Comment by Samueru-sama** [comment]
> @Samueru-sama let me see these changes throug a PR after you've tested that on your fork

😅 those were the changes of the last PR of gpgfrontend?

**Comment by ivan-hc** [comment]
> > @Samueru-sama let me see these changes throug a PR after you've tested that on your fork
> 
> 😅 those were the changes of the last PR of gpgfrontend?

and you're more familiar with this kid of workflow, let me see what you're able to do:

https://github.com/ivan-hc/AM/blob/main/templates/AM-SAMPLE-AppImage

**Comment by Samueru-sama** [comment]
> > > @Samueru-sama let me see these changes throug a PR after you've tested that on your fork
> > 
> > 
> > 😅 those were the changes of the last PR of gpgfrontend?
> 
> and you're more familiar with this kind of workflow, let me see what you're able to do:
> 
> https://github.com/ivan-hc/AM/blob/main/templates/AM-SAMPLE-AppImage

https://github.com/ivan-hc/AM/pull/398
