### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Ranko-Saotome** [ivan-hc/AM#390]
App images for gpgfrontend and qmasterpassword are not showing up in the start menu after install 
I'm using Zorin OS 17

**Comment by Samueru-sama** [comment]
Alright the issue with gpgfrontend is that the desktop entry in `/usr/local/share/applications/AM-gpgfrontend.desktop` has an error in the `Exec=` line.

```
Exec=GpgFrontend
```

It should be instead gpgfrontend without the capital letters. You can edit that file in the meantime while this is fixed.

And qmasterpassword is broken for good because it is not making the desktop entry at all lol. You can also use appman instead of am as I tested it both and they do work without issues there.

**Comment by ivan-hc** [comment]
About qmasterpassword the issue is the same of many times. The tempate has a command "`grep $app`" to search te correct entry in the .desktop file. Now I've replaced it with "`grep -i $app`", and did this for all future scripts that will use the template [AM-SAMPLE-AppImage](https://github.com/ivan-hc/AM/blob/main/templates/AM-SAMPLE-AppImage), see https://github.com/ivan-hc/AM/commit/d3fd55f801a4db26535169446298e4d23d4d2e54

**Comment by Samueru-sama** [comment]
> About qmasterpassword the issue is the same of many times. The tempate has a command "`grep $app`" to search te correct entry in the .desktop file. Now I've replaced it with "`grep -i $app`", and did this for all future scripts that will use the template [AM-SAMPLE-AppImage](https://github.com/ivan-hc/AM/blob/main/templates/AM-SAMPLE-AppImage), see [d3fd55f](https://github.com/ivan-hc/AM/commit/d3fd55f801a4db26535169446298e4d23d4d2e54)

Hey are you sure qmasterpassword was also fixed? because I still don't have the `.desktop` in `/usr/local/share/applications`. 

I noticed that is something odd going on, doing a `./qMasterPassword-x86_64-qt5.AppImage --appimage-extract usr/share/applications/*.desktop` fails for some reason. but ``./qMasterPassword-x86_64-qt5.AppImage --appimage-extract usr/share/applications` doesn't fail and it does extract the .desktop entry lol.

**Comment by ivan-hc** [comment]
> > About qmasterpassword the issue is the same of many times. The tempate has a command "`grep $app`" to search te correct entry in the .desktop file. Now I've replaced it with "`grep -i $app`", and did this for all future scripts that will use the template [AM-SAMPLE-AppImage](https://github.com/ivan-hc/AM/blob/main/templates/AM-SAMPLE-AppImage), see [d3fd55f](https://github.com/ivan-hc/AM/commit/d3fd55f801a4db26535169446298e4d23d4d2e54)
> 
> Hey are you sure qmasterpassword was also fixed? because I still don't have the `.desktop` in `/usr/local/share/applications`.
> 
> I noticed that is something odd going on, doing a `./qMasterPassword-x86_64-qt5.AppImage --appimage-extract usr/share/applications/*.desktop` fails for some reason. but `./qMasterPassword-x86_64-qt5.AppImage --appimage-extract usr/share/applications` doesn't fail and it does extract the .desktop entry lol.

![Istantanea_2024-04-15_14-48-39](https://github.com/ivan-hc/AM/assets/88724353/d46c04c8-cf8f-43b3-b804-13cba4202a2d)
![Istantanea_2024-04-15_14-47-54](https://github.com/ivan-hc/AM/assets/88724353/8d456cdd-bec9-4f8e-8771-fcec885e2e5f)

**Comment by Samueru-sama** [comment]
@ivan-hc Ok something happened that am doesn't update, I don't know if it is a conflict because I'm calling am directly instead of using am as that is an alias to appman: 

![image](https://github.com/ivan-hc/AM/assets/36420837/39a7d096-63f8-4320-951c-30d0b80a88f3)

**Comment by ivan-hc** [comment]
have you got a file named "appman" in /opt/am? This means that you've used the option `--user` or `appman` previously

**Comment by Samueru-sama** [comment]
> have you got a file named "appman" in /opt/am? This means that you've used the option `--user` or `appman` previously

No, I have appman in `$HOME/.local/opt` and had the am alias to that location. I installed am the normal way to test this bug that was reported.

I got rid of the alias and now I was able to update AM to 6.5, however it still doesn't make the .desktop for qmasterpassword lol 

![image](https://github.com/ivan-hc/AM/assets/36420837/3e884cbe-1dfd-46ee-9b05-49352aec4ed5)

More importantly if I try to manually extract the .desktop file from the appimage, doing a `./qMasterPassword-x86_64-qt5.AppImage --appimage-extract usr/share/applications/*.desktop` fails for some reason, even though it should not fail as there is indeed a .desktop file in there wtf.

**Comment by Samueru-sama** [comment]
> have you got a file named "appman" in /opt/am? This means that you've used the option `--user` or `appman` previously

FOUND THE PROBLEM: 

It is a difference between zsh and bash lol: 

![image](https://github.com/ivan-hc/AM/assets/36420837/f60dcd25-4f2f-48bf-8784-c1317a4f740f)

Oh no, this explains a lot of cases you may have seen of people with missing .desktop files.

**Comment by ivan-hc** [comment]
I'm not familiar with ZSH at all. What should we do to made it compatible?

**Comment by Samueru-sama** [comment]
> I'm not familiar with ZSH at all. What should we do to made it compatible?

It needs to have the `" "` in the path: 

![image](https://github.com/ivan-hc/AM/assets/36420837/7d87d062-b7b4-49d1-addb-cbac9b1d143b)

But either way, this should not happen because the script have a sheabang that tell which shell to use. And as far as I know none of the scripts ever call zsh.

**Comment by ivan-hc** [comment]
just seen that all my scripts have `#!/usr/bin/sh` instead of `#!/usr/bin/env bash`, as reported by https://unix.stackexchange.com/questions/38172/are-all-bash-scripts-compatible-with-zsh

**Comment by Samueru-sama** [comment]
> just seen that all my scripts have `#!/usr/bin/sh` instead of `#!/usr/bin/env bash`, as reported by https://unix.stackexchange.com/questions/38172/are-all-bash-scripts-compatible-with-zsh

In my case sh is the dash shell, and iirc debian uses dash as the sh. And you also want to use sh as much as possible because it is faster lol, however sh lacks some features and needs to be used carefully. For example my android-tools AppRun needs to use bash because I'm using features that only work in bash like filtering `$@` paste certain field. 

Don't do anything yet, I will test modifying the qmasterpassword script with "" in the path to see if it installs the bloody .desktop.

**Comment by ivan-hc** [comment]
Maybe a function in APP-MANAGER to let ZSH users run scripts in BASH instead.... may this be possible?

**Comment by Samueru-sama** [comment]
> Maybe a function in APP-MANAGER to let ZSH users run scripts in BASH instead.... may this be possible?

I tried installing qmasterpassword from bash and it still failed. I downloaded the qmasterpassword script and tried to run it directly with am, still failed. 

Changed the shebang to `#!/bin/bash` and it still failed.

Now I'm testing adding `" "` to every path in the script but it is not working either. 

However now I tested changing the entire script to the way I changed the gpgfrontend script, and I got something: 

```
# LAUNCHER & ICON
app=$(echo $APP | cut -c -3)
cd /opt/$APP
./$APP --appimage-extract *.desktop 1>/dev/null && mv squashfs-root/*.desktop ./$APP.desktop 2>/dev/null
./$APP --appimage-extract share/applications/*.desktop 1>/dev/null && mv squashfs-root/share/applications/*.desktop ./$APP.desktop 2>/dev/null
./$APP --appimage-extract usr/share/applications/*.desktop 1>/dev/null && mv squashfs-root/usr/share/applications/*.desktop ./$APP.desktop 2>/dev/null
sed -i "s/Exec=[^ ]*/Exec=$APP/g" ./$APP.desktop
CHANGEICON=$(cat ./$APP.desktop | grep Icon= | head -1)
sed -i "s#$CHANGEICON#Icon=/opt/$APP/icons/$APP#g" ./$APP.desktop
```

Now the script installs a broken `AM-qmasterpassword.desktop` symlink in `/usr/local/share/applications`. I'm getting something. I know why the symlink is broken, it is because the appimage contains a symlink in the top level of squashfs-root instead of a actual file. 

Now I'm trying only this: 
```
# LAUNCHER & ICON
app=$(echo $APP | cut -c -3)
cd /opt/$APP
./$APP --appimage-extract "usr/share/applications/*.desktop" && mv ./squashfs-root/usr/share/applications/*.desktop ./$APP.desktop 2>/dev/null
sed -i "s/Exec=[^ ]*/Exec=$APP/g" ./$APP.desktop
CHANGEICON=$(cat ./$APP.desktop | grep Icon= | head -1)
sed -i "s#$CHANGEICON#Icon=/opt/$APP/icons/$APP#g" ./$APP.desktop
```

And I am adding some by putting sleeps in between each step to see what the script is doing, for some reason it fails to do the `mv ./squashfs-root/usr/share/applications/* ./$APP.desktop 2>/dev/null` even though there is a file that can be moved wtf.

**Comment by Samueru-sama** [comment]
Ok I have no fucking idea how this can even happen, I set the script to do an `ls` after doing the --appimage-extract. And this is what happens: 

```
AM-updater
icons
qmasterpassword
remove
version
```

This is why the mv fails and I can't get the desktop entry installed.

Yes there is no squashfs-root dir, even though I can perfectly see it from my file manager when the script is running, now I'm worried if my pc is dying lol.

**Comment by ivan-hc** [comment]
squashfs-root directory is removed after the installation

**Comment by Samueru-sama** [comment]
> squashfs-root directory is removed after the installation

Not in that part of the script, notice the sleep 30 and the "mv failed" which when I hit that part of the script. (also you can still see the directory in thunar).

**Comment by ivan-hc** [comment]
I've EndeavourOS installed in Virtualbox and I've changed the default shell to ZSH and rebooted. Then I've installed qmasterpassword using AM and everything works.

**Comment by ivan-hc** [comment]
@Samueru-sama according with Shellcheck:
```
[Line 78:](javascript:setPosition(78, 27))
./$APP --appimage-extract *.desktop 1>/dev/null
                          ^-- [SC2035](https://www.shellcheck.net/wiki/SC2035) (info): Use ./*glob* or -- *glob* so names with dashes won't become options.
```
so, try to replace
```
./$APP --appimage-extract *.desktop 1>/dev/null
```
with
```
./$APP --appimage-extract ./*.desktop 1>/dev/null
```
and let me know if this works.

**Comment by Samueru-sama** [comment]
> I've EndeavourOS installed in Virtualbox and I've changed the default shell to ZSH and rebooted. Then I've installed qmasterpassword using AM and everything works.

I just gave up, I use appman anyway, but I installed AM again to record this vid: 

I'm really baffled that the issue is that the script can't pickup the `squashfs-root` directory, like it is not there from the script point of view for some reason.

https://streamable.com/qgv0ol

**Comment by Samueru-sama** [comment]
> @Samueru-sama according with Shellcheck:
> 
> ```
> [Line 78:](javascript:setPosition(78, 27))
> ./$APP --appimage-extract *.desktop 1>/dev/null
>                           ^-- [SC2035](https://www.shellcheck.net/wiki/SC2035) (info): Use ./*glob* or -- *glob* so names with dashes won't become options.
> ```
> 
> so, try to replace
> 
> ```
> ./$APP --appimage-extract *.desktop 1>/dev/null
> ```
> 
> with
> 
> ```
> ./$APP --appimage-extract ./*.desktop 1>/dev/null
> ```
> 
> and let me know if this works.

`./$APP --appimage-extract *.desktop 1>/dev/null`

In this appimage the .desktop file is actually located in `usr/share/applications/`, squashfs-root/*.desktop instead is a symlink to the .desktop file. 

Pay very close attention to this video Ivan: https://streamable.com/sp9qyh

notice how the `squashfs-root` doesn't show in the `ls -a`, crazy.

**Comment by ivan-hc** [comment]
OK, I've found the issue!

The [install.am](https://github.com/ivan-hc/AM/blob/main/modules/install.am) module has this function to patch the installation script in case the system has RO filesystems (maybe because the host uses BTRFS or its an immutable distro):
```
if [[ $(grep "[[:space:]]ro[[:space:],]" /proc/mounts) ]]; then
	$SUDOCOMMAND mkdir -p /usr/local/share/applications
	sed -i 's#/usr/share/applications#/usr/local/share/applications#g' ./$arg
fi
_install_common_patch
```
so the issue is here
```
sed -i 's#/usr/share/applications#/usr/local/share/applications#g' ./$arg
```

**Comment by ivan-hc** [comment]
@Samueru-sama try to edit the install.am module, change the line
```
sed -i 's#/usr/share/applications#/usr/local/share/applications#g' ./$arg
```
with
```
sed -i 's# /usr/share/applications# /usr/local/share/applications#g' ./$arg
```
ie with spaces before /usr/share/applications

**Comment by Samueru-sama** [comment]
> OK, I've found the issue!
> 
> The [install.am](https://github.com/ivan-hc/AM/blob/main/modules/install.am) module has this function to patch the installation script in case the system has RO filesystems (maybe because the host uses BTRFS or its an immutable distro):
> 
> ```
> if [[ $(grep "[[:space:]]ro[[:space:],]" /proc/mounts) ]]; then
> 	$SUDOCOMMAND mkdir -p /usr/local/share/applications
> 	sed -i 's#/usr/share/applications#/usr/local/share/applications#g' ./$arg
> fi
> _install_common_patch
> ```
> 
> so the issue is here
> 
> ```
> sed -i 's#/usr/share/applications#/usr/local/share/applications#g' ./$arg
> ```

Didn't work, I do use btrfs btw.

**Comment by ivan-hc** [comment]
I've just changed the module in /dev

https://github.com/ivan-hc/AM/blob/dev/modules/install.am

replace it with the new one

**Comment by ivan-hc** [comment]
@Samueru-sama the issue was that the command
```
mv squashfs-root/usr/share/applications/*.desktop ./$APP.desktop
```
was replaced with
```
mv squashfs-root/usr/local/share/applications/*.desktop ./$APP.desktop
```
this is why it was not moved, it can't find the .desktop file, no squashfs-root/usr/local exists

**Comment by ivan-hc** [comment]
And this is the reason because it works on AppMan instead:
```
sed -i "s# /usr/share/applications# $DATADIR/applications#g" ./$arg
```
there is a space before /usr/share/applications

**Comment by Samueru-sama** [comment]
> I've just changed the module in /dev
> 
> https://github.com/ivan-hc/AM/blob/dev/modules/install.am
> 
> replace it with the new one

wtf, it works! HOW?

Notice the stuff I added to the script. notice that I even added a `mkdir ./squashfs-root` for good measure, and ls -a still can't find that directory.

![image](https://github.com/ivan-hc/AM/assets/36420837/0f2c1634-9353-4fe5-9c55-7544315049ae)

Notice the `|| echo "mv failed"` wasn't printed in the terminal, but still the `squashfs-root` dir is hidden somehow, what crazy magic is this?

But this time, it did install the .desktop file in `/usr/local/share/applications`.

**Comment by Samueru-sama** [comment]
Btw @ivan-hc even though the issue is fixed somehow, I still have the broken icons in the applications that get installed by AM: 

tested gpgfrontend, qmasterpassword and es-de, none have the icon in my `rofi` menu.  This only happens with AM, it doesn't happen with appman. 

However the icons are not broken in my file manager if I navigate to the .desktop files: 

![image](https://github.com/ivan-hc/AM/assets/36420837/a875a66d-0e8a-488a-acd9-a7445066df88)

May be an issue with `rofi` but that is weird that it only happens with AM.

**Comment by ivan-hc** [comment]
I don't know what "rofi" is

However, this may be an issue related to XDG: who is the responsible of data from .desktop files (including the path to icons)?

**Comment by Samueru-sama** [comment]
> I don't know what "rofi" is

😐

I just reported to issue to rofi, turns out the issue is that if the `Icon=` part in the desktop entry contains a path `/opt` rofi refuses to show the icon. 

If I edit the desktop entry with a path to a random icon in `$HOME` then rofi has no trouble showing it, I thought that it was an issue with having the desktop entries in /usr/local/share/applications but nope, it is a very weird issue.
