### ISSUE TITLE
Add AppMan AppImage (AM)

### ISSUE THREAD

**Issue by zen0bit** [ivan-hc/AM#460]
Should be done like first app...

And I already said my thoughts about am/appman...

**Comment by zen0bit** [comment]
So bundled with all dependencies and released as *.AppImage

**Comment by Samueru-sama** [comment]
AppImages are for portabled apps but AM and AppMan are not really portable as they need to be on a certain location and their modules need updating.

So the appimage would be just an installer and shortcut for am/appman at most.

With that said, a one click installer would be great, pkexec can be used in the case of AM as it needs root permission to install.

Also both am/appman need very little dependencies, like bash, core utils, wget, zsync and thats about it. Because even xdg-user-dirs is now optional (the readme hasnt been updated about that)

**Comment by zen0bit** [comment]
wget zsync

**Comment by ivan-hc** [comment]
@zen0bit this is a movie I've already seen... and done. I don't remember if it was a 2.x or 3.x release.... but an AppImage of AppMan has already be done. So if I refuse to bundle it today (and expecially today, with all these PR with/without issues) there is a reason. To be a script is better, it is always updatable and without critical bugs because of this. Having system dependences is not a problem at this point. If you're afraid about the total replacemente of "wget" for "wget2", we can always find a solution. The other day, @Samueru-sama has uploaded the portable version of "gum", why we can't do the same with "wget" and something else? All will change will be the INSTALL script for "AM", while AppMan is already portable. "zsync" instead is an optional dependence, and the installation process will advice you if it is needed, and like we have done with "gum", we can do the same with "zsync", I did the same with "libfuse2", also installable using AM/AppMan.

**Comment by zen0bit** [comment]
> Questions?

:+1: 
But why we can have it? And work nicely?

> it is always updatable and without critical bugs because of this
And in AppImage not? I thouth that exactly this AM do no?

**Comment by ivan-hc** [comment]
> 👍 But why we can have it? And work nicely?

because its useless, I've already created it in the past. This is included in my answer above.

> > it is always updatable and without critical bugs because of this
> 
> And in AppImage not? I thouth that exactly this AM do no?

AppImages are more difficult to be updated, while scripts are more dinamic and flexible to manage... for example, if someone decided to remove the ".am" extensions from the main CLI because wanted to made AM look better, and without thinking that, maybe, they are there for some reasons (maybe a random module... clean.am, needs to have a list of modules not to be removed so it searches the keywords in there.... ), that asshole of the upstream developer cannot patch it in real time if it is an AppImage. However, the contributor does not care about it, him only want to made the CLI more beautifize.

PS: Any reference is purely coincidental, no animals were mistreated during the writing of this answer... especially crickets, like the one some developers use as avatars.

**Comment by zen0bit** [comment]
> PS: Any reference is purely coincidental, no animals were mistreated during the writing of this answer... especially crickets, like the one some developers use as avatars.

Not developer (Leave my crickets)

> Whats criterium from calling app AppImage except extension?

**Comment by ivan-hc** [comment]
Create the appdir, place the script, bundle as an appimage, wait the GH action.... its a waste of seconds/minutes! And because of someone I wont name, I know well that these minutes are strictly important to prevent bugs and issues un the PC of other people around the world using this app. But the fault is not of the contributor, its mine, and I wont have panic because I have to bundle the AppImage always and always and always due to someone.

**Comment by ivan-hc** [comment]
Found, it was AppMan 4.0 https://github.com/ivan-hc/AppMan/releases/tag/4.0.0

**Comment by ivan-hc** [comment]
I close this as not planned. I'm sure this time.

**Comment by Samueru-sama** [comment]
Hey I can add wget to the list of packages, but how do we wget wget 🤔🤔🤔

**Comment by zen0bit** [comment]
Question is:
 How we can get wget without wget

**Comment by ivan-hc** [comment]
The question is... you two do too many questions: why?

**Comment by ivan-hc** [comment]
Nope

**Comment by ivan-hc** [comment]
I don't say that its difficult to bundle. On the contrary, it is really easy. Only I wont to maintain it. It is a CLI continuosly in evolution, with PRs, feature requests and bug fixes. Its a waste of time and a mess.

Also, AppMan is auto-updatable and the download link redirects to the APP-MANAGER script... it will be continuosly replaced, again and again... so its useless to create the AppImage of it.

Also, imagine you want to install it with AM, how could it be updated if installed in a RO $PATH?

We should not talk about this anymore. My english is not perfect, but I've not wrote in arabian or japanese, for example. I think we all talk in english here, nope?

I confirm my choice, if you want to maintain an AppImage of it, do it by yourself... but its useless and insecure.

I've talked.

**Comment by Samueru-sama** [comment]
Too late: https://github.com/Samueru-sama/AppMan-AppImage

@zen0bit I also bundled gum and your apptui PR. Give it a test.


>I confirm my choice, if you want to maintain an AppImage of it, do it by yourself... but its useless and insecure.

It's ok, I'm doing this to experiment.

I guess I can add a function that checks that compares the version of the appimage when the github release and warns that it is out of date. 

Which btw Ivan, I think we neeed to add some automatic warning that appman/am is outdated, because I have already seen 2 people that had very outdated versions of AM/AppMan and didn't notice. One was even a full year behind on updates lol.

**Comment by ivan-hc** [comment]
> I guess I can add a function that compares the version of the appimage when the github release and warns that it is out of date.

and this is useless, you will see in the future

> Which btw Ivan, I think we neeed to add some automatic warning that appman/am is outdated, because I have already seen 2 people that had very outdated versions of AM/AppMan and didn't notice. One was even a full year behind on updates lol.

this is a big issue, I've thinked the same... but how we can tell this to people that are using obsolete things?
