### ISSUE TITLE
Why do you guys push drastic changes without fully considering the impact?

### ISSUE THREAD

**Issue by nazdridoy** [ivan-hc/AM#506]
its really frustrating to see a perfectly working program break upon update. 

"is not in the sudoers file. Permission denied." Why? and why do i have to leave everything on hand and try to debug an absolutely unnecessary issue while i could study for my exam.? why do you guys push breaking update without beta testing? this sort of drastic changes makes people second thought to adopt random github project  to their work flow.

i'm sorry, its really unprofessional!

**Comment by ivan-hc** [comment]
This change was because we had a pir of issues with people using AM on systems with many accounts.

You can re-install it to use it with the same privileges of other system admins, as I suggested in the message.

**Comment by ivan-hc** [comment]
Also see https://github.com/ivan-hc/AM/issues/496

**Comment by nazdridoy** [comment]
@ivan-hc please marge #507

**Comment by nazdridoy** [comment]
> This change was because we had a pair of issues with people using AM on systems with many accounts.
> 
> You can re-install it to use it with the same privileges of other system admins, as I suggested in the message.

beta is important if you don't want to ruin user experience

**Comment by ivan-hc** [comment]
I've done the tests with @Samueru-sama

**Comment by nazdridoy** [comment]
> I've done the tests with @Samueru-sama

not enough as you guys are probably using only debian based distro.

**Comment by ivan-hc** [comment]
@Samueru-sama uses Arch Linux and sometime "doas" instead of "sudo"

**Comment by nazdridoy** [comment]
at least consult with others or beta test before pushing major update

**Comment by nazdridoy** [comment]
> @Samueru-sama uses Arch Linux and sometime "doas" instead of "sudo"
 he is probably doesn't use wheel (default in arch)

**Comment by ivan-hc** [comment]
@nazdridoy you are right, but the issue here is that to solve the issues we are two of us on a widely used project. Its quite difficult to keep the rythm

**Comment by nazdridoy** [comment]
wheel is not used enough???

**Comment by ivan-hc** [comment]
> wheel is not used enough???

I'm talking about AM

**Comment by nazdridoy** [comment]
thats why you NEED to be a bit slow to add new features.... we can't keep up with you.... its counterproductive..

**Comment by nazdridoy** [comment]
now i have to fix every instance of Sudu group add wheel....

**Comment by ivan-hc** [comment]
however, now AM does not work for me

**Comment by ivan-hc** [comment]
solved

**Comment by Samueru-sama** [comment]
>why do you guys push breaking update without beta testing?

There was 💀

>he is probably doesn't use wheel (default in arch)

I did notice that [here](https://github.com/ivan-hc/AM/pull/492#issuecomment-2078486355) and [here](https://github.com/ivan-hc/AM/pull/497#issuecomment-2078627816)

I also asked about the wheel group before [here](https://github.com/ivan-hc/AM/pull/492#issuecomment-2078249222)

But Ivan used the root group, I didn't think it was a big deal since the user could be added to the group by the installer. (I actually suggested to make an am group for this like other applications do that they make their own group).

My original idea was to make am and all the directories under /opt be owned by root and required sudo to modify those applications. Ivan didn't like that idea because it meant that you would need sudo to update the applications, to which I suggested a sudoers rule that would let the `AM-updater` run without password, but none of this got added in the end. 😅

>thats why you NEED to be a bit slow to add new features

This wasn't a feature, it was a fix for [#466](https://github.com/ivan-hc/AM/issues/466) and [#491](https://github.com/ivan-hc/AM/issues/491)

**Comment by ivan-hc** [comment]
honestly all this fiddling with permissions... it was something I didn't even want to do. I already liked AM like that, up until version 6.6.2

**Comment by ivan-hc** [comment]
@Samueru-sama I'm tempted to downgrade, again

this feature is causing too many problems that weren't there before

**Comment by Samueru-sama** [comment]
>Seems like at least you have noticed and somewhat understand the issues that may be caused by these fixes. I'm wondering why you haven't stopped him from pushing it to the public before all things were ironed out?

Because after adding the user to the root group in INSTALL script everything worked on my end. 

>a fix which causes new issues is not a fix. i do appreciate you trying to help fix these issues, but do believe changing permission of things especially root permission is something that everyone should be careful about.

>I do like your idea to add a new group to manage these... Maybe create a PR, and we can review it. I will personally try to convince @ivan-hc if your implementation looks feasible and does not become a point of failure."

Had it been done like I originally wanted, the only thing that would have changed is that AM would have asked for the sudo password to update. And to fix that you would just need to add a single sudoers rule, which AM could do that as well. 

I still think that having directories in /opt be owned by the user is not ideal. And if I am not mistaken, these recent changes make `/opt/am` change ownership between the users that are updating it. 

>I'm tempted to downgrade, again

Go ahead.

**Comment by nazdridoy** [comment]
and PLEASE @ivan-hc DO NOT PUSH MAJOR UPDATE WITHOUT TESTING FOR ATLEAST A WEEK OR ASK OTHER CONTRIBUTORS FOR CODE REVIEW BEFORE MERGING!!

**Comment by ivan-hc** [comment]
@nazdridoy I can assure you that this is a feature that I have never seen the need for, to which I could easily apply patches without distorting all the permissions, as I have always done. You can't imagine how many times I was reluctant to accept change and instead got carried away by the constant requests. I am truly sorry and mortified by what happened. Sorry again.

As for the others, I was fine with version 6.6.2, and now, in the last 15 hours, we've turned around the computers of who knows how many other people.

Thanks to everyone who pushed me to do this crazy shit. Thank you all. Really.

@Samueru-sama Thanks for cleaning up all the installation scripts, it's a change I'll keep.

For the rest, after everything we have said and done, the time wasted... I'm really, really pissed off right now! CAZZO!

**Comment by Samueru-sama** [comment]
> @Samueru-sama Thanks for cleaning up all the installation scripts, it's a change I'll keep.

The `$CACHEDIR` changes can still be applied later on, it was the changes to permissions and ownership that are the problem. 

I specially made those '$CACHEDIR' changes because when am finally becomes owned by root (Which I think at this point you know that is the only solution for the multi user issues) the regular user could still launch am without needing sudo.

**Comment by ivan-hc** [comment]
> > @Samueru-sama Thanks for cleaning up all the installation scripts, it's a change I'll keep.
> 
> The `$CACHEDIR` changes can still be applied later on, it was the changes to permissions, groups and ownership that are the problem.
> 
> I specially made those '$CACHEDIR' changes because when am finally becomes owned by root (Which I think at this point you know that is the only solution for the multi user issues) the regular user could still launch am without needing sudo.

OK, you can do it. After that, I have to restyle tha APP-MANAGER to a form tha I can understand.

**Comment by ivan-hc** [comment]
@Samueru-sama actually... let me start first, I need to clean up some messes with functions and variables. Then I'll tag you when the time comes.

**Comment by horothesun** [comment]
Hi all! I just started experiencing the same "is not in the sudoers file. Permission denied." error upon update on Linux Mint.

What's the suggested way to fix that?
P.S.: if possible, I'd prefer not having to uninstall `am` with all the `am`-managed AppImages in order to fix the issue.

Many thanks :pray:

**Comment by Samueru-sama** [comment]
> Hi all! I just started experiencing the same "is not in the sudoers file. Permission denied." error upon update on Linux Mint.
> 
> What's the suggested way to fix that? P.S.: if possible, I'd prefer not having to uninstall `am` with all the `am`-managed AppImages in order to fix the issue.
> 
> Many thanks 🙏

`sudo /opt/am/remove` and `wget https://raw.githubusercontent.com/ivan-hc/AM/main/INSTALL && chmod a+x ./INSTALL && sudo ./INSTALL`
