### ISSUE TITLE
etcher from am don work. 

### ISSUE THREAD

**Issue by musicfunfan** [ivan-hc/AM#555]
When i install and use Balena Etcher from am. I get an error when i try to flash a pen drive. But when i use the appimage from the official site. The application works fine. On "am" i am on 1.19.16. The version that is official available on the site is 1.18.11.

My question is how is this possible? Did am get the appimage from unstable branch or something like that ?
And if so ... 

How can i set it up so i get only the stable versions of the appimages ?

**Comment by ivan-hc** [comment]
yes, many packages hosted on github are taken fron the more recent release, ant it may be an alpha, beta, RC or the latest stable. I did this choice because more often the developers are abandoning the AppImage format or they don't made them available in the "latest" release.

So the installation scripts now points to https://github.com/balena-io/etcher/releases/tag/v1.19.16 instead of https://github.com/balena-io/etcher/releases/latest

To solve, remove etcher
```
am -R etcher
```
and install it using the flag "--latest"
```
am -i --force-latest etcher
```
this way, you will always use and update the latest stable build.

**Comment by ivan-hc** [comment]
You can reach the same result using the last commit (above)

Run the command `am -s` to syncronize and download the latest modules (the one responsible of the updates is update.am) containing the option "--force-latest" as a standalone one.

If you use the command
```
am --force-latest etcher
```
it will "update" (or to use the correct world, "downgrade") etcher to the latest version.

This issue is also explained on the README, at https://github.com/ivan-hc/AM?tab=readme-ov-file#the-script-points-to-releases-instead-of-downloading-the-latest-stable

I had to update the module, since the installation scripts now are using "curl" and "jq" to check the URLs on api.github.com

**Comment by ivan-hc** [comment]
also updated the module install.am containing "--force-latest" as a suboption

https://github.com/ivan-hc/AM/commit/25bc3832da3ced2176b0730c02dcbe9696de9b90

if I had not this feedback I was not aware of this bug. Thank you.

**Comment by musicfunfan** [comment]
I run ``am -s`` And then i run ``am --force-latest etcher``. I get this error. `` ERROR: "etcher" does not redirect to a generic "releases"``. Do i need to uninstall and re-install etcher ?

**Comment by musicfunfan** [comment]
Ok I re-install and then run....  ``am --force-latest etcher`` Now is working. 

Thank you.

**Comment by Peppernrino** [comment]
I will have to try this solution... what I ended up doing, was: am --launcher '/home/AppImages/balenaEtcher-1.18.12-x64.AppImage' and it pointed to the copy I had manually downloaded.

The newest working AppImage is 1.8.12, not 1.8.111, as many people believe for some reason.

I have also heard of people running as admin, but I tried sudo etcher, and it seems that am couldn't find this version of etcher. More experimentation is required. :)

**Comment by ivan-hc** [comment]
As expected.... no AppImage release in https://github.com/balena-io/etcher/releases/tag/v2.1.0 (latest)

I'll redirect the main script to the generic release, no more "latest". Sorry, it should be a guarantee to have at least the more recent build, in AM, and "latest" is not a guarantee... as usual.

**Comment by musicfunfan** [comment]
Understood. I am Ventooy user now. I do not use Etcher any more.

**Comment by zen0bit** [comment]
Balena Etche isn't good choice anyway looks like...

[hackernews](https://news.ycombinator.com/item?id=28158519)

I spotted complains on a other places also...

Ventoy 🚀

**Comment by musicfunfan** [comment]
I did not know that. Thanks
