### ISSUE TITLE
Graphical User Interface?

### ISSUE THREAD

**Issue by Thatoo** [ivan-hc/AM#8]
Sounds an awesome project.
Are you planning to make a graphical user interface?

**Comment by Thatoo** [comment]
I'll check on pkg2appimage to see if I can be of any help.
Otherwise, how can we make a GUI? What tool could help?

**Comment by DLopezJr** [comment]
@ivan-hc Do you know python? Enough people know it, so should be able to find some help. 

I would suggest looking into tkinter or PySide.
- https://docs.python.org/3/library/tkinter.html
- https://wiki.qt.io/Qt_for_Python

**Comment by ivan-hc** [comment]
> Do you know python?
@DLopezJr honestly, I don't like it much. I was thinking about something based on QT or GTK. However any client can use both AM an AppMan as an inbuilt engine, so any GUI is OK for me.

**Comment by DLopezJr** [comment]
If you want to use QT, maybe checkout QT Designer. [[LINK](https://doc.qt.io/qt-6/qtdesigner-manual.html)]

It's a drag and drop designer for QT. It can give you the output code in C++ or Python.

**Comment by zen0bit** [comment]
I will think about it...

But nothing to fancy, I am not programmer so maybe in yad...

**Comment by ivan-hc** [comment]
yad or zenity are OK for me

**Comment by zen0bit** [comment]
I have some experience with yad...
[Distrohopper](https://github.com/oSoWoSo/DistroHopper)

**Comment by ivan-hc** [comment]
maybe this would be a fronted, using the new option --user of AM allows users to use AM the same way you use AppMan, so users of AM can decide to switch AM to a non-privileged use

**Comment by zen0bit** [comment]
I will start with TUI frontend maybe...

**Comment by MauricioLucas** [comment]
I believe that YAD is the most elegant front-end for all types of scripts in the unix world.
This is a fork of Zenit that displays GTK+ dialogs and will return to user input. Allows you to present information and prompt the user for information, from all types of shell scripts.

The code can be assembled to offer the test version facilities with YAD without interfering with the current "AM" code as it would only trigger the commands that are already displayed in graphical mode.

Some links that will help you realize its potential:

[Website with best examples: yad-guide.ingk.se/](https://sourceforge.net/p/yad-dialog/wiki/browse_pages/url)
[Official Link: github.com/v1cont/yad](https://github.com/v1cont/yad)
[Old Link samples: sourceforge.net/p/yad-dialog/wiki/browse_pages/](https://sourceforge.net/p/yad-dialog/wiki/browse_pages/url)
[Discussion Group: groups.google.com/g/yad-common](https://groups.google.com/g/yad-common)

**Comment by zen0bit** [comment]
Thinking about posibilities...

- [ ] yad [GUI](https://github.com/v1cont/yad)
- [ ] gum [TUI](https://github.com/charmbracelet/gum)
- [ ] easybashgui [TUI/GUI](https://github.com/BashGui/easybashgui)
- [ ] other??

yad don't fully work under wayland yet

**Comment by DLopezJr** [comment]
You can check out tcl/tk (very simple to use) or FLTK (C++ but simple and small).

**Comment by atzufuki** [comment]
I think there might be room for several GUI's for different user groups. For example an integration to Gnome Software would be a no-brainer for Gnome users.

I'm a web dev myself and enthusiastic about pure vanilla web components. Therefore I could work on an Electron based app.

This project isn't too popular, nor AppImages in general. Therefore I'm thinking ahead, like what user group we should prioritize and what kind of design the app should have in terms of marketing. There is now some hype around Steam Deck, SteamOS and gaming on Linux in general. And they are really lacking a reliable way to install non-steam apps. So maybe we should target this area to boost this project? Therefore the Electron app should integrate well with Steam's ecosystem in terms of design and UX.

**Comment by ivan-hc** [comment]
@atzufuki I've actually always thought of Electron as a solution, precisely for all the reasons you explained. Electron offers greater cross-platform compatibility. I've seen that some projects (including Bottles) are starting to move towards that technology specifically to export their projects to multiple different platforms.

Unfortunately I am not good at any type of coding other than SHELL, so I trust in your more expert hands.

**Comment by atzufuki** [comment]
Awesome. I shall look for time to implement a first working version soon.

**Comment by DLopezJr** [comment]
@atzufuki and whoever else works on the electron version,

Is there any chance you can keep it to VanillaJS? Would be easier for future contributors if they didn't need to learn another layer of software (eg. React, Typescript, npm, Vue, etc)

**Comment by atzufuki** [comment]
@DLopezJr Depends on what you consider vanilla exactly. Every code base is different and there is no universal way of doing things, hence we need some way to teach the basics specific to this project to new developers anyway. It's possible to achieve really maintainable and really unmaintainable code bases regardless the technology stack, although a bigger stack usually means the latter.

To me these frameworks like React and Vue bring nothing and they solve nothing. They just complicate things with magic and just like you mentioned, there will be a higher learning curve for any developer. I think there isn't a single problem they solve, which couldn't be solved via native API's. Nowadays it's even possible to implement reusable components using native [custom elements API](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements), which was one of the biggest marketing point for React back in the day.

So, I can promise to go as vanilla as possible but I will also promise maintainability. To be able to provide that maintainability, there will be some decisions made on top of vanilla. Again, depending on what you consider vanilla.

NPM is pretty much a must at this point, I don't think there is any other way. I would use TypeScript, since the benefit is so much bigger than the learning curve, especially for new developers who might not know TypeScript beforehand.

**Comment by Thatoo** [comment]
A good alternative to Electron is https://tauri.app/ in case you plan to check for alternatives.

**Comment by atzufuki** [comment]
@Thatoo Tauri is great but it uses WebKit on Linux and personally I've had a hard time working with WebKit on Linux. Maybe it's just me but WebKit feels still quite unpolished while encountering very weird problems even with the most basic tasks. It's funny because at the same time I'm a fan of WebKit. :D

Well, it should be easy to port from Electron to Tauri in the future if WebKit matures up ja Tauri becomes the next industry standard. At least if you know Rust.

**Comment by ivan-hc** [comment]
This is a dream that become true!

To get the icons should not be a problem.

If you're able to get each line as a group of items, for example by replacing ":" with a new line, we should be able to have something like this:


| ![avidemux](https://github.com/ivan-hc/AM-Application-Manager/assets/88724353/39487576-bb1c-4d97-9f3d-69689135dc89)   |![kdenlive](https://github.com/ivan-hc/AM-Application-Manager/assets/88724353/b9b33382-d70b-47e9-b6a8-f3c165642faa) |
| --- | --- |
| **avidemux** | **kdenlive** |
| Multiplatform Video Editor.  |   A powerful Video Editor provided by KDE. |
| [install](https://raw.githubusercontent.com/ivan-hc/AM-Application-Manager/main/programs/x86_64/avidemux) | [install](https://raw.githubusercontent.com/ivan-hc/AM-Application-Manager/main/programs/x86_64/kdenlive) |

To generate that kind of [list](https://portable-linux-apps.github.io/apps.html) (and the [home page](https://portable-linux-apps.github.io/)) I use a script on my PC that you can get from here:
https://github.com/ivan-hc/AM-Application-Manager/blob/main/tools/am2pla-site

Due to github API limits that allow you to connect and download stuff via CLI only some dozens of times per hour, to download and generate the icons would be a problem if done manually, but we can implement something like this in github actions and start downloading an archive with all the icons we need, each of them in a separate directory into a Tar archive, and all we must do is to upload it. All new addition istead would be done manually.

I want to start a test for this.

**Comment by ivan-hc** [comment]
I started adding icons on https://portable-linux-apps.github.io/apps.html

For now I have uploaded 1/3 of all the icons (641 vs the 1839 to add)

**Comment by atzufuki** [comment]
> To generate that kind of [list](https://portable-linux-apps.github.io/apps.html) (and the [home page](https://portable-linux-apps.github.io/)) I use a script on my PC that you can get from here:
https://github.com/ivan-hc/AM-Application-Manager/blob/main/tools/am2pla-site

Of course you have a script for that. :) Maybe create a script to provide a JSON version, so it would be easy to parse?

**Comment by ivan-hc** [comment]
If you give me the scheme of the json file you need I can try to do something like am2pla-site in SHELL

**Comment by atzufuki** [comment]
> If you give me the scheme of the json file you need I can try to do something like am2pla-site in SHELL

I'd go with this if some day we need some additional metadata or something, like version idk.
```jsonc
{
  // "version": "1",
  "apps": [
    {
      "packageName": "0ad",
      "description": "FOSS historical Real Time Strategy (RTS) game of ancient warfare...",
      "icon": "https://portable-linux-apps.github.io/icons/0ad.png"
    },
    {
      "packageName": "0ad-latest",
      "description": "Real Time Strategy game of ancient warfare (development branch)...",
      "icon": "https://portable-linux-apps.github.io/icons/0ad-latest.png"
    },
    {
      "packageName": "3d-puzzles",
      "description": "3D-Puzzles are Rubik, Dogic and Dogic12...",
      "icon": "https://portable-linux-apps.github.io/icons/3d-puzzles.png"
    }
  ]
}
```
or just 
```json
[
  {
    "packageName": "0ad",
    "description": "FOSS historical Real Time Strategy (RTS) game of ancient warfare...",
    "icon": "https://portable-linux-apps.github.io/icons/0ad.png"
  },
  {
    "packageName": "0ad-latest",
    "description": "Real Time Strategy game of ancient warfare (development branch)...",
    "icon": "https://portable-linux-apps.github.io/icons/0ad-latest.png"
  },
  {
    "packageName": "3d-puzzles",
    "description": "3D-Puzzles are Rubik, Dogic and Dogic12...",
    "icon": "https://portable-linux-apps.github.io/icons/3d-puzzles.png"
  }
]
```

**Comment by ivan-hc** [comment]
@atzufuki  sorry for the delay, I was a bit busy.

This is based on am2pla-site, made it executable and wait until the apps.json fie is ready:

```
#!/usr/bin/env bash

# THIS SCRIPT IS NEEDED TO GENBRATE A JSON FILE OF ALL APPLICATIONS WITH EASE
cd $(xdg-user-dir DESKTOP)
AMREPO="https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main"
arch="x86_64"
echo "" >> args
wget -q $AMREPO/programs/$arch-apps && echo -e "$(cat ./$arch-apps | awk -v FS="(◆ | : )" '{print $2}')" >> args
echo STOP >> args
ARGS=$(sed '1d' ./args)
echo "[" >> apps.json
# THIS IS THE WORKFLOW
for arg in $ARGS; do
	for var in $arg; do
	if [ $arg == STOP ]; then
		break
	else
	case $arg in
	am) ;;
	appman) ;;
	*) for var in $arg;
		do
		description=$(cat $arch-apps | grep "◆ $arg :" | sed 's/"//g' | sed 's/^.*: //')
		echo -e '  {\n    "packageName": "'$arg'",\n    "description": "'$description'..",\n    "icon": "https://portable-linux-apps.github.io/icons/'$arg'.png"\n  },' >> apps.json
		sleep 0.005
		done;;
	esac
	fi
done
done
sed -i '$s/,$//' apps.json
echo -e "]" >> apps.json
rm ./args ./$arch-apps
```

This is the file I've generated with this script:

[apps.json](https://github.com/ivan-hc/AM-Application-Manager/files/13592720/apps.json)

**Comment by atzufuki** [comment]
Delay? I just woke up. :D 

Thanks for the json. Anyway, I wouldn't mangle the description, just put it in as is. It's the UI's job to render it the way it fits the screen in a list view and show rest of the description some other way.

**Comment by ivan-hc** [comment]
> I wouldn't mangle the description, just put it in as is

I have tried to check the validity of the json file and I had issues with lines containing double "", for example:

```
ivan@debian:~$ am -q '"'

 SEARCH RESULTS FOR """ IN THE LIST OF AVAILABLE PROGRAMS:

◆ adb : Android Debug Bridge (installer for "platform-tools").
◆ ark : Archiving tool for .zip/.tar/.rar and more (installs "kdeutils").
◆ armagetronad : Multiplayer game in 3d that emulates the movie "Tron".
◆ bomber : Arcade spaceship game (installs "kdegames").
◆ bovo : Five in a row game from (installs "kdegames").
◆ colorstatic-bash : CLI to generate a random colorful "Static"/"Matrix".
◆ elementary-code : AppImage version of Elementary OS "Code" by Maksym Titenko.
◆ fastboot : Tool to flash Android devices (installer for "platform-tools").
◆ filelight : View disk usage information (installs "kdeutils").
◆ granatier : Bomberman clone (installs "kdegames").
◆ kapman : Pac-Man clone (installs "kdegames").
◆ katomic : Edu. game based around molecular geometry (installs "kdegames").
◆ kblackbox : A game of hide and seek (installs "kdegames").
◆ kblocks : Classic Tetris / falling blocks game (installs "kdegames").
◆ kbounce : Fill the field game (installs "kdegames").
◆ kbreakout : Destroy bricks without losing the ball (installs "kdegames").
◆ kcalc : Scientific Calculator (installs "kdeutils").
◆ kcharselect : Character Selector (installs "kdeutils").
◆ kdf : View Disk Usage (installs "kdeutils").
◆ kdiamond : Diamond game (installs "kdegames").
◆ kfourinline : 4 in row game (installs "kdegames").
◆ kgoldrunner : A game with a runner and gold (installs "kdegames").
◆ kgpg : A GnuPG frontend (installs "kdeutils").
◆ kigo : Go strategic board game for two players (installs "kdegames").
◆ killbots : Port of the classic console game Robots (installs "kdegames").
◆ kiriki : A dice game (installs "kdegames").
◆ kjumpingcube : A game of dices on a board (installs "kdegames").
◆ klickety : Color matching like SameGame (installs "kdegames").
◆ klines : Inspired by well known game of Color Lines (installs "kdegames").
◆ kmahjongg : Mahjongg game (installs "kdegames").
◆ kmines : Classic mine game (installs "kdegames").
◆ knavalbattle : Battle Ship game (installs "kdegames").
◆ knetwalk : Net constructing game (installs "kdegames").
◆ knights : Chess interface for the KDE Platform (installs "kdegames").
◆ kolf : Mini Golf game (installs "kdegames").
◆ kollision : Dodge red balls in the field (installs "kdegames").
◆ konquest : Game of planets (installs "kdegames").
◆ kpat : Klondike, Spider, Free Cell and other Solitaire (installs "kdegames").
◆ kreversi : Reversi game (installs "kdegames").
◆ kshisen : A game similar to Mahjongg (installs "kdegames").
◆ ksirk : A strategy board game (installs "kdegames").
◆ ksnakeduel : A snake race game (installs "kdegames").
◆ kspaceduel : Battleship with satellites in the space (installs "kdegames").
◆ ksquares : Win with most number of completed squares (installs "kdegames").
◆ ksudoku : Sudoku game (installs "kdegames").
◆ ktimer : Countdown Launcher (installs "kdeutils").
◆ ktuberling : Simple Mr. Potato game for children (installs "kdegames").
◆ kubrick : A logic game based on Rubik's Cube (installs "kdegames").
◆ kwalletmanager5 : Wallet management tool (installs "kdeutils").
◆ lskat : Fun and engaging card game for two players (installs "kdegames").
◆ npm : Package manager for Node.js (installer for "node").
◆ onnx2daq : Wrapper of NNAPI ("DNNLibrary" is for "daquexian's NNAPI libs).
◆ palapeli : Jigsaw puzzle game (installs "kdegames").
◆ picmi : Single player logic-based puzzle game (installs "kdegames").
◆ stackandconquer : A challenging tower conquest board game "Mixtour" inspired.
◆ sweeper : System Cleaner (installs "kdeutils").
```
this is why I have removed the "" via `sed`

**Comment by atzufuki** [comment]
Double quotes should get escaped like this `\"`. The best way to provide a JSON would be using a JSON serializer, like `JSON.stringify` in JavaScript and `json.dumps` in Python. Don't know if there is a proper equivalent for bash, but I found this with a quick search: https://jqlang.github.io/jq/.

**Comment by DLopezJr** [comment]
- ```jq``` has become the most common way to handle JSON in most shell scripts. 
- Another option that I like is [miller](https://miller.readthedocs.io/en/6.9.0/). 
- Python is indeed installed by most desktop systems and you can implement it in a shell script using a HEREDOC.

Regarding quoting, a trick I've learned is if nested quoting gets messy, it's easier to read if you use hex values. It's a lot cleaner.

```
$ printf '\x27\n'

$ awk 'BEGIN { print("\x27"); }'
'
$ echo -e '\x27'
'

**Comment by ivan-hc** [comment]
I've just finished to upload almost all the icons (where they were available):
- directory https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/tree/main/icons
- final result https://portable-linux-apps.github.io/apps.html

@atzufuki if you need something else, let me know

**Comment by ivan-hc** [comment]
> Yes, can you publish the json as well like this maybe: https://portable-linux-apps.github.io/apps.json

done!

**Comment by ivan-hc** [comment]
Today I worked on merging the AM and AppMan codes: they are now identical, apart from the first lines in the header (before the options).

As suggested by @zen0bit , the two scripts can practically be one and work as a single program.

The idea came to me after reading that @DLopezJr  intends to clean up the code again by adding functions. I recently learned to write about them, in fact I have already applied a large amount of them in the [ArchImage](https://github.com/ivan-hc/ArchImage) project.

Speaking of marketing, I also renewed the brand that you will find in AM and AppMan with the option `-h`, here it is, I hope you like it:
```
               _____                    _____ 
              /\    \                  /\    \		   A	   A
             /::\    \                /::\____\		    P	    M
            /::::\    \              /::::|   |		     P
           /::::::\    \            /:::::|   |		      M	      &
          /:::/\:::\    \          /::::::|   |		       A
         /:::/__\:::\    \        /:::/|::|   |		        N
        /::::\   \:::\    \      /:::/ |::|   |
       /::::::\   \:::\    \    /:::/  |::|___|______
      /:::/\:::\   \:::\    \  /:::/   |::::::::\    \
     /:::/  \:::\   \:::\____\/:::/    |:::::::::\____\
     \::/    \:::\  /:::/    /\::/    / ~~~~~/:::/    /
      \/____/ \:::\/:::/    /  \/____/      /:::/    /
               \::::::/    /               /:::/    /
                \::::/    /               /:::/    /
                /:::/    /               /:::/    /╔╦╗╔═╗╔╗╔┌─┐┌─┐┌─┐┬─┐
               /:::/    /               /:::/    / ║║║╠═╣║║║├─┤│ ┬├┤ ├┬┘
              /:::/    /               /:::/    /  ╩ ╩╩ ╩╝╚╝┴ ┴└─┘└─┘┴└─
             /:::/    /╔═╗╔═╗┬  ┬┌─┐┌─┐┌┬┐┬┌─┐┌┐┌
             \::/    / ╠═╝╠═╝│  ││  ├─┤ │ ││ ││││
              \/____/  ╩  ╩  ┴─┘┴└─┘┴ ┴ ┴ ┴└─┘┘└┘	by Ivan Alex HC
							
  >> 𝘋𝘢𝘵𝘢𝘣𝘢𝘴𝘦 & 𝘴𝘰𝘭𝘶𝘵𝘪𝘰𝘯𝘴 𝘧𝘰𝘳 𝘢𝘭𝘭 𝘈𝘱𝘱𝘐𝘮𝘢𝘨𝘦𝘴 𝘢𝘯𝘥 𝘱𝘰𝘳𝘵𝘢𝘣𝘭𝘦 𝘢𝘱𝘱𝘴 𝘧𝘰𝘳 𝘎𝘕𝘜/𝘓𝘪𝘯𝘶𝘹 << 
```

PS: should I let the urls at the footer of the "help" or under the brand.

**Comment by ivan-hc** [comment]
PPS: I've not merget completelly the two projects because each of them can be installed differently. However, I'll still do some tests before releasing the version 5 of AM.

**Comment by ivan-hc** [comment]
4:30 a.m. here in Italy, and I've just finished to merge AM and AppMan. Now their code is the same, so you have no more to choose between the two.

Just one detail made them different:
- as always, AM must be installed in /opt/am with symlink to /usr/local/bin/am to manage apps at system level, so if you want to install both apps at system level and localy, use for the latter the option --user;
- being the code the same, you can put APP-MANAGER wherever you want, like AppMan, but if you don't rename the file as "appman" it will not work with bash-completion or wont be updated with the name you want.

So let's keep this standard: "am" as a symlink in /usr/local/bin for /opt/am/APP-MANAGER and "appman" as "appman", always, otherwise what I try to make simpler will be more... confusing! xD

**Comment by DLopezJr** [comment]
@atzufuki I have made the discussion thread for GUI discussions regarding an Electron design. [[LINK](https://github.com/ivan-hc/AM-Application-Manager/discussions/95)]

@ivan-hc Very glad to hear you merged AM and AppMan. That will makes this codebase a lot easier to comprehend. Great to hear you're familiar with functions now! I've made a discussion thread for refactoring the codebase so we can discuss things out and stay in sync. [[LINK](https://github.com/ivan-hc/AM-Application-Manager/discussions/96)]

**Comment by ivan-hc** [comment]
In the latest version 5.6.3 I have removed `less -E` from the `install` option. I don't know if this would be helpful for a UI. I know that using `less` may be an obstacle sometime, expecially if you want to see the output.

Also I have restored the old name of the repository, from "AM-Application-Manager" to "AM", as in the earlier days of this project, when I started to wrote it. I think it is easier now to remember and search (for example by googleing "am appimage").

On https://portable-linux-apps.github.io I have added all the icons for all 1871 items listed.

To resume other improvements since first half december, a better `-f` option interface, support for custom repositories, you can add a github personal APIkey, a `test` option to instll your own script created with `-t`... right now I don't remember other things I've done.

Is there anything I should do now to easier your work? I hope this project hasn't tired you. I'm doing everything I can to improve it.

**Comment by ivan-hc** [comment]
For those who missed the latest updates, thanks to @nazdridoy  suggestions, AM is no longer a monolithic script, but a modular one: 27 scripts each dedicated to an option or two (see https://github.com/ivan-hc/AM/tree/main/modules), all managed by [APP-MANAGER](https://github.com/ivan-hc/AM/blob/main/APP-MANAGER). Update to version 6 of AM or AppMan to see the changes.

**Comment by ivan-hc** [comment]
Update: today we exceeded 1900 installation scripts for x86_64 (right now there are 1919).

Is there any news?

@atzufuki

**Comment by atzufuki** [comment]
> Is there any news?
> 
> @atzufuki

Not at the moment. I have been busy at work and with my own business. But I now activated in the [discussion](https://github.com/ivan-hc/AM/discussions/95) and will continue the conversation there.

**Comment by zen0bit** [comment]
TUI #175

**Comment by zen0bit** [comment]
It would be nice to separate all UI calls in AM to default UI module. so can be easily interchangeable.
And all potential GUI and TUI could be just modules ❤️

**Comment by zen0bit** [comment]
> > Thinking about posibilities...
> > 
> > * [ ]   yad [GUI](https://github.com/v1cont/yad)
> > * [x]   gum [TUI](https://github.com/charmbracelet/gum) - Work In Progress - [apptui](https://github.com/oSoWoSo/AM/tree/apptui)
> > * [ ]   easybashgui [TUI/GUI](https://github.com/BashGui/easybashgui)
> > * [ ]   other??
> > 
> > yad don't fully work under wayland yet
> 
> EasybashGui have some updates, so will try next..

Looks like easybashgui is best option

Easy Bash Gui shortened as EBG, is a Posix compliant Bash functions library that aims to give unified GUI functions using frontends for dialogs boxeds (from the user's point of view are frontends but from the EGB side are backends)
Backends environments GUI

EBG implements different dialogs boxes! You don't have to worry about what environment you are running the script in, as EasyBashGUI will handle this transparently, based on the availability of the backends (frontends).

Console mode:
- dialog
- gum (will be implemented)
Graphical mode:
- yad
- gtkdialog
- kdialog
- zenity
- xdialog

**Comment by Heus-Sueh** [comment]
my recommendation for which GUI to use, I think [Toga](https://toga.readthedocs.io/en/stable/tutorial/tutorial-0.html#write-the-app) or [QT](https://www.pythonguis.com/tutorials/pyside-creating-your-first-window/) are better candidates than tkinter or fltk, these libraries are simple and light, but they are not modern and nowadays not many people are interested in learning them as there are better alternatives.

**Comment by DLopezJr** [comment]
@Heus-Sueh Excited to see your pull request using Toga or Qt :)

**Comment by Heus-Sueh** [comment]
> @Heus-Sueh Excited to see your pull request using Toga or Qt :)

sorry man, I was just recommending it, I won't be able to implement it because I'm new to programming

**Comment by ivan-hc** [comment]
@Heus-Sueh don't worry

**Comment by Thatoo** [comment]
I mention AM to nitrux development team.
Nitrux being the distribution relying the most on appimages, and about UX/UI design they are really good. They could be very helpful on this topic.

https://github.com/orgs/Nitrux/discussions/143

**Comment by zen0bit** [comment]
Godot engine? 🤔

**Comment by DLopezJr** [comment]
@zen0bit Unless you find a dedicated Godot or two developer that's a risk that is not worth taking.

**Comment by zen0bit** [comment]
I just need to figured out how to properly run commands with arguments. Everything else looks like a peace of cake

**Comment by zen0bit** [comment]
> @zen0bit Unless you find a dedicated Godot or two developer that's a risk that is not worth taking.

Any knowledge gained will satisfy me, and open new opportunities...

**Comment by ivan-hc** [comment]
hey GUIys :rofl: would you like to see what I've found on the antix forum? An ui for AppMan

https://www.antixforum.com/forums/topic/appman-a-package-manager-for-appimage-and-binary-files/

download from here https://www.antixforum.com/wp-content/uploads/2023/06/appman-gui-5.1.zip

this is genial in my opinion

**Comment by joedefen** [comment]
Hey all interested in a GUI interface (like I was).  Since a GUI seems to be long-term project, I wrote a quickie, python-curses based layer atop appman called `vappman` (i.e., visual appman).  I have other other apps that use same foundation, and so it was literally a few hours to develop and test the features that I wanted for myself.

I think it provides much of the potential value of a GUI app at (obviously) a fraction of the development cost (and maintenance).  Thus, it might have some wider interest as a replacement for the GUI or, at least, a temporary project.

- See [vappman · PyPI](https://pypi.org/project/vappman/) for a description and a screen capture.
- And I made a VERY amateurish video introduction, too, at [vappman video intro](https://drive.google.com/file/d/1WKp_0ZP2A6l9Fg6jymzABCXU3WtnNyOp/view?usp=sharing).

I'm happy with `vappman` as a personal tool.   But if there is wider interest and it is within my development budget and interests, then make suggestions.

Cheers.

**Comment by ivan-hc** [comment]
This issue has been open for two years, "AM" still hasn't received the attention it deserves, and AppImages are still considered second-class software packages.

It makes me think that my intent to enhance AppImages failed, apparently only me cared.

I'm seriously considering archiving "AM".

It no longer makes sense to keep this issue open.

**Comment by ivan-hc** [comment]
@joedefen thank you anyway, yours is still a good solution.

The issue here is that none else care about AM or AppMan.

It's what I noticed, since people prefer to care more about Flatpake and Snap. "May Appimages never have their own package manager! NO! They would be competing, and that's not nice! Let's let Snap and Flatpak monopolize software management!"

This is what people and the mainstream keep think. And this is what pisses me off the more

**Comment by zen0bit** [comment]
If we want stick with mainstream, we are on windows right?
Don't give up, and keep your excellent work going please...
(It's still same song.
Leave win
Leave ubuntu
Leave systemD
Leave flatpak
Leave snaps)
:heart:

**Comment by Samueru-sama** [comment]
> creating my own appimages and wrappers to further close the gap was a bitch

You can always request apps to be added to the database. And if it doesn't exist as appimage I might make it.

appman made me stop using the Aur which is great, because even with btrfs snapshots setup, I often ran into issues that broke the entire system lol.

**Comment by joedefen** [comment]
> appman made me stop using the Aur which is great

Well, while on Arch, I thought AUR was a dumpster fire, and I used it as a last resort (preferring flatpaks, tarballs, etc.).  But, yes, appman (had I known at the time) would have been my goto.

> You can always request apps to be added to the database.

I have six outlier apps (i.e., crudely, self-managed apps not in repos, appman, flatpak, etc).  The most widely useful, I think, would be "ventoy-gui".   BTW, ventoy is available w appman, but it fails ("polkit-agent-helper-1: error response to PolicyKit daemon: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie; ==== AUTHENTICATION FAILED ===="); I've not looked into it at all .. I just uninstall appimages that don't work (and this is not the first).

I'm no expert on vappman/am documentation (so pardon my ignorance), but I don't where I'd request app, where to report an appimage problem, how to share an appimage (if I ever got one working), and how to know if somebody is already working on the appimage (or declared it impractical).   Anyhow, like AUR, for appman to succeed, I think, you have to harness the power of many volunteers to support it.
---
As one idea, each time I do an "about" (or maybe an "install", too), you might provide (1) the link to the appimage's support page, and  (2) a link to a page with "how to contribute" (in terms of requesting apps, signing up to implement an app, checking the status of the app (how many requests, whether in progress, whether declare impossible, etc).

---
And to ease its use, you might make, say, appman + vappman (my python tool to make it excusable) a PyPi project, so that appman is installed with "pipx appman" rather the off-putting CLI magic.   Frankly, I'd chuck AM (not self-descriptive) and make appman do both (install in common areas or home area based on whether running as root or not ... similar to pip).

---
I don't know whether the project will get its due attention and popularity, but it seems like to me that some of the preconditions are:
* harnessing the power of a bunch of weekend warriors (for appimage development and support)
* making it more noob / casual user friendly

Anyhow, just some brainstorming ... don't take me too seriously ... rebuttal not needed.

**Comment by Samueru-sama** [comment]
>BTW, ventoy is available w appman, but it fails ("polkit-agent-helper-1: error response to PolicyKit daemon: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie; ==== AUTHENTICATION FAILED ===="

I've just tested ventoy, it works here. The only way I can get that error you have is if I kill my polkit agent.

>I'm no expert on vappman/am documentation (so pardon my ignorance), but I don't where I'd request app, where to report an appimage problem, how to share an appimage (if I ever got one working), and how to know if somebody is already working on the appimage (or declared it impractical). Anyhow, like AUR, for appman to succeed, I think, you have to harness the power of many volunteers to support it.

You would need to open an issue to request apps, there used to be one issue for all app requests but Ivan changed it to the user opening one instead, if you have a working appimage template that would be thru a PR adding said script to the application database.

AM/AppMan has the `-t` flag that lets you make the appimage template, usually when the app is an appimage from github all you have to do is give it the github repo link and that's it, no further modification is needed in the script. 

>Frankly, I'd chuck AM (not self-descriptive) and make appman do both (install in common areas or home area based on whether running as root or not ... similar to pip).

I think that appman should be what's installed by default instead, but that's just me, I actually mentioned this to Ivan yesterday that the INSTALL script should ask and explain which one to use.

**Comment by joedefen** [comment]
> I've just tested ventoy, it works here.

My duh.  It did not register.  I'm a i3wm noob and it has no agent and it never struck me before.  I despise the polkit prompts when I have password-less sudo set up; when prompted, I just insert "sudo" in the offensive .desktop; thus, and circumventing the agent.   And, yes, ventoy-gui works with sudo.  But, I shoulda done this with polkit rule, in retrospect, obviously (I think that'll do it).   Sorry to bother.

**Comment by Samueru-sama** [comment]
> > I've just tested ventoy, it works here.
> 
> My duh. It did not register. I'm a i3wm noob and it has no agent and it never struck me before. I despise the polkit prompts when I have password-less sudo set up; when prompted, I just insert "sudo" in the offensive .desktop; thus, and circumventing the agent. And, yes, ventoy-gui works with sudo. But, I shoulda done this with polkit rule, in retrospect, obviously (I think that'll do it). Sorry to bother.

I'm also a [i3wm user](https://github.com/Samueru-sama/dotfiles/blob/main/Local/config/i3/config), I actually have [i3 as an appimage ](https://github.com/Samueru-sama/i3-AppImage) lol
