### ISSUE TITLE
could you add the latest stable release

### ISSUE THREAD

**Issue by Ranko-Saotome** [ivan-hc/AM#825]
https://download.sqlitebrowser.org/DB.Browser.for.SQLite-v3.13.0-x86.64.AppImage

**Comment by ivan-hc** [comment]
```
am -i --force-latest sqlitebrowser
```
or if you have already installed it
```
am --force-latest sqlitebrowser
```
and it will downgrade to the stable release.

Almost all installation scripts will install from the more recent release available on a github repository because it is not always a guarantee of continuity. Sometime the upstream developer prefer to add one different format or prevents oploading that release, may it be an AppImage, may it be a generic package for Linux.

Its not my fault, i had bad experience by redirecting everything to "latest"

See https://github.com/ivan-hc/AM?tab=readme-ov-file#the-script-points-to-releases-instead-of-downloading-the-latest-stable

**Comment by Ranko-Saotome** [comment]
thanks
