### ISSUE TITLE
Suggestions for conty/appimage

### ISSUE THREAD

**Issue by garbagescow** [ivan-hc/AM#852]
Hello:
Some Suggestions for conty appimage:
Davinci Resolve & vmware workstation player.  Maybe even qemu with virt-manager

**Comment by ivan-hc** [comment]
VM solutions are not easy to bundle like this, since they must have as less host dependences as possible.

Also, I bundled the two I have more experience with, VirtualBox (KVM) and Gnome Boxes:
- VirtualBox KVM is a modded version that does not have "vboxdrv" dependence, the AppImage still needs to run an internal option "as root" to let you use USB devices;
- Gnome Boxes needs the libvirt driver installed in /var, not to crash. The AppImage also lack of USB support.

So, as you can see, I have already difficult with solutions I already tried to port in AppImage format.

With the ones you said I have no experience.

I suggest to fork one of my repo and follow the instructions to learn more on how this kind of bundle works.
