### ISSUE TITLE
Fantasia archive is still getting an older version 

### ISSUE THREAD

**Issue by Ranko-Saotome** [ivan-hc/AM#882]
https://github.com/Elvanos/fantasia-archive-v1/releases/tag/v0.1.14a is the latest

**Comment by ivan-hc** [comment]
I have seen that they have another repo https://github.com/Elvanos/fantasia-archive

Are you sure that the one you linked is not an Alpha? If not, have they moved to a new repo?

**Comment by Ranko-Saotome** [comment]
If I understand it correctly the main repository has been converted to version 2 and it hasn't had any releases yet so they moved version 1 to its own repository

**Comment by ivan-hc** [comment]
its a strange behaviour, if they want to dedicate a new repo to each new release, the fix may be complicated in the future, for each new release

**Comment by Ranko-Saotome** [comment]
Version 2 once it comes out we'll be the main think of version one as legacy version 2 will be a complete rewrite 

Basically version one is the end of life

**Comment by ivan-hc** [comment]
to fix this issue is simple, I can replace
```
https://api.github.com/repos/Elvanos/fantasia-archive/releases
```
with
```
https://api.github.com/repos/Elvanos/fantasia-archive-v1/releases
```
only that I have no guarantees on their furter changes in the repo. I'd like to keep the script updated with the last version.

In the meantime, if you have still it installed with AM:
- open the AM-updater script
- replace the original URL (is in the line starting with "version=") with the one above
- save
- run `am -u fantasia-archive`

Maybe they will change the name of the repository back to "fantasia-archive", you should ask them before.

**Comment by Ranko-Saotome** [comment]
I was just letting you know but I'm currently got it worked around I'm currently got a launcher made using appman

**Comment by ivan-hc** [comment]
Since github repositories can redirect on an alternative name is tue one we use is unused, I hope that the day they will rename the repo as fantasia-archive again they will no more cause troubles like this one.

I updated the script with the changes needed (see commit above), keep me updated in case they change again. Thanks for reporting.
