### ISSUE TITLE
move bash_completion file to $XDG_CONFIG_HOME"/bash-completion

### ISSUE THREAD

**Issue by prodigalshadow** [ivan-hc/AM#903]
Hi, first of all, thank you for your hard work! As the title says, would it be possible to move the bash_completion file to $XDG_CONFIG_HOME"/bash-completion/bash_completion to make it compliant with XDG Base Directory Specification? Thanks!

**Comment by ivan-hc** [comment]
Hi, my cooperator had issues while trying to use it via ZSH, this is why we left it in $HOME. Anyway I also want to find a way not to add dotfiles in the $HOME like this.

**Comment by ivan-hc** [comment]
I just tried to replace
```
# BASH AND ZSH COMPLETION
completion_file="${ZDOTDIR:-$HOME}"/.bash_completion
```
with
```
# BASH AND ZSH COMPLETION
mkdir -p "${ZDOTDIR:-$XDG_CONFIG_HOME}/bash-completion"
completion_file="${ZDOTDIR:-$XDG_CONFIG_HOME}/bash-completion/bash_completion"
```
but completion does not work for me (I use BASH)

**Comment by ivan-hc** [comment]
Also using ~/.local/share does not work
```
mkdir -p "$DATADIR/bash-completion"
completion_file="${ZDOTDIR:-$DATADIR}/bash-completion/completions"
```

**Comment by ivan-hc** [comment]
I'm testing with both file names bash_completion and completions (as specified ad https://github.com/scop/bash-completion )

**Comment by ivan-hc** [comment]
@prodigalshadow it seems that the right location is ~/.local/share, not ~/.config

and I also was wrong, "completions" is a directory, not a file

I just tested this in both ~/.config and ~/.local/share, this is the working one
```
mkdir -p "$DATADIR/bash-completion/completions"
completion_file="${ZDOTDIR:-$DATADIR}/bash-completion/completions/am"
```

the file may be named "am", for both AM and AppMan

**Comment by ivan-hc** [comment]
I moved the change to the "dev" branch, its enough to run `am --devmode-enable && am -s` to test it, same for "AppMan".

I need to test this in ZSH

**Comment by ivan-hc** [comment]
I've done a test right now with both ~/.bash_completion and the new file, for the first one i changed "list" with a random text file and then closed/reopened the terminal: it has priority over the new file.

Since it still redirects to "list" its OK, but what if someone has still a previous version of AppMan?

**Comment by ivan-hc** [comment]
@prodigalshadow I must wait @Samueru-sama that uses ZSH to confirm merge.

**Comment by prodigalshadow** [comment]
no worries man, take your time.

**Comment by Samueru-sama** [comment]
@prodigalshadow sorry for the late showing up, I just didn't have electricity for 24h lol.

This issue is something I noticed but couldn't get to work, note that the issue was that when using bash for some reason the completion file wasn't working when placed on `$XDG_DATA_HOME/bash-completion`.

I never had issue getting it to work on zsh, since the zshrc gets patched to point to the path of the completion file.

However it seems Ivan managed to get it to work with bash now so that's great.

I use zsh since it lets me set `$ZDOTDIR` which lets me move all shell related dotfiles to a location of my choosing.
