### ISSUE TITLE
Change the way icons are handled to automatically follow icon theme.

### ISSUE THREAD

**Issue by LostWarriorr** [ivan-hc/AM#922]
in the .desktop file of applications downloaded the Icon path points directly to the downloaded Icon as follows:
`Icon=/home/$USER/Applications/libreoffice/icons/libreoffice-base`

However if  the icons downloaded were instead put into `/home/$USER/.local/share/icons` we would be able to point to the icon directly:
`Icon=libreoffice-base`

Then the system will automatically theme it according to the selected icon theme if applicable. If it is unable to find a theme it will automatically default to the one downloaded by AppMan that are placed into `/home/$USER/.local/share/icons` 

However in XFCE I believe a `/home/$USER/.xsessionrc` file with the following contents is needed for this to work:

`case "$PATH" in`
`   *$HOME/.local/share/icons/) ;;`
`   *) PATH=$HOME/.local/share/icons/:"$PATH"`
`esac`
`export PATH`

I'm not sure what other DEs need that file but I know KDE doesn't.

**Comment by ivan-hc** [comment]
what if I write an option to remove the path from the launcher instead?

**Comment by ivan-hc** [comment]
for example
```
appman icon-theme $APP
```
to remove the path for one or more apps, or
```
appman icon-theme --all
```
to remove the path for all installed apps?

**Comment by ivan-hc** [comment]
if you want to test it for a preview, enable support to developer mode and update
```
appman --devmode-enable
appman -s
```
to exit developer mode, use
```
appman --devmode-disable
```

@Samueru-sama @LostWarriorr  this is what I changed https://github.com/ivan-hc/AM/commit/50c52e6b735b0f963f176d0fb0458800103f1cde

if it is OK, I'll add also an help message to the option -h and on the README.

Of course, `icon-theme` is a temporary name, I can change it if you want.

**Comment by ivan-hc** [comment]
I have tested this with
```
appman -i lxtask anydesk chromium gimp
```
and "gimp" is the only one I have installed also as system package via APT.

I performed tests on one app first, then on two, and finally using the --all flag, and since GIMP is already installed system wide, the AppImage uses the same icon because listed among themes.

**Comment by ivan-hc** [comment]
PS: run `appman -s` two times, I just fixed a bug that prevented me to download modules from the "dev" branch https://github.com/ivan-hc/AM/commit/e65659cb4f8370efed27184856c8c2197fcfd3df

**Comment by LostWarriorr** [comment]
But why add yet another command to Appman when this can be be handled by the DE and done automatically? Further more not everyone is going to know what icons their theme supports so they will either have to go looking to find out or just run the command to see what happens. If they do run the command and they find their icon theme doesn't have support the icon then they will have to manually go and add the now missing icon back.

Adding ANOTHER command to revert the icon back to what was downloaded by Appman after removing it with the command you just suggested in case their icon theme doesn't support the icon or they change themes is not a good solution for the end user.

I believe that exporting the icons into one of the following directories is the best choice for the end user:
`/home/$USER/.icons/hicolor/scalable/apps/`
`/home/$USER/.local/icons/hicolor/scalable/apps/`

`/home/$USER/.icons` Would probably be the most reliable method across different DEs because as I stated in the original post XFCE (and maybe others) need another file to access `/home/$USER/.local/icons/` correctly.

**Comment by ivan-hc** [comment]
All installation scripts are wrote like this and me and my cooperator have already rewrote all of them.

If an option to change the path from the .desktop file is not the solution, it would be a symlink into the $APPSPATH/$APP/icons directory... or manually adding the icon in that directory (without an extension) to made it recognized... or manually changing the icon using an editor like "menulibre".

But as you have said, the point is that the user does not know if the icon from the theme is compatible with the app, well, since you also are a XFCE user and I use it from 2011, you should know that the developers of the DE renamed the icons, like GNOME developers do, using a icon name similar to a website address (org.gnome.alacarte.png, for example).

What if in the new option I proposed I also add the icon in $HOME/.local/share/icons? In this way, if the theme does not support the icon, al least the launcher will roll back to the existing one.

**Comment by LostWarriorr** [comment]
> > What if in the new option I proposed I also add the icon in $HOME/.local/share/icons? In this way, if the theme does not support the icon, al least the launcher will roll back to the existing one.
> 
> I mean, by launching the new option, the .desktop file get rid of the icon path and the icon from the "icons" directory of the app is placed io $HOME/.local/share/icons.
> 
> So the launcher will always have an icon, also if the icon theme does not support it.

Isn't this exactly what I am suggesting?

**Comment by ivan-hc** [comment]
> Isn't this exactly what I am suggesting?

I had read it wrong, I had focused on this

> But why add yet another command to Appman when this can be be handled by the DE and done automatically?

this point distracted me, I thought you didn't like the idea of ​​me adding another option. Sorry.

Please, if you like it, would you suggest a better name for this option? "icon-theme" doesn't give the idea of ​​what could actually be done.

**Comment by LostWarriorr** [comment]
> I thought you didn't like the idea of ​​me adding another option. Sorry.
> 
> Please, if you like it, would you suggest a better name for this option? "icon-theme" doesn't give the idea of ​​what could actually be done.

I don't like the idea of adding a new command just for icons to theme.

Once again if the Desktop Environment can handle it automatically if the icons are located in the positions I listed before why make the user do it manually? A command is not a user friendly option. Especially if the Icon is not a part of the theme then they have a blank Icon they may not know how to fix after running said command.

Flatpaks as an example follow Icon themes just fine automatically. Even on bare bones XFCE with no need to change any sandbox settings or do any extra commands.

**Comment by ivan-hc** [comment]
Since icons are something that my package manager must handtle, I had to rename the icons, also because formerly the earlier versions of AppMan and AM were already able to handle icons in /usr/share/pixmaps, and this was a risk, so I removed this feature.

> I do not like the idea of adding a new command just for icons to theme.

me neather, but you opened the issue and I'm trying to do what is now possible with the current situation, so I started writing this option. Another solution is to re-write all installation scripts again.

> Once again if the Desktop Environment can handle it automatically if the icons are located in the positions I listed before why make the user do it manually?

is the script that creates the icons directory in the app's directory and that extracts/renames it.

If we want to do this automatically during the installation, run the command during the installation, and I can add it as a flag for the option "install".

> A command is not a user friendly option.

AM/AppMan is a command line interface, the day someone take care of made a GUI that uses them as an engine, AM/AppMan will be user friendly

> Especially if the Icon is not a part of the theme then they have a blank Icon they may not know how to fix after running said command.

this is what I'm readi to add with the next commit
```
# ICON THEME CHANGER
function _icon_theme_export_to_datadir() {
	[ -d "$APPSPATH/$arg/icons" ] && mkdir -p "$DATADIR"/icons && rsync -avq "$APPSPATH"/"$arg"/icons/* "$DATADIR"/icons/ \
	&& find "$DATADIR"/icons -type f ! -name "*.*" -exec mv {} {}.png \;
}

function _icon_theme() {
	if [ "$AMCLI" = am ]; then
		$SUDOCMD sed -i "s#Icon=$APPSPATH/$arg/icons/#Icon=#g" /usr/local/share/applications/"$arg"*AM.desktop 2>/dev/null
	else
		sed -i "s#Icon=$APPSPATH/$arg/icons/#Icon=#g" "$DATADIR"/applications/"$arg"*AM.desktop 2>/dev/null
	fi
	_icon_theme_export_to_datadir
}
```

the first function will create the icons directory in $HOME/.local/share if it does not exists, then it will copy the existing icons that are without extension and will add a .png extension to them, to made them used by the DE (I've done a pair of tests, my DE does not recognize icons without an extension).

> Flatpaks as an example follow Icon themes just fine automatically. Even on bare bones XFCE with no need to change any sandbox settings or do any extra commands.

Flatpak, a community-driven package manager and repository... versus AM, a one-man amateur project: who will win?

> > you should know that the developers of the DE renamed the icons, like GNOME developers do, using a icon name similar to a website address (org.gnome.alacarte.png, for example).
> 
> This is for flatpaks to follow system Icon theme as that is how their Icons are named.

This is why I wrote my own icon theme, in the past 15 years: to prevent programs owners overwriting my theme style.

--------------------------

That said, what shoul I do now?

**Comment by ivan-hc** [comment]
In the meantime the new commit is ready https://github.com/ivan-hc/AM/commit/f6ff33b84ae9793762a54208120ddbfb29700417

**Comment by ivan-hc** [comment]
This other commit will not overwrite the existing icons if they exist locally https://github.com/ivan-hc/AM/commit/789974a70a65178d71f79f67941d431cc1d62136

**Comment by ivan-hc** [comment]
@LostWarriorr 

https://github.com/user-attachments/assets/ff2250f2-f5f7-4a06-843d-3da9f6dc33dc

**Comment by ivan-hc** [comment]
I'm testing this on "AM", in my case I require the root password to perform these tests.

**Comment by ivan-hc** [comment]
this is what I mean when I say that icons without extensions are not recognized

https://github.com/user-attachments/assets/99b3563a-cb28-4551-b621-8dbf628951cb

**Comment by ivan-hc** [comment]
And finally, here is how custom themes work, see how I use this chromium icon as an alternative for anydesk by changing the icon theme

https://github.com/user-attachments/assets/8e743d33-e384-49c2-8c52-56c68b6d384f

**Comment by ivan-hc** [comment]
@LostWarriorr I can't do better than this

maybe I should rename the option `icons` or `--icons` or both... as many names you want. Give me a suggestion, if you are still interested.

**Comment by LostWarriorr** [comment]
> (I've done a pair of tests, my DE does not recognize icons without an extension).

> this is what I mean when I say that icons without extensions are not recognized

I do not have this issue. My Icon pack doesn't even have a "keepassxc.png" file however if I were to name it as so in the .desktop file it is still able to find it correctly. Using a theme such as GNOME/Adiwaita/Tango/Breeze it is able to find it without the extension type only if the actual file doesn't have an extension. If I were to add an extension to the .desktop file or the actual image file it would break. 
Although interestingly I have noisetorch with a .png image but the .desktop file does not state so and it functions correctly

> This is why I wrote my own icon theme, in the past 15 years: to prevent programs owners overwriting my theme style.

The org/com sym link icons are only used for the flatpak variants if the application is installed natively it uses the normal naming scheme that the application would normally use. This is to ensure compatibility with all forms of installation. Your own icon theme should not have any need for those com/org icons unless you have an application that does the name scheme by default or you use a flatpak.

> also because formerly the earlier versions of AppMan and AM were already able to handle icons in /usr/share/pixmaps, and this was a risk, so I removed this feature.

> And finally, here is how custom themes work, see how I use this chromium icon as an alternative for anydesk by changing the icon theme

Then by your definition this would mean any icons the user has installed in `/home/$USER/.icons` or KDE's default through their "store" `/home/$USER/.local/share/icons` are a security risk. This would also mean that the current way application Icons are handled by appman are a security risk since someone could just replace the icon in the `$DATADIR/Icon` folder. Meaning I don't even see this as a valid point. 
The only way this would even happen is if you downloaded a shoddy Icon pack that didn't do icons correctly, someone has physical access to your computer and changes them, or you have someone remote into your computer and change them. (but at this point you have bigger problems than a false icon).

**Comment by LostWarriorr** [comment]
> Flatpak, a community-driven package manager and repository... versus AM, a one-man amateur project: who will win?

> AM/AppMan is a command line interface, the day someone take care of made a GUI that uses them as an engine, AM/AppMan will be user friendly


Flatpak by default is used in a CLI and is able to follow system Icon themes. Using the excuse of Appman being a CLI is moot. Most of the work is done my Icon pack maintainers to make sure they symlink icons to their org/com flatpak variants so that they will theme correctly. ex of a flatpak .desktop file:
`Icon=org.keepassxc.KeePassXC`
None of the issues with Icon theming are pushed to the user if two factors are correct (.desktop file setup correctly and Icon pack that has icon with correct name).

If the goal of Appman is to help integrate Appimages into the system easier for the end user then Icon theming should be taken into account and preferably automatically.

**Comment by Samueru-sama** [comment]
>I believe that exporting the icons into one of the following directories is the best choice for the end user:
/home/$USER/.icons/hicolor/scalable/apps/
/home/$USER/.local/icons/hicolor/scalable/apps/

Isn't scalable only for the svg icons? are you sure it works even if they are pngs of different sizes? 

Also I don't like the idea of using ~/.icons because some DEs dont' follow the XDG Base dir specification, we even recently had an issue opened about putting the completion file in the top level of $HOME and moved it to $DATADIR instead.

iirc Ivan even had trouble in xfce4 having apps displaying unless the full path to the symlink in PATH was added in the `.desktop`.

So I don't think this is an easy fix, using the full path guarantees that it will work.

**Comment by ivan-hc** [comment]
@LostWarriorr I've been working on an option to fix this since this morning based on how AM/AppMan works, and I still haven't gotten a response when I show you the progress I'm making with the new option. You keep talking about how Flatpak theming works. Do you want to focus on my work instead? I even posted videos on how the new option works, and you don't tell me anything about it. How can I work like this? You're confusing me. Do you want me to fix the theming problem **my way**, or do you want to keep complaining about how my work compares to others?

**Comment by LostWarriorr** [comment]
> Isn't scalable only for the svg icons? are you sure it works even if they are pngs of different sizes?

I used the directory as an example and figured they were all SVGs since the first ones I looked at were libreoffice and they were. But PNGs do appear to work in the scalable directory as well.



> Also I don't like the idea of using ~/.icons because some DEs dont' follow the XDG Base dir specification, we even recently had an issue opened about putting the completion file in the top level of $HOME and moved it to $DATADIR instead.
> 
> iirc Ivan even had trouble in xfce4 having apps displaying unless the full path to the symlink in PATH was added in the `.desktop`.
> 
> So I don't think this is an easy fix, using the full path guarantees that it will work.

When testing if scalable directory works with PNGs just now the icon themes without a custom icon stopped working when just using "keepassxc" as I used earlier and I had to specify "kepassxc.png" in both the .desktop and image to get it working again. Not sure what is exactly at fault there. But since most custom Icon themes seem to ignore the extension in the .desktop file it is probably fine to leave it with it.

**Comment by LostWarriorr** [comment]
> @LostWarriorr I've been working on an option to fix this since this morning based on how AM/AppMan works, and I still haven't gotten a response when I show you the progress I'm making with the new option.

I can agree that the command works as intended and themes the icon correctly if Applicable but why should it be an extra command to issue when it could be **automatically** done when installing an Appimage?

> You keep talking about how Flatpak theming works. Do you want to focus on my work instead? I even posted videos on how the new option works, and you don't tell me anything about it. How can I work like this?

I could compare Appman to native packages and distrobox if you so wish. Both of which **automatically** setup the .desktop file to follow the system icon theme if applicable.

> You're confusing me. Do you want me to fix the theming problem **my way**, or do you want to keep complaining about how my work compares to others?

Appman isn't in a realm of its own. If no other alternative existed then icon theming correctly would be an after thought. But with distrobox-exports and flatpaks existing it is only fair to compare what those currently offer over Appman. Automatic icon theming by way of how the .desktop file is setup is one of them.

**Comment by Samueru-sama** [comment]
>So I don't think this is an easy fix, using the full path guarantees that it will work.

On second thought, it isn't as hard as I thought, the only issue is that it might break on some DEs, so I think it has to be an option rather than a default behaviour.

it would be something like this: 

`mkdir -p $DATADIR/icons/hicolor/scalable/apps/`
`ln -s $APPSPATH/*/icons/* $DATADIR/icons/hicolor/scalable/apps/`

And when `am -r` is used we clear broken symlinks in `$DATADIR/icons/hicolor/scalable/apps/`

@LostWarriorr can you test the ln -s command? and to remove the path from the existing .desktops to test.

**Comment by LostWarriorr** [comment]
> On second thought, it isn't as hard as I thought, the only issue is that it might break on some DEs, so I think it has to be an option rather than a default behaviour.
> 
> it would be something like this:
> 
> `mkdir -p $DATADIR/icons/hicolor/scalable/apps/` `ln -s $APPSPATH/*/icons/* $DATADIR/icons/hicolor/scalable/apps/`
> 
> And when `am -r` is used we clear broken symlinks in `$DATADIR/icons/hicolor/scalable/apps/`
> 
> @LostWarriorr can you test the ln -s command? remove the path from the existing .desktops to test.

This is basically all I was asking or just have them be put into /.local/icons/ by default.

A symlink does work but for whatever reason the file needs an extension attached to it (.png or .svg) while the Icon= variable in the .desktop file does not.

**Comment by ivan-hc** [comment]
> A symlink does work but for whatever reason the file needs an extension attached to it (.png or .svg) while the Icon= variable in the .desktop file does not.

This is already covered by the new option.

**Comment by ivan-hc** [comment]
> Questo è fondamentalmente tutto ciò che chiedevo o semplicemente inserirli in /.local/icons/ per impostazione predefinita. Penso che l'unico DE su cui potrebbe non funzionare per impostazione predefinita è XFCE [ ... ]

in my video I'm doing the tests on XFCE

**Comment by LostWarriorr** [comment]
> > A symlink does work but for whatever reason the file needs an extension attached to it (.png or .svg) while the Icon= variable in the .desktop file does not.
> 
> This is already covered by the new option.

Yes it is but why not automatically? If not then as Samuel suggested a toggle of some sort for people who aren't sure. Rather then having to run a command everytime you install a new application.

> in my video I'm doing the tests on XFCE

I've had to add this to a .xsessionrc file in /home/$USER/ for noisetorch to be able to grab its own icon from `/home/$USER/.local/share/icons/` so I don't think it would work by default.

```
case "$PATH" in
   *$HOME/.local/share/icons*) ;;
   *) PATH=$HOME/.local/share/icons:"$PATH"
esac
export PATH

```
