### ISSUE TITLE
App requests

### ISSUE THREAD

**Issue by Sush-ruta** [ivan-hc/AM#962]
- [x] [hashSum](https://gitlab.com/posktomten/hashsum/-/wikis/home). [Download link](https://bin.ceicer.com/hashSum/bin/linux/GLIBC2.35/)
- [x] [Fantascene-dynamic-wallpaper](https://github.com/dependon/fantascene-dynamic-wallpaper). [Download link](https://www.fantacy.online/fantascene-dynamic-wallpaper-1.8.4_x86_64.AppImage)
- [x] [KeyCombiner](https://keycombiner.com/desktop/). [Download link](https://keycombiner.com/download/KeyCombiner-0.8.0.AppImage)
- [x] [Lorien](https://github.com/mbrlabs/Lorien).
The `tar.xz` file in the Release section has the following structure:
```
Downloads/Compressed/Lorien_v0.6.0_Linux 
❯ ls
Lorien.pck  Lorien.x86_64
```
- [x] [Pizarra](https://pizarra.categulario.xyz/en/). [Download link](https://pizarra.categulario.xyz/releases/any-linux/)
The `tar.gz` file has the following structure:
```
Downloads/Compressed/build 
❯ ls
CHANGELOG.md  LICENSE  pizarra  pizarra.desktop  pizarra.svg  README.md
```
- [x] [Rebaslight](https://www.rebaslight.com/). [Download link](https://www.rebaslight.com/#download)
- [x] [Kristall](https://kristall.random-projects.net/). [Download link](https://kristall.random-projects.net/download/Kristall-nightly-linux-x86_64.AppImage)

---
- [x] [Firework](https://firework.cloud/). [Download link](https://cdn-firework.com/fw/download/packages/Firework-linux-x32.zip).
This is the folder structure:
```
Downloads/Compressed/Firework is 📦 v4.39.13 via  
❯ ls
crashpad_handler     Firework_start_console.sh  nw_100_percent.pak  resources
credits.html         icudtl.dat                 nw_200_percent.pak  resources.pak
ext                  lib                        package.json        swiftshader
Firework             locales                    package-lock.json   updater.sh
FireworkRun.desktop  node_modules               pages               v8_context_snapshot.bin
```
This is the content of the `.desktop` file:
```
❯ cat FireworkRun.desktop
[Desktop Entry]
Name=Firework Start
Version=1.0
Exec=sh -c "$(dirname %k)/Firework --run-from-dir"
Type=Application
Terminal=false
StartupNotify=false
Encoding=UTF-8
Categories=Office;Network;Utility;WebBrowser
```

**Comment by ivan-hc** [comment]
I only need to fix [hashSum](https://gitlab.com/posktomten/hashsum/-/wikis/home)

![Istantanea_2024-09-25_16-07-09 png](https://github.com/user-attachments/assets/28b84f25-f2b3-4364-982f-f07eec1b9cbb)

**Comment by ivan-hc** [comment]
![Istantanea_2024-09-25_16-09-39 png](https://github.com/user-attachments/assets/032575a4-97cc-413b-93a3-f5927f1b459e)

**Comment by Sush-ruta** [comment]
It took me more time to prepare this issue that it took you to resolve it @ivan-hc

**Comment by ivan-hc** [comment]
it was not an easy task, normally when the apps are hosted on github, the description is taken from the repo. In this case I need to search also the description to understand also what kind of app it is.

Anyway, the big work here was to search from were to search a version number in some cases and what is the best source from where we can download it. For example, the option `-t` has also a partial support for "sourceforge", and "fantascene-dynamic-wallpaper" have the AppImage hosted there. The script will download the AppImage as a file named "download", while the version will be taken from the download URL, that is not "latest", but this
```
$ curl -Ls https://sourceforge.net/p/fantascene-dynamic-wallpaper/activity/feed | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep -i "appimage" | grep -v '%' | head -1
https://sourceforge.net/projects/fantascene-dynamic-wallpaper/files/1.8.6/fantascene-dynamic-wallpaper-1.8.6_x86_64.AppImage/download
```
the "version" cariable containing the above `curl` command and function is created using `am -t` normally. Only AppImages are supported like this... but not all apps hosted on sourceforge have that kind of structure. Most of them, not all.

When we can't determine a download URL as "$version" variable, its enough to determine the version number... then we have to manually edit the script and change the two references of `wget "$version"` with `wget "https://site/to/the/app.AppImage"`, but its better to use not a direct URL but a command that detects it.

Here are some examples of $version variable usage from my last commit that have closed this issue
```
APP=fantascene-dynamic-wallpaper
version=$(curl -Ls https://sourceforge.net/p/fantascene-dynamic-wallpaper/activity/feed | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep -i "appimage" | grep -v '%' | head -1)
wget "$version" || exit 1

APP=pizarra
version=$(echo "https://pizarra.categulario.xyz/releases/any-linux/$(curl -Ls https://pizarra.categulario.xyz/releases/any-linux/ | tr '"><' '\n' | grep -i "tar.gz$" | tail -1)")
wget "$version" || exit 1

APP=kristall
version=$(curl -Ls https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=kristall | grep -i "^pkgv\|^pkgr" | cut -c 8- | tr '\n' '-')
wget "https://kristall.random-projects.net/$(curl -Ls https://kristall.random-projects.net/ | tr '"><' '\n' | grep -i "download.*appimage$" | head -1)" || exit 1

APP=hashsum
version=$(curl -Ls https://bin.ceicer.com/hashSum/bin/linux/ | grep -i "glibc[0-9]" | head -1 | tr '>< ' '\n' | tr ' ' '\n' | grep "^[0-9]" | head -1 | sed 's/-/./g')
wget "https://bin.ceicer.com/hashSum/bin/linux/$(curl -Ls https://bin.ceicer.com/hashSum/bin/linux/ | tr '"/' '\n' | grep -i "glibc[0-9]" | head -1)/hashSum-x86_64.AppImage" || exit 1

APP=firework
version=$(curl -Ls https://firework.cloud/en/changelog | grep -i "linux.*version" | tr '"><*' '\n' | grep "^[0-9]" | sed 's/.$//g')
wget "https://cdn-firework.com/fw/download/packages/Firework-linux-x64.zip" || exit 1
```
do you notice any difference? The first two are the one4s used the most, while the others are ecceptions.

And some apps require extra code, this is the one that scare me the most (because the website can change in any moment):
```
APP=inkscape
version=$(wget -q https://repology.org/project/inkscape/related -O - | grep "version-newest" | head -1 | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}")
wget "$(echo "https://inkscape.org/$(curl -Ls $(echo "https://inkscape.org/release/inkscape-$(curl -Ls https://inkscape.org/ | grep -Po '(?<=class="info")[^"]*' | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}" | head -1)/gnulinux/appimage/dl/") | grep "click here" | grep -o -P '(?<=href=").*(?=">click)')")" || exit 1
```
and sometime I need to add more variables, maybe because releases are many (or maybe because I forgot to update the script), for example "blender" has 4 releases, this is the stable
```
APP=blender
branch=stable
url="https://builder.blender.org/download/daily/archive/"
version=$(curl -Ls "$url" | tr '"' '\n' | grep "^https" | grep -i "tar.xz$" | grep -w -v sha256 | grep "$branch" | head -1)
wget "$version"
```

and for all the above, remember, when `wget` is not downloading `$version, the same command must be added in the AM-updater part of the script, like this, int the AM-updater of inkscape, we replace
```
wget "$version"
```
with
```
wget "$(echo "https://inkscape.org/$(curl -Ls $(echo "https://inkscape.org/release/inkscape-$(curl -Ls https://inkscape.org/ | grep -Po '(?<=class="info")[^"]*' | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}" | head -1)/gnulinux/appimage/dl/") | grep "click here" | grep -o -P '(?<=href=").*(?=">click)')")"
```

I repeat, there are only two references of `wget "$version"` in each installation script. You must care when is the case to replace that two references.
