### ISSUE TITLE
[Package Request] Lutris

### ISSUE THREAD

**Issue by contrarybaton60** [ivan-hc/AM#983]
To help us make adding applications quicker and easier, please try to follow the following two syntaxes.

## If available on other sites
- lutris (lowercase, this will be the command to use)
- https://lutris.net
- https://lutris.net/downloads
- Video Game Preservation Platform

# Important!
The two syntaxes mentioned above are enough for programs that can only be used from the command line.

However, for graphical programs and programs that require integration into the menu, and therefore a launcher, also add the following two pieces of information:
- https://github.com/lutris/lutris/blob/master/share/icons/hicolor/scalable/apps/lutris.svg
- the .desktop* file, you can choose whether...
  - add a URL to the .desktop file, if it exists
https://dpaste.org/Lwag6 (desktop file of .deb version)

--------------------------------------------------

# List of portable applications to add

Lutris

## Notes

Considering Lutris is best used with programs like Wine, it may or may not be a good idea to add it as a dependency.

**Comment by ivan-hc** [comment]
well, from what I've seen and read, it seems not to be so "portable"

![Istantanea_2024-10-04_02-21-31 png](https://github.com/user-attachments/assets/225a0a77-415c-4104-ae92-ec3f4b725a2c)

but I was curious, so I downloaded and tested it

![Istantanea_2024-10-04_02-20-49 png](https://github.com/user-attachments/assets/039f1ca7-55ba-4110-ad4c-766bc108d6df)

and while you said...

> Considering Lutris is best used with programs like Wine, it may or may not be a good idea to add it as a dependency.

...from the message above is clear that "wine" is not the only dependency needed

```
2024-10-04 02:19:55,420: Command 'vulkaninfo' not found on your system
2024-10-04 02:19:55,420: Command 'wine' not found on your system
2024-10-04 02:19:55,420: Command 'fluidsynth' not found on your system
```
this is out of the concept of "portable", this is instead a "portable" app https://github.com/ivan-hc/Steam-appimage

Also, I'm scared by this

```
Warning: You'll need to make sure you have the necessary dependencies for Python 3 (PyGObject3 and PyYAML).

Warning: Tools like Virtualenv or Pyenv are not supported. Please stick to the Python version provided by your OS. PyGObject code requires non Python dependencies to function correctly, it is highly recommended to satisfy those dependencies using your package manager.

Warning: If Lutris isn't installed from your package manager already, some features such as browser integration support will be missing. We recommend you keep the latest release version installed, even if you plan on using the development branch.

Warning: Please do not use setup.py install to install Lutris. It does not fully install lutris, some aspects are handled by the distribution's package manager. Additionally, Python's setuptools do not allow to easily uninstall software installed in such a manner. 
```
It's better if I ask the games/Steam expert.

@Samueru-sama how you see this? Trash or Pass?

**Comment by contrarybaton60** [comment]
I already figured it was a bit of a stretch to add Lutris considering it's best used with your package manager and not on it's own, I'm pretty sure the .deb files provided by them do not have those restrictions the last time I used it.

**Comment by Samueru-sama** [comment]
Lutris would need to be a conty AppImage like the Steam one as it has several dependencies.

I don't use lutris btw.

**Comment by ivan-hc** [comment]
> Lutris would need to be a conty AppImage like the Steam one as it has several dependencies.

that's exactly what i was thinking, but there's a problem, as you say...

> I don't use lutris btw.

Me neither. Steam is largely @Samueru-sama 's work, as he is a user of that program, and I don't even have an account. He is the one who had mods to test it, leading me in the right direction. I provided the base repository and he improved it, so much so that 80% of the work done in that repository is his merit.

On the contrary, for Lutris we do not have users who can personally test that AppImage. It would be easy for me to provide a base, but it is the finishing work that is important (testing games, program compatibility, configurations, lightweighting the package...).

@contrarybaton60 if I provided a base repository, would you be willing to collaborate?

----------------------------------------

PS: to be honest, I was trying to reduce the number of repositories, just to lighten my workload. And working on a new AppImage of a program I know little or nothing about, doesn't help.

**Comment by contrarybaton60** [comment]
> @contrarybaton60 if I provided a base repository, would you be willing to collaborate?

I can try, but I'm not really good with stuff, and due to school I can't really do much anyway... I'm gonna close this.

**Comment by ivan-hc** [comment]
> I can try, but I'm not really good with stuff, and due to school I can't really do much anyway... I'm gonna close this.

ok, let me know

**Comment by Samueru-sama** [comment]
@contrarybaton60 Does this work for you? 

https://github.com/lucasmz1/Lutris_AppImage/releases/tag/0.5.17

**Comment by contrarybaton60** [comment]
https://pasted.drakeerv.com/rYWcFx98

doesn't seem to

**Comment by lucasmz1** [comment]
what os are you using ? I need to know cause I'll make a rundown on it to undertand why the app doesn't spawn.

**Comment by contrarybaton60** [comment]
Linux Mint 22 (based on Ubuntu 24.04, it likely has the same issue on there)

**Comment by ivan-hc** [comment]
@lucasmz1 I'd better add your AppImage to the database, so others can contribute to bug reports.

But I ask you to add the scripts, or the code, or at least the instructions on the README.

Here in AM we have a policy to mark the installation scripts of applications coming from repositories without clear instructions on how they are compiled with a flag, "#spooky", so that during the installation the user is aware that the application is not only unofficial, but "could cause problems". And I know that is not your intention, I think you are a good person.

The idea of ​​marking the scripts of applications of this type was suggested to us in a long discussion with Probonopd, the creator of AppImage. You can see that entire discussion here https://github.com/ivan-hc/AM/issues/818

I will make an exception this time, but I ask you to add the code, or at least a documentation or enough information on your README.

You could ask @Twig6943  to help you, the other day he contacted me again and I finally added your application https://github.com/ivan-hc/AM/issues/1137 

I want to help third-party packagers like you as much as possible to promote AppImage. But we need transparent methods and provide instructions that upstream developers can also consult. The more popular our projects are, the more they could be made official. But we need to provide the code. It's the only way to keep this format alive.

**Comment by lucasmz1** [comment]
Well does anyone know how to fix this icon issue.
I did everything I know.
steps I take
export XDG_DATA_DIRS=/home/lucas/Downloads/squashfs-root/usr/share/:/home/lucas/Downloads/squashfs-root/usr/share/mime && update-mime-database /home/lucas/Downloads/squashfs-root/usr/share/mime/
didn't work
disabled #GDK_PIXBUF_MODULEDIR=$APPDIR/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders
#GDK_PIXBUF_MODULE_FILE=$APPDIR/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
if enabled the app clash in some systems
another way I've copied new icon themes into the appdir didn't work
I've set GTK_THEME=Adwaita-dark
didn't work
any Ideias ? I am all ears!

**Comment by ivan-hc** [comment]
@lucasmz1 I had a similar issue with Handbrake and similar apps, it was enough to add `gdk-pixbuf`, `librsvg` and `libdav` to solve in all other appimages I had with the same issue

**Comment by contrarybaton60** [comment]
> Well does anyone know how to fix this icon issue. I did everything I know. steps I take export XDG_DATA_DIRS=/home/lucas/Downloads/squashfs-root/usr/share/:/home/lucas/Downloads/squashfs-root/usr/share/mime && update-mime-database /home/lucas/Downloads/squashfs-root/usr/share/mime/ didn't work disabled #GDK_PIXBUF_MODULEDIR=$APPDIR/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders #GDK_PIXBUF_MODULE_FILE=$APPDIR/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache if enabled the app clash in some systems another way I've copied new icon themes into the appdir didn't work I've set GTK_THEME=Adwaita-dark didn't work any Ideias ? I am all ears!

I'm pretty sure you can set GTK_THEME to blank so it uses the system theme
