### ISSUE TITLE
Webcamoid

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#984]
To help us make adding AppImages quicker and easier, please try to follow the following two syntaxes.

## If available on Github.com
- name:webcamoid
- repository:https://github.com/webcamoid/webcamoid

# List of AppImages to add
https://www.appimagehub.com/p/2106436 (AppImage package can be found here)

**Comment by ivan-hc** [comment]
Hi, I don't accept appimages from appimagehub.com/pling.com, expecially when [who uploads them](https://www.appimagehub.com/u/zrch-garcia-96) have uploaded other's appimages (including [mine](https://www.appimagehub.com/p/2106184)) without adding the sources.

Anyway, I can still solve this issue in a different and more trustable way (out of the ones proposed by the official developer, here).

Stay tuned.

**Comment by ivan-hc** [comment]
I must go, note that whil I'm writing I started a [workflow](https://github.com/ivan-hc/Database-of-pkg2appimaged-packages/actions/runs/11188938012) run to build an Archimage of this application, I've tested it on my PC, size are 237 MB and its based on the brand new release of 2 days ago and supports Qt6 (the one you linked is one year old and supports Qt5)... also the following URL still does not exists while I'm writing:
- https://github.com/ivan-hc/Database-of-pkg2appimaged-packages/releases/tag/webcamoid

This is the script to build it as an Archimage
- https://github.com/ivan-hc/Database-of-pkg2appimaged-packages/blob/main/webcamoid

And as you can see, it will be published at https://github.com/ivan-hc/Database-of-pkg2appimaged-packages

When it finishes to be compiled (it may take a lot), download it and do some tests. I can't say how much time it take to be compiled. On my PC about 20 minutes.

**Comment by Twig6943** [comment]
@ivan-hc 
![image](https://github.com/user-attachments/assets/c72a976b-108a-414f-bf74-a951168a3f28)

**Comment by Twig6943** [comment]
![image](https://github.com/user-attachments/assets/ef85f9a5-64cc-451d-99e8-255dd303c3b9)

**Comment by ivan-hc** [comment]
remove appimagelauncher, reboot and retry

**Comment by Twig6943** [comment]
removing appimagelauncher-bin got it fixed. do you know why this happens tho? (Also could u package goverlay as an appimage)

**Comment by ivan-hc** [comment]
> @ivan-hc removing appimagelauncher-bin got it fixed. do you know why this happens tho?

you got a message, `Failed to open squashfs image`, and I suppose that you were not able to launch AppImages without AppImageLauncher... this is because AIL is old and unsupported (last stable build was in 2020, last dev edition in 2022). Also, it detects if an AppImage is in the system, and this may prevent other tools (this or also the terminal... I don't know if GeaRlever has the same issie) to handle AppImages.

See https://github.com/ivan-hc/AM#failed-to-open-squashfs-image

> Also could u package goverlay as an appimage

I would package anything if I only knew what it was... and if all my AppImages worked 100%... and if I didn't have [so many to maintain](https://github.com/ivan-hc#my-appimage-packages).

The truth is that I have used Webcamoid many times in the past, so I knew the program quite well. For me, packaging it this way was not too difficult.

But as I said [here](https://github.com/ivan-hc/AM/issues/983), I risk creating too many programs that don't work, just because I dared to work on something I don't know.

My [Steam AppImage](https://github.com/ivan-hc/Steam-appimage), for example, is the result of almost 2 years of searching for the right tools... and especially for the right collaborators, since I don't have a Steam account. In this sense, @Samueru-sama has been way too helpful. If you look at the work done in the repository, 80% of the progress made is due to Samuel. I would never have managed to do it if I didn't have a collaborator who knew the program inside out and how to modify it to make it work better.

That said, the same thing as Lutris, in the other [issue](https://github.com/ivan-hc/AM/issues/983), applies: I could consider providing a base, but to work on a project, I need to have someone who knows the program thoroughly. And that's why I haven't made an AppImage of Lutris. It's a program I don't know. So I don't want to take the risk of creating something I wouldn't know how to fix. I already have other AppImages to fix.

Anyway, if you or anyone is willing to package "[Archimage](https://github.com/ivan-hc/ArchImage)" (which is the basis on which I created Webcamoid), I will be very happy to help, in your repository. "Archimage" is something I am improving day by day, and I would like to make it even better. To do that I need to check the use cases and educate others on its use, so that I have enough contributors to allow you to create all the AppImages that I was not able or would not be able to create, due to my lack of knowledge.

If you are interested, follow the instructions on the README

https://github.com/ivan-hc/ArchImage

 it is not difficult at all to get started.
